### ISSUE TITLE
Debug Executable always checked on Run Action

### ISSUE THREAD

**Issue by sassiwalid** [yonaskolb/XcodeGen#1000]
Hi, I have a really issue when I Launch my app on release ( version test flight) and I think that is due to debug executable that is always checked and I didn't find how to deactivate.

<img width="365" alt="Capture d’écran 2021-01-05 à 20 50 44" src="https://user-images.githubusercontent.com/10390684/103692680-6e5acd80-4f98-11eb-9ab3-2b25d90e3e01.png">
 in my project.yml, I tried to use the debug enabled attribute but nothing work!!

run:
      debugEnabled: false

I think that is related to this issue 
selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"

and It's revealed in this issue also [https://github.com/yonaskolb/XcodeGen/issues/485](url)
and when I check XcodeGen code, it should work !!!!
```
private func selectedLauncherIdentifier(for target: Target?, run: Scheme.Run?) -> String {
        if target?.type.canUseDebugLauncher != false && run?.debugEnabled ?? Scheme.Run.debugEnabledDefault {
            return XCScheme.defaultLauncher
        } else {
            return "Xcode.IDEFoundation.Launcher.PosixSpawn"
        }
    }
```

**Comment by sassiwalid** [comment]
the problem that my Xcodegen version installed with brew is not stable 2.6.0 and with 2.18 is work fine the debugger executable sorry :(

**Comment by NrmeenTomoum** [comment]
@sassiwalid where exactly you add 
debugEnabled: false
it, can you help, thanks in advance
