### ISSUE TITLE
Using XcodeGen directly from swift

### ISSUE THREAD

**Issue by raptorxcz** [yonaskolb/XcodeGen#1001]
Hello,

we migrated our supporting scripts from bash to Swift. We made `Package.swift` for new script file and imported XcodeGen as a dependency. 

I want to start start XcodeGen directly from swift, but I can not find a way. I am missing something?

I found file `XcodeGenCLI.swift` and `GenerateCommand.swift` which contains desired interface, but it is not accessible from Swift though SPM. 

Thank you

**Comment by yonaskolb** [comment]
Hi @raptorxcz. You should be able to import `XcodeGenKit` and then copy the relevant calling code from `GenerateCommand` into your script

**Comment by raptorxcz** [comment]
I was hoping I can aviod copying files, but thank you 🙂
Fast response 👍👍
