### ISSUE TITLE
Support for multiple sub-specs that combine to form one full spec

### ISSUE THREAD

**Issue by daltonclaybrook** [yonaskolb/XcodeGen#1002]
As the number of targets in our Xcode project has grown, so proportionally has the size of our `project.yml`. I think the ability to have multiple small sub-specs that combine to form a single full project spec would be a very useful addition to XcodeGen. I'm sure the maintainers would have good opinions on how this should work in practice, but it seems like all supported fields in a project spec should be supported in sub-specs, and XcodeGen could perform a deep merge of all these fields before processing. I could also see this feature being useful for generating smaller Xcode projects when testing isolated features, but that is not necessarily a goal of this issue. Of course, XcodeGen would need a mechanism for locating each of these sub-specs. Perhaps XcodeGen could perform a deep search beneath the current directory looking for files matching a naming convention. If that is too invasive/error-prone, perhaps a new `includes` or `extends` key could be added to the root project spec for specifying all child sub-specs.

**Comment by yonaskolb** [comment]
Hi @daltonclaybrook. This feature is already present with `include` https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#include

**Comment by daltonclaybrook** [comment]
Whoops, I must have overlooked this feature. Thanks!
