### ISSUE TITLE
Correct way to reference an XCFramework dependency? 

### ISSUE THREAD

**Issue by pouty18** [yonaskolb/XcodeGen#1005]
I'm preparing my project for the upcoming Carthage release, which will build dependencies as XCFrameworks. How do I properly indicate a dependency on an XCFramework in my project.yml project spec?

Second question: Is there a way to disable the carthage copy files script being automatically added: 
 ```If any applications contain carthage dependencies within itself or any dependent targets, a carthage copy files script is automatically added to the application containing all the relevant frameworks. A FRAMEWORK_SEARCH_PATHS setting is also automatically added```
For context, in the upcoming carthage release, they indicate that you'll no longer need to include a run script to call `carthage copy-frameworks`, and including this would actually introduce breaking changes to the currently `carthage update --use-xcframeworks` flow.

**Comment by yonaskolb** [comment]
See https://github.com/yonaskolb/XcodeGen/issues/1006
