### ISSUE TITLE
basedOnDependencyAnalysis flag ignored in build steps

### ISSUE THREAD

**Issue by Peter-Nagy** [yonaskolb/XcodeGen#1014]
Using version 2.18.0 `basedOnDependencyAnalysis` gets completely ignored.

There is already an example in the repo where it can be reproduced: https://github.com/yonaskolb/XcodeGen/blob/0eeb6369ecb407e5bc5940fb563e486fbf225883/Tests/Fixtures/TestProject/project.yml#L147

If you run `xcodegen` for this project, the following code will be generated in `project.pbxproj`:
```
		71A4CC6ECC8522178F566E7B /* Strip Unused Architectures from Frameworks */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputFileListPaths = (
			);
			inputPaths = (
			);
			name = "Strip Unused Architectures from Frameworks";
			outputFileListPaths = (
			);
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 1;
			shellPath = /bin/sh;
			shellScript = "...";
		};
```

Instead of:
```
		71A4CC6ECC8522178F566E7B /* Strip Unused Architectures from Frameworks */ = {
			isa = PBXShellScriptBuildPhase;
			alwaysOutOfDate = 1;
			buildActionMask = 2147483647;
			files = (
			);
			inputFileListPaths = (
			);
			inputPaths = (
			);
			name = "Strip Unused Architectures from Frameworks";
			outputFileListPaths = (
			);
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 1;
			shellPath = /bin/sh;
			shellScript = "";
		};
```

The difference is the missing `alwaysOutOfDate = 1;`.

**Comment by Peter-Nagy** [comment]
Just realised `basedOnDependencyAnalysis` is not released yet.

**Comment by wooseongkim-29cm** [comment]
@Peter-Nagy @yonaskolb Is there any plans to release `basedOnDependencyAnalysis` option? Xcode 14 shows warning because of this when using script like SwiftLint

Hope this will be released soon 🙏
