### ISSUE TITLE
[Regression] .storekit files are not considered bundled resources by default in 2.19.0

### ISSUE THREAD

**Issue by liamnichols** [yonaskolb/XcodeGen#1025]
This follows my comment in https://github.com/yonaskolb/XcodeGen/pull/964/files#r581035944, I'm just opening it as a standalone ticket for a bit more visibility. 

The recent change in #964 causes **.storekit** files to not be defined a build rule by default so starting in 2.19.0 we have to explicitly declare the build rule of the source file if we want to use it in a Unit or UI Test target:

```yml
sources:
  - path: GlobalTests/Classes/Common/Utilities/Payments/StoreKitConfiguration.storekit
    buildPhase: resources
```

https://github.com/yonaskolb/XcodeGen/blob/17b40a328889b3abca05dbee98598c1fec042116/Sources/ProjectSpec/FileType.swift#L113

I see both sides to the story so I'm not completely sure what we want to do here:

- If the **.storekit** file is used purely for the StoreKit Configuration run option in a scheme, there is no need to bundle it as part of the target resources since Xcode loads it at runtime.
- If the **.storekit** file is however used by [`SKTestSession`](https://developer.apple.com/documentation/storekittest/sktestsession)'s `init(configurationFileNamed:) thows` method, then the file must be bundled as a resource to be loaded at runtime by the app (rather than Xcode). 

My gut feeling is that we should respect the previous behaviour and require that excluding the file from the bundle resources is an opt-in action, but I'm not 100% sure if I'm missing something or if this is inline with the strategy of similar scenarios?

**Comment by jcolicchio** [comment]
@liamnichols I think we should default to copying the file to bundle resources for any target we include the *.storekit* file, as Xcode does by default.

Anyone who wants to use the *.storekit* without copying it to a bundle resource, purely for the scheme, can use the *fileGroups* project setting to include the *.storekit* in the project without including it as part of any target.

I'll try to tackle this issue today, and validate that *.storekit* files can be used in the scheme without being added to any particular target 👍
