### ISSUE TITLE
xcodegen command does not work

### ISSUE THREAD

**Issue by durul** [yonaskolb/XcodeGen#104]
I am getting error "Parsing spec failed: The file “project.yml” couldn’t be opened because there is no such file."

**Comment by yonaskolb** [comment]
Hi @durul. Are you running the command in a directory that contains a `project.yml` file? Otherwise are you passing the `--spec` flag to point to the file?

**Comment by durul** [comment]
Hi @yonaskolb I am running the command in directory included ```project.yml``` file.

**Comment by yonaskolb** [comment]
Ok interesting. Maybe your file is actually called `project.yaml`? (notice the extension) Otherwise is it using any `includes` or can you share your spec?

**Comment by durul** [comment]
no problem, I found the problem. ```sudo xcodegen``` works

**Comment by yonaskolb** [comment]
Oh ok, interesting. You're in a directory where you don't have access to even read files I guess
