### ISSUE TITLE
CommandLineArguments wrong documented for Schemes

### ISSUE THREAD

**Issue by mariohahn** [yonaskolb/XcodeGen#1044]
According to your documentation CommandLineArguments have to be set different for Schemes: https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#environment-variable

In real they just have to be set like the ones for the Target: 
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme

**Comment by AlanWestbrook** [comment]
Oh man, thank you so much!

**Comment by yonaskolb** [comment]
Thanks for noticing that! It's updated now https://github.com/yonaskolb/XcodeGen/commit/9df3e62734fd8a2f5af8f04337ba4d93a4a5370c
