### ISSUE TITLE
Error installing xcodegen today

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#1053]
brew install xcodegen failed -- out: (==> Downloading https://homebrew.bintray.com/bottles/xcodegen-2.18.0.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "xcodegen"
Download failed: https://homebrew.bintray.com/bottles/xcodegen-2.18.0.catalina.bottle.tar.gz) err: (exit status 1)
INFO[15:22:02] Failed to install (xcodegen) with brew

**Comment by diegolechado** [comment]
I had the same problem

**Comment by brandtdaniels** [comment]
This seems to have now resolved itself

**Comment by misyobun** [comment]
It's no longer a 403, but this time it returns 404 and the file doesn't seem to exist.

```
==> Downloading https://homebrew.bintray.com/xcodegen-2.20.0.catalina.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/xcodegen-2.20.0.catalina.bottle.tar.gz
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew%2Fcore%2Fxcodegen-2.20.0.catalina.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "xcodegen"
Download failed: https://ghcr.io/v2/homebrew/core/xcodegen-2.20.0.catalina.bottle.tar.gz
```

**Comment by stefanengel** [comment]
The downtime of bintray was planned as a warning since the service will be sunsetted on may 1st: https://status.bintray.com/incidents/x1dvhtdqkcnx

Homebrew already migrated away from bintray so you should update your homebrew installation before may 1st: https://github.com/Homebrew/brew/issues/11123

**Comment by lozhuf** [comment]
For those using homebrew via a GitHub action, there is an issue with GH's `macOS-latest` environment using old homebrew, which it sounds like they will be fixing soon:
https://github.com/actions/virtual-environments/issues/3165

**Comment by yonaskolb** [comment]
Closing this as I believe it's fixed
