### ISSUE TITLE
2.20 binary points to 2.19 binary

### ISSUE THREAD

**Issue by simonpierreroy** [yonaskolb/XcodeGen#1060]
The binary found in release [2.20](https://github.com/yonaskolb/XcodeGen/releases/tag/2.20.0), precisely [2.20.0/xcodegen.zip](https://github.com/yonaskolb/XcodeGen/releases/download/2.20.0/xcodegen.zip) is in fact version 2.19 of XcodeGen [2.19.0/xcodegen.zip](https://github.com/yonaskolb/XcodeGen/releases/download/2.19.0/xcodegen.zip).

Running `xcodegen version` returns `2.19` on both binaries and they have the same `shasum-512` (using `shasum -a 512 path_to_binary` on macOS) .

**Comment by yonaskolb** [comment]
Thanks for reporting @simonpierreroy! The release should now have the correct binary
