### ISSUE TITLE
Something missing in the readme?  `swift run xcodegen` error

### ISSUE THREAD

**Issue by multitudes** [yonaskolb/XcodeGen#1071]
I just started and I am a bit of a noob with this. Going through the `readme` and the first thing I see is 

## Use as CLI
```
git clone https://github.com/yonaskolb/XcodeGen.git
cd XcodeGen
swift run xcodegen
```
But when I do `swift run xcodegen` I get this error message. Maybe it is trivial... I am missing something
![Screenshot 2021-05-05 at 16 20 19](https://user-images.githubusercontent.com/29355828/117156350-de018d80-adbd-11eb-96e6-409bb1e0ad44.png)

Xcode 12.5 - Big Sur - XCodegen 2.21.0

**Comment by yonaskolb** [comment]
All good @multitudes. It's case sensitive, so try `swift run xcodegen` and drop the capital X and G
