### ISSUE TITLE
xcodegen command gives spec validations error

### ISSUE THREAD

**Issue by DavidWoohyunLee** [yonaskolb/XcodeGen#1077]
![Screen Shot 2021-05-06 at 7 33 40 PM](https://user-images.githubusercontent.com/74229219/117381658-314d0c00-aea2-11eb-8a71-86837b0612bd.png)

im getting this error when i run xcodegen. Can someone please help?

**Comment by yonaskolb** [comment]
Can you post the list of your `configs` in the project.yml?

**Comment by yonaskolb** [comment]
And what version of XcodeGen is this on? 
```
xcodegen version
```

**Comment by DavidWoohyunLee** [comment]
configs:
  Debug (Development): debug
  Debug (Staging): debug
  Debug (Production): debug
  Release (Development): release
  Release (Staging): release
  Release (Production): release
configFiles:
  Debug (Development): Config/Development.xcconfig
  Debug (Staging): Config/Staging.xcconfig
  Debug (Production): Config/Production.xcconfig
  Release (Development): Config/Development.xcconfig
  Release (Staging): Config/Staging.xcconfig
  Release (Production): Config/Production.xcconfig

 $ xcodegen version
Version: 2.22.0

Thank you yonas

**Comment by DavidWoohyunLee** [comment]
![Screen Shot 2021-05-06 at 11 58 14 PM](https://user-images.githubusercontent.com/74229219/117399808-f90bf480-aec6-11eb-93e8-b91aa178222d.png)
I am guessing this is causing the problem?

**Comment by stefanomondino** [comment]
@DavidWoohyunLee I had the same problem when using "Devel Archive" and "Devel Run" in my configuration names.

It appears that the definition of "Config Variant" assumes that you always include the words "Debug" and "Release" in your config name, right after the "variant" name and not before.

In my case I had to switch "Devel Run" to "Devel Debug" and "Devel Archive" to "Devel Release" and everything started to work again. 

From documentation:
> This generates a scheme for each entry, using configs that contain the name with debug and release variants. This is useful for having different environment schemes.

I guess it's assumed that "debug" and "release" should be placed at the end of config name, not at start.

**Comment by yonaskolb** [comment]
@DavidWoohyunLee yeah I think this is due to stricter config name checking that was introduced. It was all done to make sure `Prod` wasn’t matched with `PreProd`.

Putting `()` here should fix your case If you’d like to make a PR. https://github.com/yonaskolb/XcodeGen/commit/8a0615e883584b221c7433d66c22668b4c409899#diff-39d57f23780cc020ad2c08c24062fb7ba4c9f19dd0f417dd5636f6315c261941R31

To workaround this in the time being you would need to add the parentheses to your config variants, or remove them from the config names.
Let me know how you go.

**Comment by DavidWoohyunLee** [comment]
Hello yonas, I just opened the PR. Please check! Thank you

https://github.com/yonaskolb/XcodeGen/pull/1078

**Comment by DavidWoohyunLee** [comment]
@yonaskolb Could you tell me when you will be releasing a new version?

**Comment by yonaskolb** [comment]
@DavidWoohyunLee this is now released

**Comment by hsncr** [comment]
In my case I was using config variants like following and it was working; now I removed parenthesis to fix the issue.
  
  configVariants:
        - (Development)
        - (Staging)
        - (Production)
