### ISSUE TITLE
Static Library needs to be removed add add manually to work again

### ISSUE THREAD

**Issue by dungi** [yonaskolb/XcodeGen#1106]
I added a static library from google like this:

```
- framework: Project/Externals/GoogleAnalytics/libGoogleAnalyticsServices.a
  embed: false
```

But Xcode tell me this error:

```
ld: library not found for -lGoogleAnalyticsServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I remove the **libGoogleAnalyticsServices.a** from "Link Binary with Libraries" and add **libGoogleAnalyticsServices.a** again the app builds normally and runs.

So I don't know what's the error here. I use Xcode 12.5. The project looks exactly the same after running xcodegen and removing and adding **libGoogleAnalyticsServices.a** manually again. So I try to find the error, but couldn't.

**Comment by dungi** [comment]
I fixed it with adding

`LIBRARY_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Project/Externals/GoogleAnalytics`

**Comment by WeijunDeng** [comment]
However, LIBRARY_SEARCH_PATHS should be added automatically in this case, I Think.
