### ISSUE TITLE
Feature request: Expose merged/resolved yaml

### ISSUE THREAD

**Issue by namolnad** [yonaskolb/XcodeGen#1111]
Hi there,

I'm wondering if it would be possible to somehow expose the merged/fully-resolved yaml/json after templates and templateAttributes have been replaced — likely via a new `xcodegen` command.
### Background
My team has broken down our project spec into a series of `BUILD.yml` files as well as separate template files all added together with our `project.yml` file via `includes` directives. We've recently started adding metadata to the yml target definitions to provide our tooling with additional context about a given framework. I've been able to merge the yaml together by creating a custom yaml loader and some merging functions, but the templateAttributes is something I haven't taken on yet and I'm curious if all of this is something that would be relatively simple to expose from XcodeGen. Would love to hear your thoughts. Thanks!

**Comment by yonaskolb** [comment]
Hi @namolnad, you're in luck, as I believe the dump command already does what you're looking for.
```
xcodegen dump --type yaml
```
See help for the different formats you can output
```
xcodegen dump help
```

Closing this, but you can reopen if you run into any troubles.

**Comment by namolnad** [comment]
🤦‍♂️ can't believe I missed this :) Thanks so much for the quick response!
