### ISSUE TITLE
Failed to resolve xcodegen 2.17.0 with SPM

### ISSUE THREAD

**Issue by DidiFly** [yonaskolb/XcodeGen#1113]
make open
/Applications/Xcode12.2.app/Contents/Developer/usr/bin/make generate-xcodeproj
mint run xcodegen
🌱 Cloning xcodegen 2.17.0
🌱 Resolving package
error: Failed to clone https://github.com/mxcl/Version:
    Cloning into bare repository '/private/var/folders/ld/04g5h8yx3w72_0wr7k8bsvxc0000gn/T/mint/github.com_yonaskolb_xcodegen/.build/repositories/Version-9ad39a68'...
    fatal: unable to access 'https://github.com/mxcl/Version/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve xcodegen 2.17.0 with SPM
make[1]: *** [generate-xcodeproj] Error 1
make: *** [open] Error 2

**Comment by yonaskolb** [comment]
Seems like a network error with Github, and not related to XcodeGen. Maybe try again?

**Comment by DidiFly** [comment]
> 似乎是 Github 的网络错误，与 XcodeGen 无关。也许再试一次？

I tried a lot of times, every time 443 appeared in mxcl, github.com has been pinged, and the status is accessible

**Comment by DidiFly** [comment]
> 似乎是 Github 的网络错误，与 XcodeGen 无关。也许再试一次？

You are right, thank you for your reply
