### ISSUE TITLE
Broken link in Usage.md

### ISSUE THREAD

**Issue by adamawolf** [yonaskolb/XcodeGen#1114]
In file https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md

> You can change or disable how these setting presets are applied via the options.settingPresets which you can find more about in Options

where Options links to a #options header in the same page that is no longer there.

**Comment by adamawolf** [comment]
looks like what you wanted was https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#options

**Comment by yonaskolb** [comment]
Thanks for fixing 👍
