### ISSUE TITLE
Generate project spec from xcode project.

### ISSUE THREAD

**Issue by lukewakeford** [yonaskolb/XcodeGen#1126]
Or 'convert xcode project to xcodegen project spec'.

Just a feature suggestion that might enabled people to get started with xcodegen a little quicker.

Personally I have a number of internal frameworks that still have `.xcodeproj` files in git. I find myself wanting to convert these to project specs but slightly daunted by the task as I don't want to lose any config.

Would be great if this already exists or there is already a nice process someone has documented for this but i've not found any other approach than to start again from scratch.

Cheers'n

**Comment by 4brunu** [comment]
You may want to take a look at https://github.com/yonaskolb/XcodeGen/pull/735

It's not complete but it helped me a lot, I would say it did 80% of the work which was incredibly helpful.

**Comment by lukewakeford** [comment]
Awesome thanks 👍🏻
