### ISSUE TITLE
Duplicate elements of type 'PBXFileElement' were found in a Set

### ISSUE THREAD

**Issue by dalemyers** [yonaskolb/XcodeGen#1131]
We are seeing this error regularly:

```
⚙️  Generating plists...
⚙️  Generating project...
Fatal error: Duplicate elements of type 'PBXFileElement' were found in a Set.
This usually means either that the type violates Hashable's requirements, or
```

Our project is quite large, but we have no insight into what is going on here. Re-running xcodegen solves this, so it's likely a race condition somewhere. I've got a PR which adds some debug logging to hopefully help try and track it down: https://github.com/yonaskolb/XcodeGen/pull/1128

**Comment by guojiubo** [comment]
Any updates on this?

**Comment by vguerci** [comment]
Gave a look at this yesterday, as we were having the same issue breaking our CI randomly.

Basically, `XcodeProj`'s `PBXObject` and inherited classes are not respecting `Hashable` requirements. Two different instances (not equal) can have the same hash, which leads randomly to this issue.

Tried to fix that naively, to realise it was more complex, so closed my Fix above.

**Comment by dungi** [comment]
Does someone find a fix for this yet?

**Comment by dalemyers** [comment]
Thankfully my new project reproduced the issue much more frequently and I was able to create a fix: https://github.com/yonaskolb/XcodeGen/pull/1341

**Comment by dalemyers-flipdish** [comment]
Note: There may be multiple reasons for this error, but my fix corrects the one I'm seeing now at least. Try it and see if it fixes your own.

**Comment by vguerci** [comment]
Yes, it should work, this is how I fixed the issues on our side, avoiding the collision, by removing some trailing `/`.
