### ISSUE TITLE
Unwanted diff when modifying generated xcodeproj

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#114]
Xcode succeeds to open generated xcodeproj, but generates a lot of diffs when you add files from Xcode.

<img width="698" alt="screen shot 2017-10-29 at 22 41 05" src="https://user-images.githubusercontent.com/6007952/32144310-4b63ebf6-bcfa-11e7-9398-ad1812b68557.png">

This is problem especially when I'm debugging generated xcodeproj, trying to figure out what is correct structure for specific state. I want to edit xcodeproj to expected state, then check `git diff` to recognize what was wrong in XcodeGen.

So I guess the goal is Xcode creating no diffs when modifying generated xcodeproj.

**Comment by yonaskolb** [comment]
I'll try and get this resolved after the next `xcproj` release which fixes some missing defaults
