### ISSUE TITLE
Ability to use custom location for local Swift packages

### ISSUE THREAD

**Issue by John-Connolly** [yonaskolb/XcodeGen#1173]
It's not uncommon to use swift packages to separate apps into different modules for features.  Currently, the configuration for swift packages is not flexible enough to allow packages to live outside of the main packages folder.  This is not ideal for apps that are heavily modularized. I have a PR forthcoming that will support this configuration. 

I believe this would also address https://github.com/yonaskolb/XcodeGen/issues/1118

Example: Packages can live within their domains in an apps folder structure.
<img width="619" alt="Screen Shot 2022-02-14 at 1 13 42 PM" src="https://user-images.githubusercontent.com/8390081/153947492-4f7a8502-7606-45c0-a84b-ffaca44fa1a4.png">
,

**Comment by John-Connolly** [comment]
@yonaskolb I have been using this change locally.  Would you be open to upstreaming this change?

**Comment by MartinP7r** [comment]
@John-Connolly is there a way to realize a package located at the root (outside of any group) of a project with your changes from #1175 ? 

If not would you be able to advise in these issues? #1209
