### ISSUE TITLE
Feature request: Test duplicated dependencies

### ISSUE THREAD

**Issue by imWildCat** [yonaskolb/XcodeGen#1186]
In the yaml file, it is easy to add duplicated dependencies of a target.

Could we have a feature which can prevent this from happening?

If so, I can start to draft a PR.

**Comment by yonaskolb** [comment]
Is this what you want? https://github.com/yonaskolb/XcodeGen/pull/1187

**Comment by imWildCat** [comment]
Yeah! Thanks!
