### ISSUE TITLE
Release xcodegen 2.27.0 on homebrew

### ISSUE THREAD

**Issue by dehlen** [yonaskolb/XcodeGen#1192]
Hey,

it seems like 2.27.0 was released but no PR on hombrew-core was opened. Would you mind running the `make brew` command to update the new version on homebrew?

Kind regards,
David

**Comment by yonaskolb** [comment]
PR opened here https://github.com/Homebrew/homebrew-core/pull/97502 
I was having some troubles with homebrew

**Comment by yonaskolb** [comment]
Has been merged in homebrew
