### ISSUE TITLE
Version 2.28.0 is not published to homebrew

### ISSUE THREAD

**Issue by tr1ckyf0x** [yonaskolb/XcodeGen#1207]
The latest version 2.28.0 is not published to homebrew. It shows current stable version 2.27.0.

https://formulae.brew.sh/formula/xcodegen

**Comment by yonaskolb** [comment]
Old brew PR was closed, new one here. It's still failing for some reason though https://github.com/Homebrew/homebrew-core/pull/99017

**Comment by yonaskolb** [comment]
PR was merged
