### ISSUE TITLE
Caching doesn't pickup file changes

### ISSUE THREAD

**Issue by bonkey** [yonaskolb/XcodeGen#1212]
I've just noticed that XcodeGen executed with `--use-cache` doesn't pick up file changes.

XcodeGen 2.28.0
macOS 12.3.1 (21E258)

Here's a sample project: https://github.com/bonkey/xcodegen-test-cache

Output:

```
➜ make
rm -rf Kaboom.xcodeproj
echo "\nstruct Foo {}" > Sources/Foo.swift
mint run XcodeGen --use-cache
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/dbauke/Projects/xcodegen-test-cache/Kaboom.xcodeproj
echo "\nstruct Bar {}" >> Sources/Foo.swift
mint run XcodeGen --use-cache
Project has not changed since cache was written
sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```

_UPDATE: I modified the sample project a bit to always use a cache, and that makes the remark below irrelevant._

~The same is with `2.27.0`, but on the first run, when it was compiled from mint, it didn't use cache – as expected:~

<details>
<summary>Irrelevant sample</summary>
<pre>
➜ make
rm -rf Kaboom.xcodeproj
echo "\nstruct Foo {}" > Sources/Foo.swift
mint run XcodeGen
🌱 Cloning XcodeGen 2.27.0
🌱 Resolving package
🌱 Building package
🌱 Copying resources for XcodeGen: SettingPresets ...
🌱 Installed XcodeGen 2.27.0
🌱 Running xcodegen 2.27.0...
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/dbauke/Projects/xcodegen-cache-test/Kaboom.xcodeproj
echo "\nstruct Bar {}" >> Sources/Foo.swift
mint run XcodeGen --use-cache
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/dbauke/Projects/xcodegen-cache-test/Kaboom.xcodeproj
➜ make
rm -rf Kaboom.xcodeproj
echo "\nstruct Foo {}" > Sources/Foo.swift
mint run XcodeGen
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/dbauke/Projects/xcodegen-cache-test/Kaboom.xcodeproj
echo "\nstruct Bar {}" >> Sources/Foo.swift
mint run XcodeGen --use-cache
Project has not changed since cache was written
</pre>
</details>

**Comment by bonkey** [comment]
Actually, adding at least a timestamp in https://github.com/yonaskolb/XcodeGen/blob/35212a6154a36d2e77ca5f3b63f6218e5ebb38e7/Sources/ProjectSpec/CacheFile.swift#L14 should resolve that issue.

What do you think?

**Comment by yonaskolb** [comment]
Changes to the contents of files does not dirty the cache as this doesn't affect the Xcode project, only when files are added or removed. Do you have a use case where the contents of files results in a different project?

**Comment by bonkey** [comment]
Of course, I actually didn't think about it. The content doesn't matter for the project structure.

It must've been some other case not specifically related to the cache that project generation didn't happen (eg. git hook failed). Unfortunately, can't say more as it was not on my machine.

I think we can actually close it because adding timestamps to files is rather counter-productive for cache in general, isn't it?
