### ISSUE TITLE
Install Slack Integration

### ISSUE THREAD

**Issue by skofgar** [yonaskolb/XcodeGen#1215]
Hello @yonaskolb 

I'd love to configure one of our Slack channels to get automatically get notified, whenever there's a new release of XcodeGen. 

Can you potentially add the Slack app https://github.com/apps/slack ? 
Documentation: https://slack.github.com/

This should allow us to subscribe to releases of XcodeGen with this command:

```
/github subscribe yonaskolb/XcodeGen releases
```

**Comment by yonaskolb** [comment]
Done, I think. Feel free to reopen if any issues

**Comment by skofgar** [comment]
Thank you very much!
