### ISSUE TITLE
Localised files with same name aren't generated properly

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#122]
If localized files have with the same name but different extensions, they are generated incorrectly

<img width="270" alt="screen shot 2017-11-02 at 1 39 35 pm" src="https://user-images.githubusercontent.com/2393781/32326518-65e04034-bfd3-11e7-9c3c-c2019cbe8118.png">

**Comment by yonaskolb** [comment]
@ryohey are you able to take a look at this?

**Comment by ryohey** [comment]
@yonaskolb I'll look into it.
