### ISSUE TITLE
Universal binary doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by gyulavoros** [yonaskolb/XcodeGen#1220]
A universal binary is available from the GitHub release: https://github.com/yonaskolb/XcodeGen/releases/download/2.29.0/xcodegen.zip.

Looking at the binary, it seems to contain both architectures:
```
$ file xcodegen
xcodegen: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64]
xcodegen (for architecture x86_64):	Mach-O 64-bit executable x86_64
xcodegen (for architecture arm64):	Mach-O 64-bit executable arm64
```

However, executing the binary results in the following output and generates a faulty `xcodeproj` file:
```
⚙️  Generating plists...
⚙️  Generating project...
No "base" settings found
No "debug config" settings found
No "release config" settings found
No "iOS" settings found
⚙️  Writing project...
```

I did some investigation and tried to build the binary on both machines, Intel and M1 with the following command:
```
xcrun swift build --disable-sandbox -c release --arch arm64 --arch x86_64
```

It seems that:
- If I build the universal binary on M1, it works correctly on M1, but not on Intel.
- If I build the universal binary on Intel, it works correctly on Intel, but not on M1.

**Comment by gyulavoros** [comment]
It was my bad, I didn't consider the `SettingPresets` folder, now I found a way to make it work.

**Comment by MalleswariDazn** [comment]
Hi @gyulavoros 
 I have the same issue,  how did you fixed this issue.

**Comment by gyulavoros** [comment]
To make the self-complied universal binary work, we needed to copy the `SettingPresets` folder in this repo to our project's root directory. But I haven't investigated further; it was a while ago, so there might be better solutions, or since then, it might be irrelevant.
