### ISSUE TITLE
Question: Address sanitizer?

### ISSUE THREAD

**Issue by jfaust** [yonaskolb/XcodeGen#1223]
Hey, was looking for this and didn't find it. Is there a way to enable Address Sanitizer (or Thread Sanitizer) on a Scheme?

**Comment by freddi-kit** [comment]
Sorry for late. Currently sanitizer can be specified in .xcscheme file directly and it cannot be set from project.yml file

**Comment by jfaust** [comment]
Ah, got it - I didn't realize that was an option, but in retrospect I should have. Thanks!
