### ISSUE TITLE
Xcode14: Rename "Embed App Extensions" to "Embed Foundation Extensions"

### ISSUE THREAD

**Issue by clausjoergensen** [yonaskolb/XcodeGen#1238]
Xcode 14 beta 3 is giving a warning about the "Embed App Extensions" name saying it should be renamed to "Embed Foundation Extensions" not to conflict with "Embed ExtensionKit Extensions" (which was implemented in #1224)

![Screenshot 2022-07-28 at 11 00 18](https://user-images.githubusercontent.com/233721/181466125-5c82861d-db1d-48cd-bef4-a2a7f0282422.png)

**Comment by Dennisdezhangaho** [comment]
I want to know how could I just ignore it, cause when I accept this change, my app crash. but, unfortunately Xcode 14 force me to do it.

**Comment by adamcarter93** [comment]
I've found this warning myself which is currently sitting in my project (using Tuist v3.15.0 which is the current latest)

<img width="578" alt="Screenshot 2023-01-01 at 15 27 57" src="https://user-images.githubusercontent.com/14096630/210176433-804755ef-06c7-45c6-aa65-02dc179310fd.png">

**Comment by yonaskolb** [comment]
@Dennisdezhangaho, interesting that you say your app crashes after allowing Xcode to make this change. Has anyone else seen this? Does #1310 solve your issue?
@casperriboe did you run into this in your PR?

**Comment by casperriboe** [comment]
> @casperriboe did you run into this in your PR?
Nope didn't happen to me. Don't remember Xcode ever crashing on me after grabbing the suggested changes. Sounds like a fluke if it was just once.
