### ISSUE TITLE
Using Xcode Build Tool Plug-ins

### ISSUE THREAD

**Issue by nico-dkd** [yonaskolb/XcodeGen#1269]
Hi together, 

I have written a swift package that contains a plugin which is defined as a build tool.

Am I right with my assumption that it is not yet possible to configure my project setup in a way to add the named swift package build tool plugin under my project's _Build Phases_, _Run Build Tool Plug-ins_? 

Any help is highly appreciated. 

![Screenshot 2022-09-30 at 14 09 59](https://user-images.githubusercontent.com/18416657/193266668-115c228b-672a-4c8b-b96e-52b342d2b3c0.png)

XcodeGen Version: 2.32.0

**Comment by cal-os** [comment]
Hey @nico-dkd  - my understanding is that a build tool plugin needs to be installed as a dependency on a specific target as defined in your Package.swift file. You can then integrate your local or remote package via XcodeGen by following the project spec.

**Comment by cal-os** [comment]
Hey @nico-dkd - this is because you're applying the `MySwiftPackageBuildPlugin` product directly to your Xcode target. Instead, you should apply the plugin as a dependency to a Package target. That package target should then be included in the final product that you decide to build into XcodeGen as a dependency to your project "App" target.

```
targets:
  App:
    dependencies:
      package: MySwiftPackage
      product: MySwiftPackageProduct
```
and Package.swift
```
let package = Package(
    name: "MySwiftPackage",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MySwiftPackageProduct",
            targets: ["MySwiftPackageTarget"]),
    ],
    dependencies: [
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MySwiftPackageTarget",
            dependencies: [],
            plugins: [
                <my_plugin_target>
            ]
        )
    ]
)

```

**Comment by aaron-foreflight** [comment]
With Xcode 14 there is a new XcodeProjectPlugin framework available to integrate Swift Package Plugins with Xcode: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes (search "XcodeProjectPlugin" on that page). I don't have experience with it to help you out @nico-dkd, but you are right that you should be able to integrate your plugin with Xcode projects.

**Comment by yonaskolb** [comment]
Let us know how you go @nico-dkd. See if you can get it working by manually configuring the Xcode project within Xcode, to confirm whether it's something that needs to be added to XcodeGen.

**Comment by nico-dkd** [comment]
@yonaskolb What exactly do you mean when you say, to be clear what do I need to do?  
> ...manually configuring the Xcode project within Xcode...
I'm able to add my build plugin accordingly manually by hand.

**Comment by yonaskolb** [comment]
Discussion on implementation here https://github.com/yonaskolb/XcodeGen/issues/1290
