### ISSUE TITLE
sources "optional" has bug in targetTemplates

### ISSUE THREAD

**Issue by WeijunDeng** [yonaskolb/XcodeGen#1277]
template.yml

targetTemplates:
  T:
    sources:
      - path: a_path_maybe_optional
        optional: true

A.project.yml

targets:
  A:
    templates: [T]

B.project.yml

targets:
  B:
    templates: [T]

**Comment by yonaskolb** [comment]
Hi @WeijunDeng, do you have some more info? What is the problem you are running into?
It's hard to tell from the snippet you posted, but perhaps indentation is an issue. Make sure `optional: true` is at the same indentation as `- path: a_path_maybe_optional`
