### ISSUE TITLE
DEBUG_INFORMATION_FORMAT is always DWAFT for Debug config

### ISSUE THREAD

**Issue by ikajava** [yonaskolb/XcodeGen#1278]
Hi,
I'm facing the issue when updating DEBUG_INFORMATION_FORMAT to dwarf-with-dsym for default Debug config.

The actual value always remains DWARF.

<img width="502" alt="Screenshot 2022-10-24 at 15 21 42" src="https://user-images.githubusercontent.com/739367/197524510-d7c8306b-b8b3-43a0-93c3-44972a525dc5.png">
<img width="500" alt="Screenshot 2022-10-24 at 15 21 55" src="https://user-images.githubusercontent.com/739367/197524513-92840a7a-f720-46ad-8abd-36032c1fa4ca.png">

xcodegen version 2.32.0

**Comment by yonaskolb** [comment]
Did you figure this out @ikajava?

**Comment by zelanastasia** [comment]
Yeah, i facing the same problem, how it solved?

**Comment by ikajava** [comment]
@yonaskolb Yes, I did it, issue was in misconfigured hierarchy in my project side.

the syntax below works well.  
`
settings:
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
`
