### ISSUE TITLE
Xcode Build Tool Plugin support

### ISSUE THREAD

**Issue by technocidal** [yonaskolb/XcodeGen#1290]
@yonaskolb 

I'd really like to have support for Build Tool Plugins and I'd be happy to build it. Is there any ongoing work already or maybe research?

**Comment by technocidal** [comment]
Alright.

Some results:
- Plugins are stored as PBXTargetDependency objects
- Plugins are mentioned using its PBXTargetDependency ID in the `dependencies` section of the PBXNativeTarget
- Plugins are stored as a `XCSwiftPackageProductDependency` with the slight difference that the `productName` is prefixed with `plugin:`

Next I'll try to figure out if and how `XcodeProj` needs to be adapted to accommodate plugins. Maybe we can also implement this here first. AFAIK there is no current effort from `XcodeProj` to support this.

**Comment by technocidal** [comment]
Alright. Now with a little bit more clarity and care for grammar 🙂

# Proposal

This implementation will focus on supporting Xcode Build Tool Plugins that run during a build at basically the same time as a script defined in a  `Run Script Phase`.

The project file stores information about the usage of a package product as a plugin in 3 places.

A `XCSwiftPackageProductDependency` object is created that differs from the normal version by prefixing the value for the `productName` with the string `plugin:`.

Then a `PBXTargetDependency` is created that references the previously created product. This `PBXTargetDependency` is than stored inside the `dependencies` object of the `PBXNativeTarget` that the plugin was added to.

## Proposed Syntax

The idea is to closely mirror the `dependencies` object already found on a `target` and base the new `BuildToolPlugin` entity on the existing `Dependency` entity. This provides the necessary information to identify the package that contains the plugin and offers a familiar syntax for selecting a specific product from a previously defined dependency.

```yaml
targets:
    MyTarget:
        buildToolPlugins:
            - package: SwiftLint
              product: SwiftLintPlugin
```

## Scope

As Xcode doesn’t introduce any new types to represent Build Tool Plugins so it’s possible to implement this without changing `XcodeProj`. I also recognise that in the long run it'll be nice to have Plugins as their own types inside `XcodeProj` to make the prefix and storage inside `dependencies` instead of `packageProductDependencies` visible.

**Comment by yonaskolb** [comment]
A solid proposal @technocidal, it all sounds good to me. If you have the time and energy the work will be much appreciated, as others were asking about it here https://github.com/yonaskolb/XcodeGen/issues/1269

**Comment by technocidal** [comment]
@yonaskolb 

Thanks for your feedback! I'll start working on it this coming weekend.

**Comment by technocidal** [comment]
Progress 🎉

**project.yml**

```yaml
name: XcodeGen-Test
packages:
    SwiftLint:
        branch: main
        url: https://github.com/realm/SwiftLint
targets: 
    XcodeGen-Test:
        type: application
        platform: iOS
        settings: 
            GENERATE_INFOPLIST_FILE: true
        buildToolPlugins:
            - package: SwiftLint
              product: SwiftLintPlugin
        sources: XcodeGen-Test
```

**XcodeGen Output**

```bash
swift run --package-path ../XcodeGen
Building for debugging...
[60/60] Linking xcodegen
Build complete! (4.75s)
[ProjectSpec.BuildToolPlugin(package: "SwiftLint", product: "SwiftLintPlugin")]
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
```

**Comment by technocidal** [comment]
And we've got a working project. SwiftLint as a Build Tool Plugin in a generated project.
<img width="931" alt="Screenshot 2022-11-19 at 20 15 20" src="https://user-images.githubusercontent.com/14994778/202867673-2ef46f17-e5e3-4e4e-b556-15282c2e5121.png">

**Comment by technocidal** [comment]
Final Status Update for today:
It is necessary to implement plugin support for XcodeProj before it can be added to XcodeGen. Otherwise the plugin package product never gets a final identifier leading to ugly `TEMP` identifier in the generated project. It still works fine but I don't think it's the desirable outcome. I've finished the implementation in XcodeProj and will open an PR with them before continuing here.

You can find the working prototype that generates a valid project with `TEMP` identifiers here [Prototype](https://github.com/technocidal/XcodeGen/tree/feature/xcode-build-tool-plugin-support-with-temp-identifier)

**Comment by clausjoergensen** [comment]
@technocidal anything we can do to help speed this along? Getting plugin support would be glorious, specially as it would allow integrating SwiftLint seamlessly into our projects. 

Thanks!

**Comment by iteracticman** [comment]
We also would really want to use this ASAP and are also willing to help.

So @technocidal, can you please tell us if you intend to finish this and need help and/or more time or if you would rather have someone else take over?

**Comment by iammxrn** [comment]
Any updates? :) @technocidal @yonaskolb

**Comment by technocidal** [comment]
This is a repost of the update that I've posted to the XcodeProj PR


> I think I dropped the ball on this one. Sorry. I'll try to summarise my thoughts which I should've done way earlier.
>
> I can totally understand that getting this done would be a great thing but I'm a bit worried that this will generate a lot of follow-up maintenance. I've also worked on the Plugin Support for SwiftLint which has turned into a massive headache for everyone involved. There are a lot of edge case related to plugins that are not correctly handled by Xcode. This means that it is entirely possible that adding a plugin to your project breaks it. This happens with SwiftLint and it's dependency on swift-syntax quite a lot. You can find more details in this discussion.
>
> There are also some other weird linker issues that we've filed a Feedback (FB11877146) for but haven't heard from Apple yet.
>
> Regarding the actual implementation. I think I only need to update my fork and add finish implementing the test suite/fixtures but I'm a bit disheartened due to the problems mentioned above.

**Comment by sborovikov-belkacar** [comment]
Any updates? :) @technocidal @yonaskolb

**Comment by ronnie-codes** [comment]
Bump.

**Comment by BarredEwe** [comment]
I continued to add support for working with plugins 😊

I have already made a [branch](https://github.com/BarredEwe/XcodeGen/tree/feature/xcode-build-tool-plugin) where you can try plugins. The problems described by @technology above were solved there.

It is necessary to add [plugin support to XcodeProj](https://github.com/tuist/XcodeProj/pull/784) before it can be added to XcodeGen. 
You can try the working version in the branch I indicated above.

**Comment by BarredEwe** [comment]
> Alright. Now with a little bit more clarity and care for grammar 🙂
> 
> # Proposal
> This implementation will focus on supporting Xcode Build Tool Plugins that run during a build at basically the same time as a script defined in a `Run Script Phase`.
> 
> The project file stores information about the usage of a package product as a plugin in 3 places.
> 
> A `XCSwiftPackageProductDependency` object is created that differs from the normal version by prefixing the value for the `productName` with the string `plugin:`.
> 
> Then a `PBXTargetDependency` is created that references the previously created product. This `PBXTargetDependency` is than stored inside the `dependencies` object of the `PBXNativeTarget` that the plugin was added to.
> 
> ## Proposed Syntax
> The idea is to closely mirror the `dependencies` object already found on a `target` and base the new `BuildToolPlugin` entity on the existing `Dependency` entity. This provides the necessary information to identify the package that contains the plugin and offers a familiar syntax for selecting a specific product from a previously defined dependency.
> 
> ```yaml
> targets:
>     MyTarget:
>         buildToolPlugins:
>             - package: SwiftLint
>               product: SwiftLintPlugin
> ```
> 
> ## Scope
> As Xcode doesn’t introduce any new types to represent Build Tool Plugins it’s possible to implement this without changing `XcodeProj`. I also recognise that in the long run it'll be nice to have Plugins as their own types inside `XcodeProj` to make the prefix and storage inside `dependencies` instead of `packageProductDependencies` visible.

I think we should discuss this a little more. 

After a little digging in the [Swift Package Manager repository](https://github.com/apple/swift-package-manager), I found such a structure:


```swift
public enum PluginUsage {
    /// Specifies the use of a plug-in product in a package dependency.
    ///
    /// - Parameters:
    ///   - name: The name of the plug-in target.
    ///   - package: The name of the package that defines the plug-in target.
    case plugin(name: String, package: String?)
}

extension Target.PluginUsage {
    /// Specifies use of a plugin target in the same package.
    ///
    /// - Parameter name: The name of the plugin target.
    /// - Returns: A `PluginUsage` instance.
    public static func plugin(name: String) -> Target.PluginUsage {
        return .plugin(name: name, package: nil)
    }
}
```

I suggest making a similar API, for example this:

```yaml
targets:
  MyTarget:
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
```

**Comment by yonaskolb** [comment]
Thank you for picking this up @BarredEwe! Your suggested api looks good

**Comment by flopshot** [comment]
Should this issue be closed? Are spm plug-ins fully supported?

**Comment by truemetal** [comment]
Do we have an ability to specify params to build tool plugins, like e.g. SwiftLint config yaml file location?

**Comment by yonaskolb** [comment]
> Do we have an ability to specify params to build tool plugins, like e.g. SwiftLint config yaml file location?

I haven't spent to much time with build tool plugins, but is that possible to configure in the Xcode project by hand?

**Comment by BarredEwe** [comment]
> > Do we have an ability to specify params to build tool plugins, like e.g. SwiftLint config yaml file location?
> 
> I haven't spent to much time with build tool plugins, but is that possible to configure in the Xcode project by hand?

Unfortunately, build plugins do not support parameter passing. Maybe sometime later: https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md#type-safe-options
