### ISSUE TITLE
Included specs can no longer be referenced in XcodeGen 2.33.0

### ISSUE THREAD

**Issue by FelixLisczyk** [yonaskolb/XcodeGen#1299]
I have a project structure similar to this:

```
├── Configuration
│   ├── project.yml
│   └── targets.yml
└── Sources
    └── MyApp.swift
```

`project.yml`
```
name: MyProject
include:
  - targets.yml
options:
  bundleIdPrefix: com.myapp
```

`targets.yml`
```
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
```

In XcodeGen 2.32.0 and below, I could generate my Xcode project from the root directory with the following command:

`xcodegen --spec ./Configuration/project.yml --project-root . --project .`

Since XcodeGen 2.33.0, I get the following error message:

`Parsing project spec failed: Error Domain=NSCocoaErrorDomain Code=260 "The file “targets.yml” couldn’t be opened because there is no such file." UserInfo={NSFilePath=targets.yml, NSUnderlyingError=0x11ee32fd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

I tried to change the path of `targets.yml` to `Configuration/targets.yml`, but this also generates an error message:

`Spec validation error: Target "MyApp" has a missing source directory "Configuration/Sources"`

Is this a bug, or do I have to update my configuration? I didn't read about any breaking changes in the latest release notes. Thank you!

**Comment by PaulOmta-TomTom** [comment]
Probably introduced [in this commit](https://github.com/yonaskolb/XcodeGen/commit/e7f753785e6ee135e5ea77268d149e9cd10bb7ed#diff-8d851d8f8d10ea7a2d7d6d3f0ba6abb3cef3002a63bfdec8a314326029778606) where the project root is used (if it is given) instead of the current path. 

From the changelog, it seems to be the intention that both the project root, as well as the current directory are considered for includes. So this seems like a defect.

**Comment by yonaskolb** [comment]
cc @ma-oli

**Comment by FelixLisczyk** [comment]
Any updates on this issue?

**Comment by CraigSiemens** [comment]
@FelixLisczyk If you've got a chance, could you try out https://github.com/yonaskolb/XcodeGen/pull/1262 and let me know if it fixes the issue.

**Comment by FelixLisczyk** [comment]
Thanks, Craig! I've checked out the PR branch and built XcodeGen using `make build`. Unfortunately, the error message remains the same. I'll attach my sample project, which you can use to reproduce the issue. The build command is `xcodegen --spec ./Configuration/project.yml --project-root . --project .`

[XcodeGen-TestProject.zip](https://github.com/yonaskolb/XcodeGen/files/10424684/XcodeGen-TestProject.zip)

**Comment by FelixLisczyk** [comment]
This issue still occurs in the latest XcodeGen 2.34.0.

**Comment by grigorye** [comment]
> Probably introduced [in this commit](https://github.com/yonaskolb/XcodeGen/commit/e7f753785e6ee135e5ea77268d149e9cd10bb7ed#diff-8d851d8f8d10ea7a2d7d6d3f0ba6abb3cef3002a63bfdec8a314326029778606) where the project root is used (if it is given) instead of the current path.

In [my case](https://github.com/grigorye/TMBuddy) 2.34.0 (and 2.33) fail even if -r is not specified:
```
$ mint run xcodegen@2.32.0
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/eg/Workbench/TMBuddy/feature/XcodeGen-Test/TMBuddy.xcodeproj
$ mint run xcodegen@2.33.0
Parsing project spec failed: Error Domain=NSCocoaErrorDomain Code=260 "The file “Compact.yml” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/eg/Workbench/TMBuddy/feature/Compactness/Compact.yml, NSUnderlyingError=0x600003c9e520 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
$ mint run xcodegen@2.34.0
Parsing project spec failed: Error Domain=NSCocoaErrorDomain Code=260 "The file “Compact.yml” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/eg/Workbench/TMBuddy/feature/Compactness/Compact.yml, NSUnderlyingError=0x6000003982d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
$
```

**Comment by yonaskolb** [comment]
@ma-oli are you able to look into this as I believe [this PR ](https://github.com/yonaskolb/XcodeGen/pull/1275) broke things

**Comment by FelixLisczyk** [comment]
I was finally able to fix this issue by:

- Referencing the `include` files with their path relative to the project root directory.
- Adding `relativePaths: false` for each `include` entry.

Here is the updated `project.yml` file from my original post:

```
name: MyProject
include:
  - path: Configuration/targets.yml
    relativePaths: false
options:
  bundleIdPrefix: com.myapp
```

All paths inside `targets.yml` must also be relative to the project root directory.

I've tested this approach with the latest XcodeGen 2.35.0.
