### ISSUE TITLE
Xcodegen with Xcode 14.2 / macOS 13.1 / XcodeGen 2.33.0 can't generate project

### ISSUE THREAD

**Issue by dungi** [yonaskolb/XcodeGen#1300]
If I generate the project with Xcode 14.2 installed, it seems like the project can't find the config settings... I just updated Xcode and changed nothing to my yml-file or project

```
mint run yonaskolb/XcodeGen xcodegen
🌱 Finding latest version of XcodeGen
🌱 Running xcodegen 2.33.0...
⚙️  Generating plists...
⚙️  Generating project...
No "base" settings found
No "debug config" settings found
No "watchOS" settings found
No "iOS" settings found
```

**Comment by dungi** [comment]
Even after selecting Xcode Commandline Tools for Xcode 14.1 and running Xcode 14.1 - the same error appears.

Seems maybe like an macOS 13.2 issue? Cause I also updated this today.

**Comment by dungi** [comment]
Upate: Seems like going back to [2.32.0](https://github.com/yonaskolb/XcodeGen/releases/tag/2.32.0) works currently for me.

**Comment by dungi** [comment]
Does someone else has problems with 2.33.0?

**Comment by nishchal-v** [comment]
> Xcode 14.2 / macOS 13.0.1 / XcodeGen 2.33.0

No issues.
FYI, I have installed `XcodeGen` using brew and you are running using `Mint`, that could be a difference

**Comment by dungi** [comment]
Fixed with new version
