### ISSUE TITLE
Support Xcode Plugins

### ISSUE THREAD

**Issue by aquintiliano-encora** [yonaskolb/XcodeGen#1331]
Currently, we can get a XcodePlugin with SPM and then add it to the project
I didn't find where the plugin is added on project.pbxproj, but it would be really nice if I could add those plugins to the project using XcodeGen

I'm using these two plugins now:
- https://github.com/realm/SwiftLint.git
- https://github.com/BookBeat/SwiftGenPlugin

So I'm adding those packages with Xcodegen and manually adding them to the generated project.pbxproj

**Comment by yonaskolb** [comment]
Discussion on this is in #1290. Closing as duplicate
