### ISSUE TITLE
Xcode 14.3 Start with Rosetta Destination

### ISSUE THREAD

**Issue by avkin88** [yonaskolb/XcodeGen#1350]
After update Xcode to 14.3 version  the ability to run with Rosetta disappeared and now you need to go to the Product -> Destination -> Destination architectures -> Show Rosetta Destination
and so every time after removing  and generate .xcodeproj/.xcworkspace

**Comment by yonaskolb** [comment]
This seems to write into a `UserInterfaceState.xcuserstate` within xcuserdata which looks to be a binary file. If you aren't manually removing the project or it's workspace, XcodeGen will leave those files alone when it regenerates

**Comment by avkin88** [comment]
thank you so much, for this advice)
it works now)
