### ISSUE TITLE
`generate` command changes `objectVersion` of `.pbxproj` to an older one

### ISSUE THREAD

**Issue by KacperCzapp** [yonaskolb/XcodeGen#1362]
When running `xcodegen generate`, in `.pbxproj` file the `objectVersion` keeps being reverted to 51 (from 54 which newest Xcode sets by itself, for example when adding new files). How to fix this?

Environment:
- XcodeGen 2.35.0
- Xcode 14.3 (14E222b)

**Comment by yonaskolb** [comment]
fixed by https://github.com/yonaskolb/XcodeGen/pull/1368
