### ISSUE TITLE
Xcode 15 local swift packages support

### ISSUE THREAD

**Issue by yarneo** [yonaskolb/XcodeGen#1396]
As of Xcode 15 beta 5: "Adding a dependency to a Swift package on the filesystem (instead of a remote URL) now participates in up-front package verification, such as checking transitive dependencies for conflicting version requirements."

Also the local packages should now show where the remote package dependencies are.

Is this something xcodegen currently supports or can support?

**Comment by clausjoergensen** [comment]
You can already use `path` instead of `url` to use local Swift Packages

**Comment by yarneo** [comment]
Yes I'm aware. It doesn't support though the new Xcode 15 features for these local swift packages. You'd need to add the `XCLocalSwiftPackageReference` definition in the .proj as well as adding the local package to `packageReferences`

**Comment by giovannitrezzi** [comment]
Any news on this?

**Comment by yonaskolb** [comment]
I don't know much about this but I assume this is new support that was added to XcodeProj in the newer 8.16.0 https://github.com/tuist/XcodeProj/releases/tag/8.16.0
https://github.com/tuist/XcodeProj/pull/799

No one has picked up this work yet. Any volunteers?

**Comment by yonaskolb** [comment]
Released in 2.42.0
