### ISSUE TITLE
info.plist with settings

### ISSUE THREAD

**Issue by Simimi-dot** [yonaskolb/XcodeGen#1426]
Please tell me, is there an opportunity to take a ready-made Info.plist and change some parameters from it, or add them? Without resorting to creating a new Info.plist
I mean, to get rid of it:

```swift
info:
      path: "Info.plist"
      properties:
        CFBundleName: "BundleName"
```

**Comment by yonaskolb** [comment]
XcodeGen can't edit your existing Info.plist files. You can either:
- use a physical file and make changes there
- generate one on demand like your example above
- let Xcode generate one for you. In this way you can set build settings that relate to info plist keys using a prefix `INFOPLIST_KEY_CFBundleName: BundleName`. This is what new Xcode projects use by default nowadays

**Comment by yonaskolb** [comment]
closing this for now, feel free to ask more questions
