### ISSUE TITLE
How to make a target extension via xcodegen ?

### ISSUE THREAD

**Issue by Simimi-dot** [yonaskolb/XcodeGen#1431]
My question is as follows. How can I create an extension target through xcodegen? 
I need to create a Notification Service Extension target, but I don't quite understand how this can be done correctly through xcodegen, since when I create this target through Xcode itself, a folder with the NotificationService.swift and info.plist files for this target is automatically created. And this does not happen through xcodegen. 
Since there is no such target yet, I cannot specify a source for it.
I can separately create a folder in which info.plist and entitelements were created using xcodegen, but the NotificationService.swift file will not be created.
Does anyone know how to do this?

**Comment by tejuamirthi** [comment]
- you have to add target config for your extension as well in the project.yml used by xcodegen
- Apart from the main App target, you can create other extension targets the following way

Example: 
```
targets:
    NotificationService:
      type: app-extension
```

Please don't forget to mention `type: app-extension`. 
Refer section [Product Type from docs](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#product-type)

**Comment by yonaskolb** [comment]
Thanks @tejuamirthi, closing this for now
