### ISSUE TITLE
XcodeGenKit/resource_bundle_accessor.swift:44: Fatal error: unable to find bundle named XcodeGen_XcodeGenKit

### ISSUE THREAD

**Issue by persidskiy** [yonaskolb/XcodeGen#1445]
XcodeGen: 2.39.0
Xcode: 15.2

When I run the latest xcodegen, I see this error:

```
⚙️  Generating plists...
⚙️  Generating project...
XcodeGenKit/resource_bundle_accessor.swift:44: Fatal error: unable to find bundle named XcodeGen_XcodeGenKit
[1]    3755 trace trap  xcodegen
```

There were no such errors in version 2.38.0.

**Comment by freddi-kit** [comment]
Are you using XcodeGen from Swift Package? And what commands are you using?

**Comment by OdNairy** [comment]
@freddi-kit Here is the code we use to download xcodegen on the CircleCI:

```
        XCODEGEN_DIR="$HOME/xcodegen" && mkdir -p $XCODEGEN_DIR
        curl -L -f https://github.com/yonaskolb/XcodeGen/releases/download/2.38.0/xcodegen.zip -o "${HOME}/xcodegen.zip"
        unzip "${HOME}/xcodegen.zip" -d "${XCODEGEN_DIR}/"
        echo 'export PATH="$HOME/xcodegen/xcodegen/bin:$PATH"' >> $BASH_ENV
        source $BASH_ENV
```

**Comment by freddi-kit** [comment]
I see, I'm sorry because I'm busy so let me investigate at Sunday in Japanese Time ... 🙇🙇🙇

**Comment by freddi-kit** [comment]
Or you can my PR to how to fix it, please check my pr what I changed

**Comment by freddi-kit** [comment]
It's #1388. My change wrong on loading Bundle loading

**Comment by daltonclaybrook** [comment]
I am experiencing this issue as well. Installing XcodeGen on CI using `mint install yonaskolb/xcodegen`

**Comment by kkk669** [comment]
@daltonclaybrook What version of Mint are you using? I'm using Mint 0.17.5 and have no issues. Mint versions older than 0.17.2 do not copy bundles.

https://github.com/yonaskolb/Mint/releases

**Comment by daltonclaybrook** [comment]
I'm using 0.17.5 as well. Installing mint on CI with `brew install mint`

**Comment by kkk669** [comment]
I don't know why that issue didn't occur on my side, but your issue may be related to the following issue.

https://github.com/yonaskolb/Mint/issues/261

**Comment by yonaskolb** [comment]
Can anyone having issues confirm that 2.39.1 fixes the issue?

**Comment by freddi-kit** [comment]
@yonaskolb it looks binary[xcodegen.artifactbundle.zip](https://github.com/yonaskolb/XcodeGen/releases/download/2.39.1/xcodegen.artifactbundle.zip) is still 2.39.0 in https://github.com/yonaskolb/XcodeGen/releases/tag/2.39.1

**Comment by freddi-kit** [comment]
sorry, please ignore above my comment

**Comment by freddi-kit** [comment]
It looks fixed from my sight with released binary in https://github.com/yonaskolb/XcodeGen/releases/tag/2.39.1

**Comment by persidskiy** [comment]
The fix works, thank you all!
