### ISSUE TITLE
Where should I set the App version?

### ISSUE THREAD

**Issue by rex-structorum** [yonaskolb/XcodeGen#1455]
The Project schema specification docs lists some `Info.plist` properties that are automatically generated: [ProjectSpec.md#target](https://github.com/yonaskolb/XcodeGen/blob/2a367acb0f7928bc42210cbcdd31dcd778831c6b/Docs/ProjectSpec.md#target)

Am I missing where `CFBundleVersion` and `CFBundleShortVersionString` are derived from in the spec, or are these always `1` and `1.0` unless overridden here?

**Comment by yonaskolb** [comment]
There are various Xcode settings that interlink but I think what you're looking for is the build setting `MARKETING_VERSION` which you can set in the target or just across the entire project

**Comment by yonaskolb** [comment]
Let me know if that helps, closing this for now
