### ISSUE TITLE
Prefetch resource tags (ODR, On Demand Resources)

### ISSUE THREAD

**Issue by pafdad** [yonaskolb/XcodeGen#1469]
Hello and thank you for XcodeGen

Is there any support for prefetched tags in XcodeGen? The docs for prefetched tags [are here](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/Tagging.html#//apple_ref/doc/uid/TP40015083-CH3-SW2).

I could only find `resourceTags` in the documentation for XcodeGen but no mention of how to fine tune the fetching for the 3 available categories:

1. Initial Install Tags
2. Prefetched Tag Order
3. Download Only on Demand

Thank you

**Comment by pafdad** [comment]
I think I found it under `ON_DEMAND_RESOURCES_PREFETCH_ORDER` actually. Thank you

**Comment by fedorinovdmitry** [comment]
@pafdad  I still couldn't figure out how to move my tag to `Initial Install Tags` category. By default it was created in the `Download Only on Demand` category. Could you help me with this, please?
