### ISSUE TITLE
Build is broken on Xcode 16 Beta 1 due to GraphViz

### ISSUE THREAD

**Issue by giginet** [yonaskolb/XcodeGen#1483]
Currently, XcodeGen can't build with Xcode 16 Beta 1.

```
/Users/giginet/Library/Developer/Xcode/DerivedData/XcodeGen-ccjxvauqmliuzaaqjslkfzkifxrg/SourcePackages/checkouts/GraphViz/Sources/GraphViz/Edge.swift:6:27 'ID' is only available in macOS 10.15 or newer
```

The following errors were caused by [GraphViz](https://github.com/SwiftDocOrg/GraphViz). However it is no longer maintained and has already become a public archive.

This dependency is only used in the `dump` command, so we can easily drop the feature. Therefore, I think it's better to remove this dependency for future maintainability. How do you think?

By the way, I guess this error is caused by a compiler bug. Therefore, it may be resolved by Swift 6 release.

**Comment by yonaskolb** [comment]
@giginet can you create a PR for this please? You can point to this issue as well https://github.com/yonaskolb/XcodeGen/issues/1462

**Comment by giginet** [comment]
Sure, I'll open the PR soon.
