### ISSUE TITLE
Support installation with Homebrew

### ISSUE THREAD

**Issue by pepibumur** [yonaskolb/XcodeGen#15]
Installation can be simplified by using Homebrew. The purpose of this issue is to provide a Homebrew formula that tells Homebrew how to install XcodeGen

**Comment by yonaskolb** [comment]
I would love that! I remember hearing you're not allowed to submit formula's for your own project, so if you could to it, that would be great!

**Comment by pepibumur** [comment]
You can add your own repository, called Tap where the definition is. I'm working on the formula but I'm facing some issues with the generated binaries, since it depends on other frameworks that have to be linked once moved to the system directory.

**Comment by pepibumur** [comment]
Forget about that, it's exactly what you do here :trollface: https://github.com/yonaskolb/XcodeGen/blob/master/Makefile

Where did you find documentation about that? I always wondered how that can be done.

**Comment by yonaskolb** [comment]
Yeah one of the guys from YAMS pointed me in the right direction 
https://github.com/jpsim/Yams/issues/39
I've been meaning to write a blog post about it, but I think it's supposed to be a solved problem when Swift 4 comes out

**Comment by pepibumur** [comment]
I see. I wonder why it only happens with that dependency and not with the other. I feel I'm missing something :/

**Comment by yonaskolb** [comment]
It's because Yams relies on a C module - libCYaml.dylib

**Comment by pepibumur** [comment]
This has already been done:
```bash
brew tap yonaskolb/XcodeGen git@github.com:yonaskolb/XcodeGen.git
brew install xcodegen
```
