### ISSUE TITLE
App from new project is in rectangle instead of taking full screen

### ISSUE THREAD

**Issue by michaello** [yonaskolb/XcodeGen#1503]
I use basic template and it's put in much smaller frame. How can I undo that?

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/e35fc50e-988c-47e3-9901-13df0f5ae558">

**Comment by bpisano** [comment]
This is related to [this issue](https://stackoverflow.com/questions/75262066/ios-app-not-using-full-height-of-the-screen). Make sure to add an empty image as a launch screen to your `Info.plist` file as suggested [here](https://stackoverflow.com/a/78250740/7133236).
```xml
<key>UILaunchScreen</key>
<dict>
    <key>UIImageName</key>
    <string></string>
</dict>
```

**Comment by yonaskolb** [comment]
Thanks @bpisano. Similar info here https://github.com/yonaskolb/XcodeGen/issues/1458
