### ISSUE TITLE
Adding files: the default target is not selected

### ISSUE THREAD

**Issue by jerrymarino** [yonaskolb/XcodeGen#159]
When I add a new file in in an XcodeGen created project, the files are added to the first target in the list. 

If I hand create Xcode project, by default, file are automatically added to the right target.

This is a pain point for users when there is 60 targets in the project.

Is there a way to fix this issue? I think there is a mapping that Xcode creates with a given directory to targets.. Perhaps we could do the same thing?

**Comment by yonaskolb** [comment]
I just tested this on one of my own generated projects. It seems to preselect the right target whenever I right click on a certain target's group and create a new file, except if that group contains sources from multiple targets (multi-platform targets). Are you seeing otherwise? 

I don't use `createIntermediateGroups` though. Maybe that has something to do with it

**Comment by jerrymarino** [comment]
@yonaskolb thanks so much for testing this out man - much appreciated!

It looks like Xcode associates targets based on the name of the folder.

After some debugging and testing of Xcode, here is what the logic seems to be:

```
func getTarget(relativePath)
	if allTargets contains relativePath[0]
		return allTargets valueForKey relativePath[0]
	return allTargets.first
```

This seems to match up with fact that Xcode creates a folder with the name of the target at the project root.

I don't know if is anything that could be set in an Xcode project to fix this. The only solution I can think of would be to rearrange some of the sources for targets.

**Comment by yonaskolb** [comment]
I see. I guess most people would have their sources in a folder that is named after the target. If not I guess #162 would be a good fix

**Comment by jerrymarino** [comment]
@yonaskolb if there was a way to fix this with an Xcode project change that would be amazing.

What it looks like is Xcode is searching for a target based on the `file path` and not the group. For example, given the project:
```
Targets:
    Application
        type: App
        deps: ChildLib
    ChildLib
       type: StaticLib
```

If you have the source tree:
```
   App.xcodeproj
   Application/
   CoreLib/
```
Everything works as expected.

Now, if you have a source tree, where `ChildLib` is a child of `Application/`.
```
   App.xcodeproj
   Application/
        CoreLib/
```
The default target for any files add to `CoreLib/` seems to always be `Application`. I tried various combinations of group types, which proved futile.

If I put an Xcode project at `Application/CoreLib.xcodeproj` then it will work. Once we have multiple Xcode projects up and running, I can create a few Xcode projects and it will be 💯 

<img width="274" alt="nestedxcodetargetswork" src="https://user-images.githubusercontent.com/1245820/33144887-6fb7201e-cf73-11e7-995c-b372ece84737.png">

Adding files to `Application/CoreLib` through the `CoreLib.xcodeproj` is working good ( `CoreLib` is the default target! )


[ChildTargetAddingFileTest.zip](https://github.com/yonaskolb/XcodeGen/files/1497206/ChildTargetAddingFileTest.zip)
