### ISSUE TITLE
Link & Embed implicit dependencies

### ISSUE THREAD

**Issue by sbarow** [yonaskolb/XcodeGen#163]
I have multiple `.xcodeproj` generated using `XcodeGen` which are then added to a work space.

Say we have the structure:
- App (depends on UI & Foundation)
- UI (depends on Foundation)
- Foundation (no dependencies)

With there respective `project.yml` files being defined like this:
```
## App/project.yml
...
dependencies:
	- framework: UI.framework 
	- framework: Foundation.framework
...

## UI/project.yml
...
dependencies:
	- framework: Foundation.framework
...
```

This will compile and launch correctly on simulators because the build option for implicit dependencies is checked, however this will crash on launch when running on device because the implicit frameworks are not being copied to the apps frameworks folder.

Example of embedded framework in project:

![screen shot 2017-11-20 at 10 18 59 pm](https://user-images.githubusercontent.com/867796/33042490-59b39fe0-ce42-11e7-99d0-351fc21397bd.png)

- `UI.framework` is embedded correctly - by manually selecting the framework which is being built by the UI project and placed in the `$(BUILT_PRODUCTS_DIR` (note the `... in Build/Debug-iphoneos`)
- `Foundation.framework` is the added dependency  which will cause a crash because its not copied into the app frameworks folder.

Is there a way to specify that the framework being linked is in the `$(BUILT_PRODUCTS_DIR`?

**Comment by yonaskolb** [comment]
Hi @sbarow 
There's currently no way to achieve this in the spec that I know of. I guess this goes back to the question of generating the whole workspace as per #24. I want to open up a proper discussion about that soon.

Does anyone have an idea of a workaround in the meantime?

**Comment by rahul-malik** [comment]
@sbarow - Can you just add `$(BUILT_PRODUCTS_DIR)` to `FRAMEWORK_SEARCH_PATHS` via an xcconfig file / config setting?

**Comment by sbarow** [comment]
I have a script that can do the workspace generation pretty easily depending on the folder structure & `project.yml` files and its dependencies but needs this to be work before I can make it public.

Could we create a new `Dependency` type which would create a `PBXFileReference` with `sourceTree: .buildProductsDir`? Not sure how involved this would be and if its a road I want to go down?

**Comment by sbarow** [comment]
@rahul-malik that doesn't seem to work, the build still fails saying it can't find the frameworks.

**Comment by yonaskolb** [comment]
@sbarow adding something like that to `Dependency` is definitely doable, if you'd like to submit a PR for it.
