### ISSUE TITLE
Target Scheme codeCoverageEnabled = "YES"

### ISSUE THREAD

**Issue by alexruperez** [yonaskolb/XcodeGen#169]
Hi @yonaskolb! 😃
How can we set true the "Code Coverage" flag to gather coverage data?

![Coverage](https://raw.githubusercontent.com/intelygenz/Archit-iOS/master/Resources/gather_coverage_data.png)

Thanks!

**Comment by alexruperez** [comment]
The first step should be @pepibumur or any reviewer with write access approves this https://github.com/xcodeswift/xcproj/pull/166

And later add something here, right? https://github.com/yonaskolb/XcodeGen/blob/0c1325cc5fd6fdc190e250d6a8786ce6bff1a2e1/Sources/XcodeGenKit/ProjectGenerator.swift#L66

**Comment by pepibumur** [comment]
The PR has been merged @alexruperez. @yonaskolb can give you better feedback about how to support it from the XcodeGen project specification file.

**Comment by alexruperez** [comment]
Thanks @pepibumur! 🙌

**Comment by yonaskolb** [comment]
Hi @alexruperez! Thanks for helping out!

Currently there are 2 methods for creating shared schemes. 
There is a small convenience api on `Target` called `scheme: TargetScheme`. This generates a scheme for that single target, and only allows you to add some test targets and config variants (config variants allow you to specify for example `[test, staging, production]` and it would use debug or release variants for the different build types.

There is another way to define totally custom schemes, under `schemes: [Scheme]`, but it is currently undocumented as it's incomplete and the api may change. At the moment you can only choose which targets to build for which build types, and which configuration each build type will use. 

I think the best place to add code coverage would be `Scheme.Test`, but you could also add it to `TargetScheme` for those simple cases.

I hope that all makes sense!

**Comment by alexruperez** [comment]
Thanks @yonaskolb, I've tried to do it in https://github.com/yonaskolb/XcodeGen/pull/170 as you explained, it works perfectly for me. 😃
