### ISSUE TITLE
Create breakpoints

### ISSUE THREAD

**Issue by alexruperez** [yonaskolb/XcodeGen#173]
@yonaskolb is there any way to [create breakpoints](https://github.com/intelygenz/Archit-iOS/tree/feature/XcodeGen#-project-configuration)? (Exception, symbolic...)

What would be necessary for it?

@pepibumur should we add this functionality to [xcproj](https://github.com/xcodeswift/xcproj) first?

Thanks! 🍻

**Comment by pepibumur** [comment]
Yes @alexruperez you can extend xcproj to support breakpoints 😛

**Comment by yonaskolb** [comment]
Yeah, I guess it could be useful for some people. Though simply committing either the shared breakpoints, or having user breakpoints might be a good solution as well. Are there other use cases where this would be useful?

**Comment by alexruperez** [comment]
I thought about shared breakpoints not committed in the repo (ignored by Git), I'm working on it, as I find problems/doubts, we can discuss them in the pull request, agree? 😃

**Comment by yonaskolb** [comment]
👍
