### ISSUE TITLE
Update current Xcode version

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#179]
Currently the Xcode version is 0900 where as the latest Xcode should be 0910.

Question is whether this should be supported with as an option or should we continue using the hard coded version.

**Comment by yonaskolb** [comment]
Yeah this could be updated. Does that fix any practical issues?
We could add an option as well

**Comment by peymankh** [comment]
It's really just to avoid Xcode warnings to `Update Project Settings`. 

OK I'll add this as an option with `0910` as default.

**Comment by rahul-malik** [comment]
@peymankh @yonaskolb - Would it make sense to infer this based on the currently selected path for the Xcode toolchain? The advantage there is that you won't have to update this every time there is an update

**Comment by yonaskolb** [comment]
@rahul-malik that’s a good idea. Though sometimes a new Xcode may have breaking changes that have we to accomodate, so we can’t automatically support all future versions. So it might be good to still manually update to newer versions as the fallback

**Comment by peymankh** [comment]
@rahul-malik I think I have to agree with @yonaskolb on this.
