### ISSUE TITLE
Support for recursive Source excludes

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#180]
Currently Source excludes are implemented with using glob patterns.

#### Examples

- `ios/*.swift`: all files with full path that ends with .swift
- `ios/configs`: all files and directories under ios/configs
- `README.md`: the README.md file in the root directory of your repository (doesn’t match ios/README.md)
- `ios/*.[mh]`: files with the extension .m or .h only under the ios directory (but not its subdirectories)
- `configs/server[0-2].json`: the files server0.json, server1.json, server2.json in the directory configs/

Aim is to add a more robust excludes support using `**`. 

#### Examples

- `ios/**`: all files with full path that starts with ios/ (i.e. any files in the ios directory)
- `**/README.md`: the README.md file in all directories (including README.md in root directory of your repository)
- `ios/**/*.[mh]`: all files with the extension .m or .h, in the ios directory and all of its subdirectories

[Examples Disclaimer](https://docs.buddybuild.com/builds/selective_builds.html#examples)

**Comment by faken** [comment]
+1

**Comment by keehun** [comment]
Are there any plans for supporting the `**` rule?
