### ISSUE TITLE
Script Double Quote Escaping

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#181]
Reference to issue #41 and fixed in swift-xcode/xcodeproj#59.

Seems to me this is currently being overdone.

For example `cp $FILE "$DEST/file"` should not be escaped because it will cause cp to fail.

@yonaskolb thoughts?

**Comment by yonaskolb** [comment]
@allu22 do you have any thoughts on this? https://github.com/xcodeswift/xcproj/pull/159 may have affected this as well
