### ISSUE TITLE
Add support for different command line arguments for different scheme action

### ISSUE THREAD

**Issue by vhbit** [yonaskolb/XcodeGen#188]
It's a suggestion to improve what started in #172 - while profile & launch actions usually don't differ much, test action quite often has its own set of command line arguments.

**Comment by rahul-malik** [comment]
I thought about doing this originally but was unsure what the appropriate schema change would be to enable it. We have support in xcproj to vary the arguments by them type so it's just updating the schema

**Comment by yonaskolb** [comment]
@vhbit do you mean `target.scheme`? That is a simpler version of a full scheme spec, and is designed for simple cases. If you want to have more control over build actions then use `spec.schemes`. If you specify a scheme there you can have different command line arguments for each build action type

**Comment by vhbit** [comment]
@yonaskolb I feel I'm missing something, there is no mention of `spec.schemes` in docs.

**Comment by yonaskolb** [comment]
Yes, sorry you are right. It wasn’t added as it was still a work on progress. I’ll add some documentation.

In the meantime you can look at Scheme.swift to see what it supports

**Comment by vhbit** [comment]
@yonaskolb sorry for a delay. Yep, `spec.schemes` has everything needed. The only thing stopping it from adoption is unrelated issue - it doesn't generate `Testables` so Xcode thinks that target is not testable. I've opened #193 to keep it separated.
