### ISSUE TITLE
Add options for indentWidth and tabWidth

### ISSUE THREAD

**Issue by bkase** [yonaskolb/XcodeGen#189]
Hi!

If https://github.com/xcodeswift/xcproj/pull/183 lands, xcproj will be able to support encoding the indentWidth and tabWidth directly inside a PBXGroup. This overrides the default settings that a user has specified in Xcode (so it's a way to enforce code consistency in a project).

I think it would be great for XcodeGen to support this, but I'm not sure the best way to introduce it into the ProjectSpec. I feel like we don't need per-group settings (but maybe we should support that?). There should definitely be some sort of setting that can apply to the `topLevelGroup`. I tested this by hardcoding the `indentWidth` and `tabWidth` and those fields do cascade, so setting them on the `topLevelGroup` sets them for the entire project.

The top-level settings right now directly map to Xcconfigs, though, is the right place for this in `options`?

cc @yonaskolb

**Comment by bkase** [comment]
It seems like `options` would be the right place for this. What do you think?

**Comment by yonaskolb** [comment]
Yeah, options is good 👍
