### ISSUE TITLE
Generate from Swift PM Package

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#196]
This would allow SwiftPM to be used as a dependency manager, but allow XcodeGen to generate the project. This means you can use your own build settings, and also allows for iOS development via Swift PM

**Comment by pepibumur** [comment]
This is a great idea! Would you then parse the `Package.swift` and figure out how the Xcode projects for the dependencies should be? @yonaskolb

**Comment by yonaskolb** [comment]
I think there are a few options:

1. specify swiftPM dependency type, and then link dependencies from:
    - an existing `Package.swift`
    - a `Package.swift` we generate
2. generate directly from an existing Package.swift file and provide some command line options
3. add some sort of package option in the project spec which then generates the target specs from that, and lets you override settings
4. create a new sort of spec file that provides overrides (mostly build settings) for an existing `Package.swift` file
5. probably some other solutions I haven't thought of

**Comment by yonaskolb** [comment]
It's basically a question of where the source of truth should be. Considering that Swift PM is the future, I would say there. Hopefully Swift PM finally gets to a point that it can remove the need for XcodeGen, thought it might a few years away for it to support everything we do.

**Comment by LinusU** [comment]
This would be amazing 😍 

There is currently a way to use SPM to handle dependencies for iOS app. Basically you set up a subproject that builds all the deps, and then embed that project in the main project. Here is a tutorial: http://www.ralfebert.de/ios-examples/xcode/ios-dependency-management-with-swift-package-manager/

It would be amazing if this project could use `Package.swift` as the source of truth, and then generate a project that is ready to use the dependencies.

Is there anything that I would be able to help with to move this forward?

**Comment by LinusU** [comment]
The swift package manager is able to generate an Xcode project that builds `.framework` files from each dependency. It seems to add all of the source files in a "Dependencies" group ([relevant code](https://github.com/apple/swift-package-manager/blob/922d2f9b46a30f605b3bb6bf4a6ca9cce0fc30c9/Sources/Xcodeproj/pbxproj().swift#L327-L359)), and then create products for each framework ([relevant code](https://github.com/apple/swift-package-manager/blob/922d2f9b46a30f605b3bb6bf4a6ca9cce0fc30c9/Sources/Xcodeproj/pbxproj().swift#L379-L409)).

Would it be within the scope of this package to do something similar? Effectively allowing SwiftPM to be used for managing dependencies for an iOS app.

**Comment by danramteke** [comment]
Hello. Any updates on this? This would be pretty sweet. 

My use case is: I have a server written in swift and an iOS app in the App Store. And the two share some code. 

Currently, I have a local cocoapods podspec that points to several directories in my server code. But that doesn’t feel elegant.

**Comment by moppymopperson** [comment]
I'd really like to see this happen to. I'm interested in being able to generate a new iOS project from the command line.

**Comment by yonaskolb** [comment]
I feel this is adequately solved by https://github.com/yonaskolb/XcodeGen/pull/624
