### ISSUE TITLE
Cross platform frameworks

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#2]
This is by specifying multiple platforms for a target in the spec, which would generate multiple targets, each with a different platform

**Comment by robertjpayne** [comment]
Just to add a comment on this -- you can actually generate a cross platform framework w/o duplicating it.

http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by yonaskolb** [comment]
Thanks for the info @robertjpayne. As the article mentions that are some issues with such an approach. If we're generating these targets automatically anyway, we may as well do it in a recommend and supported way.
This has now been added in #35
