### ISSUE TITLE
R.swift can't parse generated *.xcodeproj

### ISSUE THREAD

**Issue by gin0606** [yonaskolb/XcodeGen#208]
Hi!
I need help.

I try to use XcodeGen with R.swift.
But R.swift show error ;(

```
[R.swift] Project file at 'file:///path/to/RswiftWithXcodeGen.xcodeproj/' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?
```

I made the smallest project to see errors.

https://github.com/gin0606/xcodegen-v1.4.0-trouble

Thanks!

**Comment by yonaskolb** [comment]
Hi @gin0606. The problem seems to be that `XcodeEdit` (which R.swift uses to read xcode project files) was being a bit too strict. 
We now generate that the required property in #23, as Xcode automatically generates it when you open the project anyway

**Comment by gin0606** [comment]
Problem solved!
Thanks a lot!!
