### ISSUE TITLE
Update to xcproj 2.0 or later

### ISSUE THREAD

**Issue by kastiglione** [yonaskolb/XcodeGen#223]
Are there plans to upgrade to xcproj 2.0? Are there any known issues/blockers? I want to add XcodeGen support for scheme pre- and post- actions, which will depend on xcodeswift/xcproj#217, which will presumably be in a 2.x.y release.

**Comment by yonaskolb** [comment]
There is actually a PR in progress for this #191 
@pepibumur will you be continuing to work on that, or should someone else take that over?

**Comment by kastiglione** [comment]
Oops, I searched in issues but not pull requests.

**Comment by pepibumur** [comment]
I don't have much time these days to work on it. Feel free to take it over @kastiglione if you want to 😛

**Comment by kastiglione** [comment]
@pepibumur I will have a look. Do you have time to answer questions if I have some?

**Comment by pepibumur** [comment]
Yes! definitively

**Comment by keith** [comment]
Should update to 3.x now https://github.com/xcodeswift/xcproj/releases/tag/3.0.0

**Comment by yonaskolb** [comment]
I've having a look at this now 👍

**Comment by jerrymarino** [comment]
👍 pre/post scheme actions would be super useful for me!

**Comment by jerrymarino** [comment]
Awesome - looking forward to it @kastiglione

**Comment by yonaskolb** [comment]
I currently have a xcproj 3.0 branch ongoing that isn’t published. I can get it done later today

**Comment by yonaskolb** [comment]
Actually, it depends on changes that require an xcproj 4.0 with this PR included https://github.com/xcodeswift/xcproj/pull/218

**Comment by pepibumur** [comment]
@yonaskolb is it ok if we release after your last two PRs are merged?

**Comment by yonaskolb** [comment]
Yeah, unless there’s anything else breaking we want to get in
