### ISSUE TITLE
Use xcodegen *and* be a carthage dependency

### ISSUE THREAD

**Issue by codeOfRobin** [yonaskolb/XcodeGen#226]
Hey!

If a project uses xcodegen (and consequently - doesn't commit the `.xcodeproj` file to the git repo), it can't be used in carthage as a dependency, right?

I think carthage always depends on the project files being present so it can compile targets into frameworks. 

Is there a good way to do both, i.e. not commit a project to the repo AND be carthage compatible?

**Comment by yonaskolb** [comment]
That is true, you need a checked in project to be Carthage compatible. But it doesn’t mean you can’t still use XcodeGen to configure the project

**Comment by codeOfRobin** [comment]
Ah gotcha! Thanks!

**Comment by yonaskolb** [comment]
Remember that even if you check in your project, xcodegen still helps you get around conflicts by simply regenerating

**Comment by codeOfRobin** [comment]
Oh right. That is AMAZING. Thank you so much for making xcodegen 🙏
