### ISSUE TITLE
Support scheme actions

### ISSUE THREAD

**Issue by kastiglione** [yonaskolb/XcodeGen#228]
I've started working on adding support for scheme pre-actions and post-actions and have some questions.

Has anyone already given this some thought? The [spec](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md)'s current design steers toward adding pre/post actions to [schemes](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#scheme). This is because actions can be added before and after each of the distinct action types: build/run/test/etc. These action types currently only exist within the scheme structure.

Relatedly, I've noticed an issue with how schemes are defined. Currently, schemes that are defined by the top level [`scheme`](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#scheme) property are superseded by schemes that come from the [`targets`](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target) property. If this is expected behavior, I think a warning or error should be added. I'm thinking that it would be good to merge the two sources of scheme data into one? Does this seem reasonable, or are there reasons they can't be merged?

See also xcodeswift/xcproj#217.

**Comment by yonaskolb** [comment]
Currently `target.scheme` is just a convenience api which makes adding simple schemes easy, as you don't have to worry about names or targets.
The top level `schemes` is where you can add more complex schemes. Issue #215 contains a similar discussion.

**Comment by yonaskolb** [comment]
For scheme actions, I would say we add them to the `Scheme`, but could possibly also add them to `TargetScheme` which would just add them to every supported action, which again is about convenience.
