### ISSUE TITLE
Include standalone XcodeGen binaries in releases

### ISSUE THREAD

**Issue by kastiglione** [yonaskolb/XcodeGen#234]
Has there been any interest in making a binary available with each release? The way we manage versioning and updates of XcodeGen is by creating a release in our fork that includes a binary. If others want this too, maybe it's worth adding binaries to the official releases.

**Comment by yonaskolb** [comment]
No one has asked about yet. One thing is that the `settingPresets` also need to live in the same directory, which mint and homebrew setup correctly.

It's possible to bundle everything up into a zip. I'd want to do this automatically though via the makefile. If you'd like to write a script to talk to github that's great!

**Comment by rahul-malik** [comment]
We're using XCodeGen as a framework so this doesn't benefit us but just wanted to support this since we're thinking of having precompiled binaries for all our dependencies so it's easy to upgrade team members by avoiding compilation on everyones machine.

**Comment by toshi0383** [comment]
I guess this would help resolving the issue?
https://github.com/yonaskolb/Mint/pull/52

We can put this in Makefile as part of release process,
```
mint archive xcodegen
```
then in your project you can install like this.
```
PREFIX=mint/XcodeGen mint install yonaskolb/XcodeGen --binary
```
Giving the `$PREFIX` results the binary installed at `$PWD/mint/XcodeGen/bin/xcodegen`.

**Comment by toshi0383** [comment]
> I'd want to do this automatically though via the makefile. If you'd like to write a script to talk to github that's great!

@yonaskolb 
In my experience, [GitHub release API is not straight forward to use](https://github.com/fastlane/fastlane/issues/575#issuecomment-139307075), so I would just upload the generated zip file manually to the release page.
It was a while ago, so you can of-course try.😉

**Comment by keith** [comment]
I think ideally we would include the settings presents files as strings in the code, so a standalone binary would be feasible. We’re actually using a standalone binary we build currently and just exclude those files since we don’t use them.

**Comment by toshi0383** [comment]
@keith 
> we would include the settings presents files as strings in the code

In which code you talking about?👀

If I understood you correctly, would that be `.mint.yml` or something like that?
https://github.com/yonaskolb/Mint/issues/2

**Comment by keith** [comment]
No I just mean that ideally XcodeGen could be entirely standalone without any supporting yams files. Those could be strings in the code

**Comment by toshi0383** [comment]
Ah I see. So ideally we don’t need project.yml, xcconfigs, and all that kind of configuration files.🤔

**Comment by yonaskolb** [comment]
@toshi0383, @keith means the setting preset yaml files here: https://github.com/yonaskolb/XcodeGen/tree/master/SettingPresets

There is a usefulness to keeping them as external files:
- if they are copied to the project root they can be modified by a project (even just piecemeal files will override the official ones)
- they are optional, so don't need to specifically live in binary
- are more easily maintained in external yaml files

**Comment by toshi0383** [comment]
By the way today I started to use XcodeGen on CI and XcodeGen's install takes more than 2 minutes on Bitrise. I want to make it less than 10 seconds by resolving this issue. 👍

**Comment by toshi0383** [comment]
> Agree. Maybe we can use Mint's Package.resources feature to distribute them, if we keep them as separated yaml files.

Just recognized that then I would have to install `mint` to use `Package.resources`, so it might not resolve installing time..🙄
I guess we need to use standalone install script like this for CI.
https://github.com/toshi0383/scripts/tree/master/swiftpm

**Comment by toshi0383** [comment]
I've submitted a PR to resolve this issue. https://github.com/yonaskolb/XcodeGen/pull/246
For now we have `SettingPresets`, so embedded `install.sh` is the solution.👌

I'm already doing this on Bitrise using my fork.
https://github.com/toshi0383/XcodeGen/releases/tag/1.6.1

**Comment by yonaskolb** [comment]
As a note, I used Mint on a project to run xcodegen on Bitrise as well this week. I just added `/usr/local/lib/mint‘ to the cache pull and cache push steps 👍

**Comment by toshi0383** [comment]
🎉
