### ISSUE TITLE
Atomic writing?

### ISSUE THREAD

**Issue by jerrymarino** [yonaskolb/XcodeGen#235]
Is it possible to make XcodeGen support atomic writes? I noticed that if the program is killed, it can end up in a weird state ( i.e. schemes may not be written but the project was ).

I'd like to write the project to a temporary file path, and then copy it over once writes are fully complete. I noticed this is non trivial due to validation in XcodeGen, which seems to check paths relative to the output directory.

Here is how I'm working around this:
- Give XcodeGen a path adjacent to the project I want to write
- Let that project be written
- On success, move that to the actual path

**Comment by yonaskolb** [comment]
Yeah should be possible to write to a temporary file and then copy over. 
It would have to be a smart copy though that doesn’t remove people’s private data, but still overwrites some directories like shared schemes

**Comment by yonaskolb** [comment]
That would mean XcodeGen would need to be knowledgeable about the project structure on the filesytem which isn’t great.
Just though of a better way. Copy the existing project to a temporary directory, then overwrite with generated project, and then copy back

**Comment by jerrymarino** [comment]
@yonaskolb thats a really good point. We'd need to merge any user created directories into the new project. I like your idea of just copying over and overwriting the old project - this is super clean. 👍

**Comment by yonaskolb** [comment]
Done here #250
