### ISSUE TITLE
Add support for Scheme action enviroment variables

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#236]
This would allow for setting environment variables in schemes. 

My main motivation for this is being able to set `OS_ACTIVITY_MODE` to `disable`, to remove Xcode's garbage logging in the console 😄 

![screen shot 2018-02-07 at 5 10 56 pm](https://user-images.githubusercontent.com/2393781/35901286-014aba16-0c2a-11e8-94cf-0e0443bb1440.png)

**Comment by turekj** [comment]
@yonaskolb this is super useful for snapshot testing, too! See: [iOSSnapshotTestCase](https://github.com/uber/ios-snapshot-test-case)
