### ISSUE TITLE
Setting MACOSX_DEPLOYMENT_TARGET to 10.10 results in 10.1

### ISSUE THREAD

**Issue by olbrichj** [yonaskolb/XcodeGen#240]
It seems like setting MACOSX_DEPLOYMENT_TARGET to 10.10 is parsed at 10.1. On the other hand 10.11 works fine.

#Expected Result
Setting MACOSX_DEPLOYMENT_TARGET to 10.10, sets the correct deployment target version in the generated Xcode project.

See this issue for context:  
https://github.com/xcodeswift/xcproj/issues/228

**Comment by yonaskolb** [comment]
This is due to a plain value of `10.10` is parsed as a double which is then written as a string `10.1`.
To get this to work you must specify a string `"10.10"`

**Comment by yonaskolb** [comment]
I've updated the `deploymentTarget` docs to show string examples so this issue is minimised https://github.com/yonaskolb/XcodeGen/commit/3ee14fd0bf640c628b2bd47c9fddd977d4849e22

**Comment by olbrichj** [comment]
thanks!

**Comment by yonaskolb** [comment]
Looks like this issue is back in a newer version of Yams. New issue here  #268
