### ISSUE TITLE
xcdatamodeld support

### ISSUE THREAD

**Issue by ralfebert** [yonaskolb/XcodeGen#243]
When a project with a Core Data model (.xcdatamodeld) is generated, the file is added as a resource and the data model is not editable in Xcode.
I generated an example project via File - new Single View Application project - with option 'use Core Data'.
I then re-generated the project via xcodegen, and fixed the project by removing and adding the data model manually. This is the resoluting change: https://github.com/ralfebert/xcodegen-coredataexample/commit/7c1664772b74e753c77e5cf1aa4ccf6be6215b43
Xcode seems to generate a special `XCVersionGroup` for these models.
Any chance to get these generated via xcodegen?

**Comment by yonaskolb** [comment]
Yep good catch, this should be possible. An easy change will be changing the default build phase to source instead of resource. I’ll look into whether the version group is necessary, but we can do that too

**Comment by yonaskolb** [comment]
Fixed with #249. It'll be in the next release 👍
