### ISSUE TITLE
Setup repository labels

### ISSUE THREAD

**Issue by pepibumur** [yonaskolb/XcodeGen#26]
I find it useful to include priority, difficulty and type useful to organize issues. It's also good for welcoming contributors in the project *(e.g. they can start with the simple issues to get some context on the project)*.

This is the setup that I've used for xcodeproj, what do you think @yonaskolb?

![image](https://user-images.githubusercontent.com/663605/29562012-f3a41a1e-8737-11e7-930e-7e32d990c48b.png)

**Comment by yonaskolb** [comment]
Personally I think it's a bit overkill for such a small project, but I have no problem with it. Sure, you can add them 😀

**Comment by pepibumur** [comment]
Done 😛
