### ISSUE TITLE
Option to create groups for empty directories

### ISSUE THREAD

**Issue by abeintopalo** [yonaskolb/XcodeGen#278]
Hi,

First, thank you for this great tool. It is really awesome. :)

I'm trying to use this tool to generate a template Xcode project that has already a group structure setup regardless if the source directories contain source files or not.

Currently it seems that XcodeGen ignores directories that don't contain any source file.

Is there any way (option) to instruct XcodeGen to mirror the source directory structure as group structure in the generated Xcode project even if the source directories are empty? (I don't want to use _folder_ type)

This feature would be useful when creating starter projects where the group structure is already agreed within a team before any source code is created for all groups.

**Comment by yonaskolb** [comment]
Hi @abeintopalo
At the moment no there isn't a way to tell XcodeGen to change this behaviour. It could potentially be added as an option though

**Comment by yonaskolb** [comment]
This was added in 2.2.0
