### ISSUE TITLE
Add an option 'Run script only when installing'

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#28]
I often use auto-increment build number script and some scripts that should invoked only when archiving.

_Examples:_
http://crunchybagel.com/auto-incrementing-build-numbers-in-xcode/
https://gist.github.com/sekati/3172554
https://github.com/realm/realm-cocoa/blob/master/scripts/strip-frameworks.sh

Those kind of scripts should run only when archiving (well, just personally I guess so). So I believe 'Run script only when installing' option would be nice...

**Comment by yonaskolb** [comment]
This requires support from xcodeproj

**Comment by yonaskolb** [comment]
Fixed in xcodeproj https://github.com/carambalabs/xcodeproj/pull/49

**Comment by yonaskolb** [comment]
Resolved with workaround in the meantime. Will be in the next release soon

**Comment by pepibumur** [comment]
We'll have a release tonight so that you can use it @yonaskolb

**Comment by yonaskolb** [comment]
@ImLaufderZeit This is now in [0.4.0](https://github.com/yonaskolb/XcodeGen/blob/master/CHANGELOG.md#040)
