### ISSUE TITLE
Generate output files for carthage copy frameworks script

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#29]
This will make the  Carthage `copy-frameworks` script run only if the output files are missing. As suggested in the Carthage readme

**Comment by toshi0383** [comment]
>  As suggested in the Carthage readme

I couldn't find this. Could you tell me which section?

**Comment by yonaskolb** [comment]
It's here in point 6 https://github.com/Carthage/Carthage/blob/master/README.md#getting-started

**Comment by toshi0383** [comment]
Thanks 😄

**Comment by yonaskolb** [comment]
Resolved in #84
