### ISSUE TITLE
Group without folder

### ISSUE THREAD

**Issue by abeintopalo** [yonaskolb/XcodeGen#295]
Is there a way to add files to a group without folder like e.g. the _Products_ group?
I'd like to add my _Cartfile_ to a group hierarchy like this:

```
Configurations 
        Carthage
              Cartfile
```

In this case the group hierarchy wouldn't reflect an actual directory hierarchy. The _Cartfile_ could be e.g. in the project's root directory as usually is but in the generated Xcode project it would be placed neatly in the group hierarchy above.

**Comment by yonaskolb** [comment]
This would require #478, so can be tracked there
