### ISSUE TITLE
Add Templates to documentation

### ISSUE THREAD

**Issue by Lutzifer** [yonaskolb/XcodeGen#301]
We could improve onboarding of new users by providing some simple template projects as blueprints,
e.g. https://github.com/num42/RxUserDefaults/blob/master/project.yml for a carthage compatible iOS/tvOS framework project with tests. (It took me some time to set this up, so a collection of blueprints might actually save some time).

**Comment by toshi0383** [comment]
Good idea.
Maybe we can add links to those examples in the wild, too. 👌
I've got mine here.
https://github.com/toshi0383/Bitrise-iOS/blob/master/project.yml

**Comment by Lutzifer** [comment]
Might be a good addition to the readme.

**Comment by yonaskolb** [comment]
Yeah would be cool. I’ve been wanting to add a bunch of use cases with example templates (cross platform targets, Carthage Dependencies, includes, configurations... etc), maybe to the FAQ page

**Comment by pvinis** [comment]
ill add mine to sometime when i have a working react native setup with xcodegen. that would be my dream :D

**Comment by Lutzifer** [comment]
We might be able to contribute some more complex examples, as @yonaskolb already has come to know of due to some of my edge-case issues 😅

**Comment by yonaskolb** [comment]
I've added an examples page now. Feel free to add any of your own specs there https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Examples.md

I've also filled out the FAQ a little bit and added a Usage doc for more specific documentation. https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md
These will both be filled out with more information, but have a bit in there to start.

**Comment by yonaskolb** [comment]
The examples could also possible give a little bit of info about what they include (cross platform targets, uses `includes`, carthage depenendencies ..etc). What do you think?

**Comment by toshi0383** [comment]
That would be great.
`fastlane/examples` page is a good reference I guess.
https://github.com/fastlane/examples

**Comment by LinusU** [comment]
@pvinis

> ill add mine to sometime when i have a working react native setup with xcodegen. that would be my dream :D

Did you ever get this working? Would love to see it! 😍

**Comment by pvinis** [comment]
i gave up after not being able to include libs from a folder. i have to try again soon, since there has been a buuuunch of progress on xcodegen.

ill let you know.
