### ISSUE TITLE
1.8.0 & 1.9.0 release builds crash on Sierra

### ISSUE THREAD

**Issue by dflems** [yonaskolb/XcodeGen#304]
Crash report: https://gist.github.com/dflems/23b307b2ccd8365a6f628ee1420b7b30

I was able to get it running by recompiling 1.8.0 on a machine running Sierra & Xcode 9.2. It appears the github release builds for 1.8.0 and 1.9.0 were built with Xcode 9.3 on High Sierra and that something, somewhere in the build process is creating an instruction that is invalid on Sierra.

**Comment by keith** [comment]
This is a crash in the yaml parser, can you post the contents of your yaml file?

**Comment by yonaskolb** [comment]
@dflems do the new releases work for you now?

**Comment by dflems** [comment]
@yonaskolb We upgraded our CI machines to High Sierra, so the issue sort of resolved itself. The issue was on Sierra only.

**Comment by yonaskolb** [comment]
Ok, closing this for now

**Comment by dflems** [comment]
@yonaskolb @keith I think this issue might have returned but for High Sierra.

```
$ ./xcodegen/bin/xcodegen -h
dyld: Symbol not found: _$s11SubSequenceSlTl
  Referenced from: /Users/spotify-buildagent/xcg/./xcodegen/bin/xcodegen (which was built for Mac OS X 10.14)
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/spotify-buildagent/xcg/./xcodegen/bin/xcodegen
Abort trap: 6
```

Is there a way to build with Swift 5 support but still be able to target High Sierra?

**Comment by dflems** [comment]
Ok, I was able to get it to work on HS by:

1. Invoking the build with `swift build --disable-sandbox -c release -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.13" -Xlinker -rpath -Xlinker @executable_path/../lib`
2. Opening `.build/x86_64-apple-macosx/release.yaml`, finding the link command, and manually removing the `rpath` that contains `Xcode.app` (not sure if there's a better way to do this, i'm quite unfamiliar with swiftpm)
3. Running that modified link command manually
4. Replacing the `bin/xcodegen` in the archive with the newly built binary
5. Adding the following files from Xcode 10.2 to the archive:

```
lib/libswiftCore.dylib
lib/libswiftCoreFoundation.dylib
lib/libswiftCoreGraphics.dylib
lib/libswiftDarwin.dylib
lib/libswiftDispatch.dylib
lib/libswiftFoundation.dylib
lib/libswiftIOKit.dylib
lib/libswiftObjectiveC.dylib
lib/libswiftos.dylib
lib/libswiftXPC.dylib
```

Pretty janky but it seems to work.
