### ISSUE TITLE
Exclude a .xcodeproj

### ISSUE THREAD

**Issue by albyok** [yonaskolb/XcodeGen#309]
I don't know if this is a bug, but seems that I'm not capable of excluding a .xcodeproj from sources setting.

 I tried every way that I could think of, but the file is still there. Even if I exclude a whole folder, all files within that folder are actually excluded, but in the project I get that folder with only the xcodeproj files still there.

**Comment by yonaskolb** [comment]
Interesting. I guess it might be a bug, and to do with `.xcodeproj` actually being a directory and that messing up the ignore logic?
Can you share what you tried as the first attempt? I'm guessing it was something like:
```
targets:
  App:
    sources:
      - path Sources
        exclude: *.xcodeproj
```
Is the `.xcodeproj` a direct child of the sources directory, or in a sub directory?

**Comment by albyok** [comment]
Hi yonaskolb.

I tried this:

excludes:
          - "*.xcodeproj"
          - "Librerie/**"
          - "Librerie/*.[xcodeproj]"

It doesn't affect any xcodeproj. I have some in a direct child and others in a sub dir.

**Comment by albyok** [comment]
Any news?

**Comment by yonaskolb** [comment]
Hi @albyok 
I've added some tests demonstrating the ability to exclude `.xcodeproj` here https://github.com/yonaskolb/XcodeGen/commit/5d611e008af8042823c84884a6e4c60171591489
Note that you should specify this as `*.xcodeproj`

Also note that `**`  is unfortunately not supported so you can't do `**/*.xcodeproj`, so to exclude xcode projects in nested subdirectories you will have to exclude whole directories, or add an exclude for every level eg `Librerie/*.xcodeproj`

Can you confirm this works for you?

**Comment by yonaskolb** [comment]
Closing this for now. Feel free to open again @albyok if you continue seeing the issue

**Comment by albyok** [comment]
I'm gonna try. Sorry, but I missed the notification!

**Comment by brentleyjones** [comment]
#326 probably fixed this.
