### ISSUE TITLE
Default exclude git merge files

### ISSUE THREAD

**Issue by m-ruhl** [yonaskolb/XcodeGen#310]
Hi 👋 ,

Does it makes sense to default exclude all git merge files `*.orig` ?
I'm not sure anymore would use does in a Xcode Project.

I can create a PR, but I wanted to check first 😉 

Greets
Michael

**Comment by yonaskolb** [comment]
Hi @m-ruhl 
I agree git merge files shouldn't be added to the project. But are there workflows where you want to keep these around anyway? Wouldn't they get deleted once you've completed your merge?

I see no harm in adding them to the default ignored files however. Feel free to create a PR if it's an issue for you 😄 👍

**Comment by keith** [comment]
I submitted a fix for this here https://github.com/yonaskolb/XcodeGen/pull/627
