### ISSUE TITLE
Consider renaming project.yml

### ISSUE THREAD

**Issue by stevemoser** [yonaskolb/XcodeGen#312]
[Ceedlings](http://www.throwtheswitch.org/ceedling) uses project.yml files. Consider renaming to a more specific name like xcode-project.yml or xcodegenspec.yml.

**Comment by keith** [comment]
FWIW you can pass an arguement to your project file so you can name it whatever you want using --spec

**Comment by yonaskolb** [comment]
Yeah, as @keith says you can use a custom name. Does that solve your issue @stevemoser? If so I'll close this issue

**Comment by yonaskolb** [comment]
Closing this for now
