### ISSUE TITLE
Weakly link a framework

### ISSUE THREAD

**Issue by iamtomcat** [yonaskolb/XcodeGen#314]
Is there a way currently to weakly or optionally link a framework?

Was looking around and didn't see it.

**Comment by yonaskolb** [comment]
At the moment no, it's not possible to mark a dependency linkage as optional.
It's something that would be possible to add to a dependency definition though, which would then set the required `WEAK` attribute on the framework build file

**Comment by keith** [comment]
You can do this by adding -weak_framework Foo to OTHER_LDFLAGS for the target you want to weakly link Foo

**Comment by yonaskolb** [comment]
True, that’s a good workaround 👆

**Comment by iamtomcat** [comment]
@keith Thanks man that's a good workaround.

**Comment by yonaskolb** [comment]
Added in #411, and will be in the next release
