### ISSUE TITLE
Source excludes can't be a string, only a string array

### ISSUE THREAD

**Issue by philippelatulippe** [yonaskolb/XcodeGen#319]
For the Target Source object, the documentation states that

> excludes: [String] or String - A list of global patterns representing the files to exclude.

If I use a string instead of an array, it is ignored. `TargetSource.excludes` will be empty.

Here's an example of a target where the issue occurs:
```targets:
  SomeTarget:
    platform: iOS
    type: application
    sources:
      - path: Sources
        excludes: "*.orig"
```

The workaround is to use an array:
```targets:
  SomeTarget:
    platform: iOS
    type: application
    sources:
      - path: Sources
        excludes: 
          - "*.orig"
```

**Comment by yonaskolb** [comment]
Yes, right you are. Documentation updated 👍
