### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by brentleyjones** [yonaskolb/XcodeGen#329]
I was just wondering what the criteria is for a new release? I see we haven't gotten one since April and there have been a couple good bug fixes merged since then. Thanks!

**Comment by yonaskolb** [comment]
Yes usually a new release is pushed when important fixes go in or a bunch of new features. It's pretty adhoc.
Usually there isn't so long a delay for a release, but this one has taken a while, apologies. But good news is, it's released now 😄 https://github.com/yonaskolb/XcodeGen/releases/tag/1.10.0

I'll add a `RELEASE.md` so others can also push a release 👍
