### ISSUE TITLE
1.10.0 - Targets marked as don't code-sign by default

### ISSUE THREAD

**Issue by eskerber** [yonaskolb/XcodeGen#330]
## What

After the changes in https://github.com/yonaskolb/XcodeGen/pull/324, framework targets are not code signed by default and must be explicitly marked.

## Effects

If `codeSign: true` is not specified for framework target dependencies, deploying to device will result in an error “No code signature found”

## Proposed Solution

Like discussed [here](https://github.com/yonaskolb/XcodeGen/pull/324#issuecomment-400872800), the logic could be modified slightly to disable code signing based on:

- The destination (i.e. plugins) _or_
- Whether the target is an app extension or not (borrow logic from here:)

https://github.com/yonaskolb/XcodeGen/blob/c79a205339a150ef3000985cc542ccb6564f8a4f/Sources/XcodeGenKit/PBXProjGenerator.swift#L458

**Comment by yonaskolb** [comment]
Fixed in #333
I tried using app extension or plugin destination but it missed some cases (for example iMessage apps aren't extensions but require code signing to be off)
I've changed the heuristic to code sign all dependencies except executables. Leave your comments in the PR
