### ISSUE TITLE
Carthage dependencies are now included in targets that both use carthage dependencies

### ISSUE THREAD

**Issue by iamtomcat** [yonaskolb/XcodeGen#335]
## PaywithSDK

    dependencies:
      - carthage: FirebaseCore
      - carthage: FirebaseInstanceID
      - carthage: nanopb
      - carthage: FirebaseNanoPB
      - carthage: FirebaseAnalytics
      - carthage: TTTAttributedLabel
      - carthage: AFNetworking
      - carthage: CountryPicker
      - carthage: GoogleToolboxForMac
      - carthage: CardIO

<img width="616" alt="screen shot 2018-07-04 at 3 22 17 pm" src="https://user-images.githubusercontent.com/6033483/42295341-0da3f182-7f9e-11e8-9b8b-8fecd746f1a5.png">

## Paywithpush

    dependencies:
      - carthage: AirshipKit
      - target: PayWithSDK

<img width="668" alt="screen shot 2018-07-04 at 3 21 53 pm" src="https://user-images.githubusercontent.com/6033483/42295337-05758a0c-7f9e-11e8-9143-991c167e70bf.png">

My initial thought is that when the first target is made the dependency array isn't being cleared for the other targets.

**Comment by brentleyjones** [comment]
This is deliberate from https://github.com/yonaskolb/XcodeGen/pull/327. It can be turned off with the new option. I’m assuming it’s an issue because some of those frameworks should be statically linked? For now you can do `embed: false` on them under PaywithSDK and they will be “seen” as a static framework and not linked against targets further down the dependency chain.

**Comment by yonaskolb** [comment]
Yep as @brentleyjones says. 
@iamtomcat Is this actually causing build issues for you? If so maybe we have to set the default of `transitivelyLinkDependencies` to false to not break existing projects, and perhaps make the default true in a future release.

**Comment by brentleyjones** [comment]
The more I think about it, until we get smarter about static frameworks, I think `transitivelyLinkDependencies` should default to false.

**Comment by yonaskolb** [comment]
Set default to false and released in 1.10.2

**Comment by iamtomcat** [comment]
Hey yeah sorry I must have missed that flag in the change log. Thanks for pointing it out to me. Also thanks for the quick turn around time.
