### ISSUE TITLE
Organization name in config file

### ISSUE THREAD

**Issue by jasesuperhero** [yonaskolb/XcodeGen#338]
When I regenerate project, i dont have organization name in my xcproject settings. Can I set organization name, prefix, and identity size with xcodegen spec?

**Comment by jasesuperhero** [comment]
@yonaskolb, what about this feature?

**Comment by yonaskolb** [comment]
@jasesuperhero as far as I understand the organisation name and bundle prefix aren't stored in a specific project, but instead are stored against your whole user within Xcode. If you can find somewhere in the `.xcodeproj` that this is stored, let me know

**Comment by jasesuperhero** [comment]
@yonaskolb we have this attribute in this section of pbxproj file:
```
/* Begin PBXProject section */
		83CBB9F71A601CBA00E9B192 /* Project object */ = {
			isa = PBXProject;
			attributes = {
				CLASSPREFIX = SO;
				ORGANIZATIONNAME = SomeOrganization;
				...
			};
			...
		};
/* End PBXProject section */
```

**Comment by jasesuperhero** [comment]
Thanks! 😄
We can add this to example in project spec! It's not trivial. What do you think about this?
