### ISSUE TITLE
Carthage copy phase

### ISSUE THREAD

**Issue by peymankh** [yonaskolb/XcodeGen#357]
Hey guys,

Do you know if there's a way to use `mint run Carthage carthage copy-frameworks` instead of `carthage copy-frameworks` in the Carthage build phase?

@yonaskolb maybe 😉?

**Comment by brentleyjones** [comment]
That would be a nice project option!

**Comment by yonaskolb** [comment]
Yep, already supported 👍 Just set it like this

```yaml
options:
  carthageExecutablePath: mint run Carthage carthage
```

`carthageExecutablePath` is what is prepended to `" copy-frameworks"`

**Comment by yonaskolb** [comment]
It should probably just be called `carthageExecutable`, but it was named when it was assumed it would be a path and not a fancy `mint` command 😄

**Comment by peymankh** [comment]
@yonaskolb 

Fancy indeed. Awesome, thanks.
