### ISSUE TITLE
Add ability to embed Carthage frameworks without using `copy-frameworks`

### ISSUE THREAD

**Issue by brentleyjones** [yonaskolb/XcodeGen#359]
On our project we have many test targets, and all of them depend on Carthage versions of Quick and Nimble. When we build this with parallel builds enabled a Carthage bug can be hit where two instances of `copy-frameworks` try to strip the same dSYM (https://github.com/Carthage/Carthage/issues/2531). Since test targets don't really need to strip anything at all, it would be good to be able to specify on a target that we want to embed the Carthage frameworks instead of using `copy-frameworks`. It can default properly for test targets.

I will add a `directlyEmbedCarthageDependencies` to `Target`. Right now it would be `true` for `.macOS` platform, and I'll extend it to be `true` for test targets as well.

**Comment by yonaskolb** [comment]
In my opinion this is a big in Carthage and should be fixed there. Is there any other reason you would want to turn this on?

**Comment by brentleyjones** [comment]
They just said it's a bug on our side. They are correct. Only iOS apps need to use that script, since no other targets need to strip the simulator slice. I have a PR incoming.

**Comment by brentleyjones** [comment]
> Is there any other reason you would want to turn this on?

Mainly the option would be to turn it off, since we will default it to on for basically everything but the application.

**Comment by brentleyjones** [comment]
I guess on macOS you might want to strip the frameworks as well? Another case for adjusting the default.
