### ISSUE TITLE
CoreData model versioning configuration

### ISSUE THREAD

**Issue by rpassis** [yonaskolb/XcodeGen#362]
Hi all,

Just wondering if it is possible to select a versioned CoreData model "current version" option using XcodeGen? I had a look at the documentation but haven't been able to find it.

Thanks for developing such a great tool!

Rog

**Comment by yonaskolb** [comment]
Hi @rpassis, there is currently no way to manually select a core data model version, however some work was done recently to automatically select the newest one by sorting them https://github.com/yonaskolb/XcodeGen/pull/341 
It will be in the next release. Would that solve your issue?

**Comment by rpassis** [comment]
Hey @yonaskolb thanks for the quick response! I was just having a look at that PR. I'll build from master to test it and update here but it looks like that's likely to do the trick!

FWIW the filename/path fix seems a bit fragile and a possible alternative would be to check if there is a `.xccurrentversion` file inside a versioned model, and set the version based on that. Here's a related issue that was tackled by Xcodeproj https://github.com/CocoaPods/Xcodeproj/issues/81

**Comment by rpassis** [comment]
Yup that file sorting change has fixed the issue, thanks again!

**Comment by yonaskolb** [comment]
Great! I'll reopen this for tracking the proper fix, if anyone wants to work on it

**Comment by rpassis** [comment]
I'll see if I can tackle this one myself, watch this space!

**Comment by yonaskolb** [comment]
Fantastic! 😄👍

**Comment by brentleyjones** [comment]
Fixed by #364.
