### ISSUE TITLE
Folders added as folder references instead of groups

### ISSUE THREAD

**Issue by danicoello** [yonaskolb/XcodeGen#371]
I have three folders on disk:
- folder1
- folder2
- folder1.1

When I generate my .xcodeproj file using `xcodegen` command first two folders are added as groups as usual but third folder is added as folder reference so every file contained on that folder is not added to target and compilation fails.

I'm executing version 1.10.3.

**Comment by brentleyjones** [comment]
Does using a `type` of `folder` work? 
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#sources

**Comment by brentleyjones** [comment]
Ohh, it's incorrectly seeing it as a "folder like file".

**Comment by Lutzifer** [comment]
Though it is the younger issue, #396 covers this in more detail.
Should we close this ticket to avoid having duplicates?

**Comment by yonaskolb** [comment]
Yep, use #396 for discussion
