### ISSUE TITLE
TEST_HOST should be set automatically

### ISSUE THREAD

**Issue by brentleyjones** [yonaskolb/XcodeGen#377]
When a test has an app as a target it should set the `TEST_HOST` automatically. We need to make sure not to break UI tests though. Discussed here:  https://github.com/yonaskolb/XcodeGen/issues/372#issuecomment-411321621.

**Comment by yonaskolb** [comment]
Somewhat related to #71

**Comment by yonaskolb** [comment]
Duplicate of of #408
