### ISSUE TITLE
Generation failed: The folder “project.pbxproj” doesn’t exist.

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#378]
We've been getting this warning sporadically with XcodeGen 1.10.2. I'm not sure how to reproduce it yet, but I was wondering if anyone else has seen this issue. It appears to be coming from this catch:  https://github.com/yonaskolb/XcodeGen/blob/6c35c332e973c4a0bfb0f87c285fcc4e23a8db55/Sources/XcodeGen/main.swift#L66

**Comment by yonaskolb** [comment]
Hmm, haven't seen this before. Is it still happening?

**Comment by keith** [comment]
We haven't seen this since, but we never really saw it frequently either.

**Comment by rebello95** [comment]
FWIW I saw this yesterday. Seems to happen occasionally (inconsistently) when a large number of files change since the last generation

**Comment by rebello95** [comment]
Adding a bit more info: I noticed today that this occurs when running XcodeGen on 2 project workspaces simultaneously (in my case, 2 different clones of the same repo in sibling directories on my machine). When doing so, one of them will fail pretty consistently.

**Comment by keith** [comment]
I saw this one today too, I think this is because Xcode is open with the project, and it must try to do something during that time that borks the writing

**Comment by bryansum** [comment]
We're seeing this intermittently too... running many clones of the same repo in a manner similar to @rebello95
