### ISSUE TITLE
Metal files added to "Copy Bundle Resources" rather to "Compile Sources" build phase.

### ISSUE THREAD

**Issue by vgorloff** [yonaskolb/XcodeGen#379]
The files with extension `.metal` is type of "Metal Shader Source" which needs compilation build phase. At the moment files just added to "Copy Bundle Resources" build phase.

Hope it is easy to fix issue .)
Thank you!

**Comment by keith** [comment]
It needs to be added here https://github.com/yonaskolb/XcodeGen/blob/461de39f8e7c837a78f5617bc4fc20d4d84267b7/Sources/XcodeGenKit/SourceGenerator.swift#L191 can you submit a PR?

**Comment by vgorloff** [comment]
Ok. I am finishing converting one project with Shaders. Then will make a fix and PR.

**Comment by vgorloff** [comment]
PR is ready and it passes tests. Please review and merge.
Thanks!
