### ISSUE TITLE
Adding files without any target

### ISSUE THREAD

**Issue by ethanjdiamond** [yonaskolb/XcodeGen#384]
There are files in my project that I'd like to be able to access from Xcode, but not add to any particular target. An example is I have .stencil templates that I'd like to be able to edit from Xcode but not actually ship with my project. Is there a way to achieve that in the project.yml?

**Comment by brentleyjones** [comment]
Yes, using `fileGroups`: 
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#project

**Comment by ethanjdiamond** [comment]
Ah, great. Is there any way to do that in a way that does string matching? Something like 

fileGroups:
  - "*.stencil"

**Comment by yonaskolb** [comment]
No, pattern based sources isn't possible...yet

**Comment by ethanjdiamond** [comment]
Ok! Thanks!

**Comment by michaelfransen** [comment]
Is there a way to have a file not be included for a target but have it show in Xcode in its current location versus making it show in Xcode at the root of the project?
