### ISSUE TITLE
Does not generate knownRegions if there are no resources in the project

### ISSUE THREAD

**Issue by Saik0s** [yonaskolb/XcodeGen#389]
When I am trying to run R.swift in the generated project without resources, it gives me an error 
```
error: [R.swift] Project file at 'file:///Users/saik0s/Documents/Projects/modular/Projects/Profile/Profile.xcodeproj/' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?
The operation couldn’t be completed. (XcodeEdit.AllObjectsError error 0.)
```
After some investigation, I found that the problem is in `knownRegions` parameter. It is not generated when there are no localized resources. But project generated by Xcode sets this parameter to 
```
knownRegions = (
	en,
);
```
by default even without resources.

**Comment by yonaskolb** [comment]
Thanks for the report @Saik0s.
It’s not a required property from Xcode’s point of view, but the library that R.swift uses to parse the project expects it. We can add a default en value though 👍
