### ISSUE TITLE
Question related to code signing identity settings on project.yml

### ISSUE THREAD

**Issue by ezegutierrez** [yonaskolb/XcodeGen#395]
Hi!
I'm having troubles trying to integrate fastlane on my project. The issue is due to "Any iOS SDK" setting is added by default on code signing identity when .xcodeproject is generated, thus it's giving me an error when I'm trying to archive the project through fastlane. 

I don't know how can I remove that setting from my project.yml. Is there any way to do that?

This is the settings that I want to remove from the .xcodeproject:
<img width="463" alt="screen shot 2018-09-11 at 18 31 49" src="https://user-images.githubusercontent.com/7784016/45389574-adf49300-b5f2-11e8-9fab-386f39fe1b30.png">

Thanks in advance.

**Comment by kyleturner** [comment]
I am also having this exact same issue. I can set the `Debug` and `Release` values correctly, but cannot get "Any iOS SDK" to match.... would be nice to not have to reach into proj settings to do so. Thanks!

**Comment by yonaskolb** [comment]
Hi guys, thank you for raising this. I've created a fix for this in #414
