### ISSUE TITLE
Embedded Frameworks: 'Code Sign on Copy' is always false

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#42]
Although embedding frameworks is working flawlessly, it seems `Code Sign on Copy` will be always `false` (checked off) even in case specifying it manually by: `codeSign: true`.

**Comment by yonaskolb** [comment]
@ImLaufderZeit This is fixed on master if you'd like to test it

**Comment by yonaskolb** [comment]
Fixed in 0.5.1. 
Let me know if you still have issues with it @ImLaufderZeit

**Comment by ImLaufderZeit** [comment]
Confirmed it is now working as expected in 0.5.1. Great job!
