### ISSUE TITLE
Request: add parallelizable = "YES|NO" and testExecutionOrdering = "random" options to XCScheme.TestableReference generator.

### ISSUE THREAD

**Issue by sjepifanov** [yonaskolb/XcodeGen#421]
Not sure if it should be here and not under tuist/xcodeproj, but since XcodeGen is not on latest xcodeproj anyway I see no reason to create the issue under xcodeproj git.

Xcode 10 introduced several options for tests:
parallelizable = "YES|NO"
testExecutionOrdering = "random"

xcodeproj included with XcodeGen (4.3.1) could only set option "skipped=YES|NO" to TestableReference section of .xcscheme file. That is also true for xcodeproj 6.0 (current latest)

These options are implemented in [CocoaPods\Xcodeproj](https://github.com/CocoaPods/Xcodeproj/blob/master/spec/scheme/test_action_spec.rb)
but we are not using that tool.

In case there is nothing to be done with the problem on XcodeGen side, I will post the issue on tuist\xcodeproj git. Yet it's up to XcodeGen to use the latest xcodeproj then.

**Comment by yonaskolb** [comment]
Yes, we need xcodeproj support first. If you could open an issue there as well that would be great 👍

**Comment by sjepifanov** [comment]
Opened an issue with tuist\xcodeproj [#335](https://github.com/tuist/xcodeproj/issues/335)

**Comment by yonaskolb** [comment]
Added in #434
