### ISSUE TITLE
Incompatible with project sorting

### ISSUE THREAD

**Issue by samskiter** [yonaskolb/XcodeGen#424]
We use XCodeGen to bootstrap creating new XCode projects.

We also sort our project files (using the [Apple sort script](https://github.com/mas-cli/mas/blob/master/script/sort.pl))

Unfortunately the project generated by XCodeGen is incompatible with the sort script for a couple of reasons:

1. The UUIDs generated are not of the same format that XCode would generate. (They are of the format AAA_123456789123)
2. The output lines do not always match the [regex that matches "in"](https://github.com/mas-cli/mas/blob/master/script/sort.pl#L170) because some of them do not contain "in" in sections where that would be expected.

I believe that (1) is definitely XCodeProj's responsibility, so I have raised this: https://github.com/tuist/xcodeproj/issues/344

But I'm unsure where the second issues is coming from..

Can you advise?

**Comment by yonaskolb** [comment]
Xcodegen will use standard UUID's in the next release
