### ISSUE TITLE
Ability to not link Carthage framework?

### ISSUE THREAD

**Issue by sbarow** [yonaskolb/XcodeGen#426]
In a framework with the following:

```
dependencies:
	- carthage: Firebase.framework
	  link: false
```

Firebase would still be linked in `Link Binary With Libraries` in the Build Phases, is this expected or is there another way to achieve this?

Thanks.

**Comment by yonaskolb** [comment]
Yeah looks like that `link` property is not being used for `carthage` dependencies. What's the use case of adding a carthage dependency but not linking it?

**Comment by sbarow** [comment]
From https://github.com/firebase/firebase-ios-sdk/issues/911

> The Firebase.framework is only needed to provide build time access to the Firebase module and Firebase.h. It is not needed for linking. Thus a workaround is to delete Firebase.framework from the Link Binary With Libraries Build Phase.

Don't think its a very common use case but does solve this issue for now.

**Comment by yonaskolb** [comment]
Added here https://github.com/yonaskolb/XcodeGen/pull/432

**Comment by sbarow** [comment]
Wow that was quick, thank you.
