### ISSUE TITLE
knownRegions should contain the developmentRegion value instead of 'Base'

### ISSUE THREAD

**Issue by Westacular** [yonaskolb/XcodeGen#436]
Right now, XcodeGen populates `knownRegions` by just taking the names of all `*.lproj` folders it finds.

I ran into an issue because my project's development language is English, but contains no `en.lproj` folders, only `Base.lproj`. Consequently, `knownRegions` did not contain `en`.

This made Xcode behave in a moderately confused way when handling things related to base localization / development language:

- The project settings list of localizations was missing the "English — Development Language" entry
- The "English (Development Language)" checkbox was missing from the "Export for Localization..." dialog box
- If I unchecked the "Use Base Internationalization" option in project settings, the dialog box that asks what language to turn the "Base" resources into would be missing "English" as an option, and instead have a cryptic "<DVTLocale ... " entry.

This was worked around by just adding an `en.lproj/.gitkeep` item in the repo, to trigger XcodeGen to have an `en` item in `knownRegions`, but that should not be necessary.

Comparing with some other Xcode projects shows that `knownRegions` normally does NOT contain `Base` in the list, but should always contain (if nothing else) the language code for the `developmentRegion`.

**Comment by yonaskolb** [comment]
Thanks for opening this @Westacular and providing all the info 👍 
Would you be interesting in having a go at fixing this in a PR? I'd be happy to help answer any questions you have. 
Otherwise I could look at it sometime next week

**Comment by liamnichols** [comment]
Maybe we can close this in favour of #954?

**Comment by yonaskolb** [comment]
Good idea @liamnichols 👍
