### ISSUE TITLE
Generating Info.plist overwrites path specified in settings>configs

### ISSUE THREAD

**Issue by feischl97** [yonaskolb/XcodeGen#440]
I have a project where a target has different configs. One of those configs uses a different Info.plist than the others. 
When I create a Info.plist with xcodegen it overwrites every config with the generated one, even if I have specified a path for it via INFOPLIST_FILE build setting.

Example: In this case Predifined.plist for debug gets overwritten with Generated.plist.
![plistoverwrite](https://user-images.githubusercontent.com/28102489/48704215-48c2ac80-ebf6-11e8-802d-a39a0cf00eb0.png)

Suggestion: When there is a path for a predefined plist set, do not overwrite it with the created one.

Related issues: #207, #406

**Comment by yonaskolb** [comment]
The generated info plist was designed to be a simple way to set info plist properties without creating your own. For more complex cases custom settings can be set per config that point to existing files.
Having said that there's no reason that we shouldn't allow the `INFOPLIST_PATH` to be overwritten by custom settings, like you've done here. So yes, this can be changed 👍 
The automatic `INFOPLIST_PATH` that is set by looking into the source files would still be overriden by the `info` property.
