### ISSUE TITLE
--project command not work

### ISSUE THREAD

**Issue by chenjunpu** [yonaskolb/XcodeGen#447]
Full `xcodegen generate` command `--project` not work

when i use: 

```shell
xcodegen --project ~/Downloads
```

```shell
📋  Loaded project:
  Name: Test
  Include:
    Libraries/environments.yml
  Targets:
    Test: iOS application
⚙️  Generating project...
⚙️  Writing project...
💾  Saved project to /Users/hb/Downloads/Test.xcodeproj
```

Log path is right, but xcodeproj still in the old path.
My xcodegen version: 2.0.0

**Comment by yonaskolb** [comment]
Thanks for opening @chenjunpu. This was a regression that has been since fixed on master, and will be in the next release

**Comment by yonaskolb** [comment]
Released in 2.1.0

**Comment by ninjazoete** [comment]
Hi, I am using 2.1.0 and still when passing a path it does say it put the .xcodeproj there but it is always in the root of the spec.

**Comment by chenjunpu** [comment]
Me too, still has this problem.
