### ISSUE TITLE
Devices - Deployment info

### ISSUE THREAD

**Issue by VictorUrielPG** [yonaskolb/XcodeGen#456]
Is there a way to set the Deployment info Device?

<img width="526" alt="captura de pantalla 2018-12-06 a la s 20 00 47" src="https://user-images.githubusercontent.com/29692881/49623080-bd853d00-f991-11e8-9ae0-c547250cbc19.png">

I want my project to be only for iPhone instead of Universal and I couldn't find the documentation about it.

![image](https://user-images.githubusercontent.com/29692881/49623099-d2fa6700-f991-11e8-9e08-b78135c77071.png)

BTW, thank you for this awesome  tool.

**Comment by yonaskolb** [comment]
Hi @VictorUrielPG 
This is controlled with the `TARGETED_DEVICE_FAMILY` setting. For iPhone only you can set it to 1. You can set this for the whole project or just the app:

```yml
apps:
  MyApp:
	settings:
		TARGETED_DEVICE_FAMILY: 1
```

To find things like this out you can change settings in some project that's checked in and see the git diff that it creates.

I'll close this for now. If you have any more questions feel free to ask or create a new issue 👍
