### ISSUE TITLE
xcodegen --version was removed in update 2.1?

### ISSUE THREAD

**Issue by JFryer12** [yonaskolb/XcodeGen#458]
Is there any reason that xcodegen --version was removed in update 2.1?

**Comment by yonaskolb** [comment]
Hmm, looks like a regression with the change of the command architecture. `xcodegen version` works however. Is that sufficient for your needs or do you require backwards compatibility for `--version`?

**Comment by kgellci** [comment]
`xcodegen version` outputs `Version: X.Y.Z` while `-v` would output `X.Y.Z` if I remember correctly. Seems as output format is different which breaks some of my scripts.

**Comment by kgellci** [comment]
Here is the commit that broke it https://github.com/yonaskolb/XcodeGen/commit/07cd5a4a0b120e1c5fce128098c447abbbb7333b#diff-37ca2dd15ca0f6b1b49e78db084ef5b9

Moving from Commander to SwiftCLI. No big deal for me, easy to fix scripts, but in case it is an issue for others.

If it needed to be fixed, could probably set the default version command to nil and add a custom `Flag` to output the old format.

https://github.com/jakeheis/SwiftCLI#version-command

**Comment by yonaskolb** [comment]
For context, do you use this for locking to a specific version?

**Comment by kgellci** [comment]
For locking and for easy setup. Script reads version required by project and will download the appropriate zip from release branch and unzip locally if version is different or xcodegen does not exist locally. By locally I mean local to the project.
