### ISSUE TITLE
Use template name relatively into template

### ISSUE THREAD

**Issue by Alex293** [yonaskolb/XcodeGen#462]
I have like 10 framework representing features which have this folder structure : 
Features/FeatureX/Sources
Features/FeatureX/Tests
Features/FeatureX/SupportingFiles/info.plist
Features/FeatureX/SupportingFiles/testsinfo.plist

I'd like to define a template able to generate the framework target and it's test target. Right now I'm overriding the paths when I import the target. Is there a way to use the target name as a var inside the template so It pickup the right paths without explicitly typing them ?

**Comment by AlexisQapa** [comment]
That would be very convenient indeed !

**Comment by yonaskolb** [comment]
Implemented in https://github.com/yonaskolb/XcodeGen/pull/504
