### ISSUE TITLE
Support PBXAggregateTarget

### ISSUE THREAD

**Issue by ImLaufderZeit** [yonaskolb/XcodeGen#47]
It seems that https://github.com/swift-xcode/xcodeproj supports PBXAggregateTarget (?), but XcodeGen doesn't.
Priority would be low though, I often use the kind of target in framework projects to invoke archive script.

**Comment by mironal** [comment]
I want this feature. but it is difficult for me to implement. 😭

**Comment by yonaskolb** [comment]
How would you guys imagine this feature looking in yaml?

Would something like this work?
A new top level `aggregateTargets`, that has a map of target name to the following structure:
- targets: [String]
- prebuildScripts
- postBuildScripts

Is that all that would be needed? Do you need to be able to set build settings on an aggregate target?

**Comment by vgorloff** [comment]
We mostly using `aggregateTarget` to execute scripts. For instance as global `Prepare` target set as dependency for any other target. Just to avoid setting pre-build scripts in every target.

**Comment by yonaskolb** [comment]
Would target inheriting solve the same problem as you could easily apply a build script to all targets? https://github.com/yonaskolb/XcodeGen/issues/285

**Comment by brentleyjones** [comment]
Ideally the build script is run once though. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yonaskolb** [comment]
Got it

**Comment by yonaskolb** [comment]
Aggregate targets added here #354, but with a strange issue
