### ISSUE TITLE
How to specify UseModernBuildSystem - false? 

### ISSUE THREAD

**Issue by johndpope** [yonaskolb/XcodeGen#470]
Normally -
File >  project settings > build system > Legacy 

https://github.com/tensorflow/swift-models/issues/10
<img width="505" alt="screen shot 2019-01-03 at 1 03 12 pm" src="https://user-images.githubusercontent.com/289994/50653580-f516e300-0f57-11e9-81a9-954e01dbbcdc.png">

**Comment by johndpope** [comment]
NB. this didn't work - 

    Legacy:
      type: ""
      platform: macOS
      legacy:
        toolPath: /usr/bin/true
        passSettings: true

**Comment by johndpope** [comment]
related - https://stackoverflow.com/questions/51205221/how-can-i-use-the-legacy-build-system-with-xcode-10s-xcodebuild

**Comment by keith** [comment]
We've never tried this with XcodeGen but for our project we use a xcworkspace that is checked in where we set this setting, and it includes the generated xcodeproj

**Comment by yonaskolb** [comment]
@johndpope back when the new build system was opt in this used to be an **attribute** of the project which was settable via the `attributes` property. 

This is now no longer the case and the setting seems to be written to a new type of file at `Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings`.
This file isn't written by xcodegen, so one option is to check it in, and it won't be overriden by xcodegen. That does mean it will look like the `.xcodeproj` is checked in when it isn't really. The other workaround is to use a workspace like @keith suggested.

Going forward, having the ability to set properties in this file will be useful, as something else came up recently that required access to that file. Support will first need to be added to https://github.com/tuist/xcodeproj

**Comment by johndpope** [comment]
I wondered if Xcodegen would spit out a workspace - is it a bit of work to do this (I imagine it is)?

**Comment by rarabass** [comment]
when you update the Xcode->File->Project Settings->Build System = Legacy Build System,
it updates Projectname.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings.
```
<dict>
	<key>BuildSystemType</key>
	<string>Original</string>
</dict>
```
when you set it to "New Build System", this file does not have this block
