### ISSUE TITLE
Ability to disable debugging in Scheme run phase

### ISSUE THREAD

**Issue by AlexisQapa** [yonaskolb/XcodeGen#485]
Hi, I'm using custom schemes for my different configs. There is one catch thought, I have a Production scheme that is not debuggable as per it's configuration. When I press the run button in Xcode the app won't launch unless I uncheck the debug box. Is there a way to uncheck this from the scheme definition ?
<img width="709" alt="screenshot" src="https://user-images.githubusercontent.com/31622518/50827153-fd976100-133d-11e9-9018-019b72080488.png">

**Comment by yonaskolb** [comment]
Hmm, no this isn’t possible at the moment

**Comment by yonaskolb** [comment]
Looks like it would require this change:
```diff
<LaunchAction
    buildConfiguration = "Debug"
-	 selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
-    selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
+    selectedDebuggerIdentifier = ""
+    selectedLauncherIdentifier = "Xcode.IDEFoundation.Launcher.PosixSpawn"

```
That's doable

**Comment by AlexisQapa** [comment]
That would be very convenient indeed !

**Comment by sassiwalid** [comment]
there is a solution for this issue now please?

**Comment by yonaskolb** [comment]
Yes, you can use `debugEnabled` for this https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#common-build-action-options
