### ISSUE TITLE
Config-specific build settings not reliably applied

### ISSUE THREAD

**Issue by nickdowell** [yonaskolb/XcodeGen#491]
After upgrading from version 1.10.3 to 2.1.0 I have encountered a problem with how XcodeGen applies per-config build settings for a target.

Given a `project.yml` with the following configs:
```
configs:
  Debug: debug
  Release: release
  Release_Staging: release
  Release_Live: release
```
and the following target settings:
```
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        INFOPLIST_FILE: TestApp/Info.plist
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.acme.TestApp.Debug
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.acme.TestApp.Release
        Release_Staging:
          PRODUCT_BUNDLE_IDENTIFIER: com.acme.TestApp.Release_Staging
        Release_Live:
          PRODUCT_BUNDLE_IDENTIFIER: com.acme.TestApp.Release_Live
```

the output Xcode project will not always have the correct `PRODUCT_BUNDLE_IDENTIFIER` for each of its build configurations.

When `xcodegen` is run, the build configurations are incorrect:

<img width="591" alt="screenshot 2019-01-15 at 15 50 48" src="https://user-images.githubusercontent.com/61777/51191956-656d1f00-18dd-11e9-9856-6f36f78537cd.png">

The results are not consistent, running `xcodegen` again can result in:

<img width="626" alt="screenshot 2019-01-15 at 15 53 38" src="https://user-images.githubusercontent.com/61777/51192122-c4329880-18dd-11e9-928a-b2e27302bbd4.png">

or

<img width="632" alt="screenshot 2019-01-15 at 15 56 53" src="https://user-images.githubusercontent.com/61777/51192317-35724b80-18de-11e9-98f8-fad8a5f9856d.png">

I have created a sample project that demonstrates the bug: https://github.com/nickdowell/xcodegen-bug

**Comment by yonaskolb** [comment]
Hi @nickdowell, thanks for raising this.

It looks like this is a quirk of how config specific settings are defined and applied. There is a feature where you can just write part of the config name to be able to apply to multiple at once, eg `Test` would apply to `Test-Debug` and `Test-Release`. https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#settings

In your case `Release` is being applied to all the configs that include the word `Release` but in a non derterministic order. One fix we could make is to not do partial lookups if there is an exact match. This could also be checked for in the spec validation pass.

One workaround for now is to rename your configs so they don’t contain parts of the names of others, at least in how you reference them. For example you could rename `Release` to something more meaningful depending on how you use it (perhaps `Beta`?). If you don’t even use it you can also remove it

**Comment by nickdowell** [comment]
Hi @yonaskolb thanks for your answer, I have now been able to update our configurations to work around this 😀

The partial lookups seem like a potentially useful feature that would be a shame to remove, although perhaps not intuitive... I should have read the documentation more closely 😂
