### ISSUE TITLE
Can I change Xcode version compatibility?

### ISSUE THREAD

**Issue by pvinis** [yonaskolb/XcodeGen#494]
Right now I see that the `compatibilityVersion` is 3.2.

Can I change this to 9.3 or 10.0 or is there no such option?

If there is, how?
If there is not, is it because it didn't happen until now, or is there another reason?

Thanks.

**Comment by yonaskolb** [comment]
Hi @pvinis. Currently there isn't a way to change this in the spec. It looks like Xcode 10.1 now sets this to `Xcode 9.3` by default when creating a project, so we could follow that.
What issues is this causing for you?

**Comment by pvinis** [comment]
I am trying to recreate a project using xcodegen so I'm adding little by little too the yml, generate, then compare with filemerge to see what else is different. it's mostly fine, but the compatibility setting changes the structure in a few places when I change it from 3.2 to 9.3, so currently I generate and then open in xcode, change the compatibility and then compare.

I guess I could clone and change it but maybe adding an option would be useful for others too. I don't know if sone people need the 3.2 compatibility.

what do you think about all that?

**Comment by yonaskolb** [comment]
There's a PR to update the compatibility here https://github.com/yonaskolb/XcodeGen/pull/497

What sort of structure changes are you seeing in your project when updating that value? Be aware that just changing the compatibility version doesn't change anything else about the generated project. Also that when you open a project in Xcode it may make some other subtle changes, and then also again the first time you make any sort of change to the project. Maybe that's what you're seeing?

**Comment by pvinis** [comment]
<img width="843" alt="screen shot 2019-01-22 at 07 52 27" src="https://user-images.githubusercontent.com/100233/51517351-b5d30800-1e1a-11e9-9a1e-42227fde127d.png">
These are the changes I get when changing the compat to 9.3 inside xcode.

Sometimes I also get this:
<img width="782" alt="screen shot 2019-01-22 at 07 55 56" src="https://user-images.githubusercontent.com/100233/51517475-2d089c00-1e1b-11e9-80a5-339ed1c10fdc.png">

**Comment by pvinis** [comment]
Maybe I'm trying to fight this too much, and instead of making the xcodeproj file be exactly the same minus the ids is too much. Maybe I should just open the two projects and just go through every part of the project and make sure what I need is there, all the links and connections and settings and files, without messing with the actual xcodeproj representation..?

**Comment by yonaskolb** [comment]
Yeah I think that’s best

**Comment by pvinis** [comment]
Alright, I'll go that way. Thanks for the PR and the quick response. It's still useful to keep the option to change it, as well as change to the default of 9.3.
