### ISSUE TITLE
Plans to support xcfilelist?

### ISSUE THREAD

**Issue by lukewakeford** [yonaskolb/XcodeGen#499]
Hey 👋, Is xcodegen planning to support the [recent Xcode 10 addition](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10#3035615) of `.xcfilelist` files for build scripts?

> Run Script build phases now support declaring input and output files in a .xcfilelist file. This file should contain a newline-seperated list of the file paths for the inputs or outputs. Build setting references may be used in these paths. The path to a copy of the .xcfilelist file with resolved build setting references will be provided in the SCRIPT_INPUT_FILE_LIST_(#) and SCRIPT_OUTPUT_FILE_LIST_(#) environment variables of the Run Script phase. Projects which use an .xcfilelist require Xcode 10. (39241255)

✌️

**Comment by yonaskolb** [comment]
Hi @lukewakeford, yeah this should be pretty easy to add. Feel free to also create a PR for this

**Comment by yonaskolb** [comment]
If you’re interested in contributing I can answer any questions you might have on getting started

**Comment by lukewakeford** [comment]
Sure i'll take a look, will give you a shout if I get stuck 👍
