### ISSUE TITLE
Optional: true does not disable missing path check 

### ISSUE THREAD

**Issue by nzhuk** [yonaskolb/XcodeGen#519]
xcodegen 2.2.0

Sources marked with `optional: true` cause `xcodegen` to fail if they are missing.

Test project attached.

Steps to reproduce:

- Unzip the attachment
- Run `xcodegen`
- Expected: project is generated
- Current: ```Error Domain=NSCocoaErrorDomain Code=260 "The folder “OptionalSources” doesn’t exist." UserInfo={NSFilePath=[…snip…]/xcodegen-test/OptionalSources, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7ffbd7700f50 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}```

[xcodegen-test.zip](https://github.com/yonaskolb/XcodeGen/files/2878673/xcodegen-test.zip)

**Comment by yonaskolb** [comment]
Fixed by https://github.com/yonaskolb/XcodeGen/pull/527
