### ISSUE TITLE
Can I share a folder between targets?

### ISSUE THREAD

**Issue by squarefrog** [yonaskolb/XcodeGen#528]
In a project I am working on, we have the following structure:

```
ProjectName
  |
  | FrameworkA
    | Sources
    | Tests
  | FrameworkB
    | Sources
    | Tests
```

We currently use the following yml

```
targets:
  FrameworkA:
    type: library.static
    platform: iOS
    sources:
      - path: Sources
        name: FrameworkA/Sources
    settings:
      INFOPLIST_FILE: ../ModuleInfo.plist
    configFiles:
      Debug: ../Configs/Module.xcconfig
      Release: ../Configs/Module.xcconfig
  FrameworkATests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        name: FrameworkA/Tests
    settings:
      INFOPLIST_FILE: ModuleInfo.plist
    dependencies:
      - target: Core
```

In the project, this results in two folders:

```
ProjectName
  |
  | FrameworkA
  | FrameworkATests
```

While this is fine, we would like to clean the structure up a little and end up with the following result:

```
ProjectName
  |
  | FrameworkA
    | Sources
    | Tests
```

Is this possible? I've tried setting the `sources -> path` to `FrameworkA/Sources` and `FrameworkA/Tests`, but that just used the literal name.

This could be related to https://github.com/yonaskolb/XcodeGen/issues/478

**Comment by yonaskolb** [comment]
Hi @squarefrog. #478 would give you more control, but see if `createIntermediateGroups: true` solves your problem. You can either set this in `options` or on a specific targetSource. See the docs here https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#options

```
options:
  createIntermediateGroups: true
targets:
  Framework:
    sources:
      - path: Sources
        createIntermediateGroups: true
```

**Comment by yonaskolb** [comment]
One other option would be to add `FrameworkA` in `fileGroups`. Once it's created anything within it will default to be under that group.

```yaml
fileGroups:
 - FrameworkA
targets:
  ...
```

**Comment by squarefrog** [comment]
`createIntermediateGroups` worked great, thank you! I'm sorry I missed that setting.
