### ISSUE TITLE
Clarification on customWorkingDirectory

### ISSUE THREAD

**Issue by johndpope** [yonaskolb/XcodeGen#538]
## Context 🕵️‍♀️
I'm building sample code for tensorflow / swift using xcodegen - I'm looking for clarification around specifying the working directory programmatically

![Screen Shot 2019-03-20 at 20 25 30](https://user-images.githubusercontent.com/289994/54674492-a5a48400-4b50-11e9-99a2-75a0ef4fd78b.png)

https://github.com/tensorflow/swift/pull/92

I searched through code and can see the bool for useCustomWorkingDirectory - but not the appropriate parameter name  for yml file. 

Once the command line project is running - it can read the local files in directory without explicit paths pointing to respective data directories - 

This line seems ok to me - but fails to create a proper scheme.
```yml

schemes:
  Debug:
    useCustomWorkingDirectory: "YES"
    customWorkingDirectory:  "."

```

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/ddc72791d651fdea4cee00c1db456cf6

In right hand side - by specifying the working directory as current directory - the build files show up. 
![Screen Shot 2019-03-20 at 20 40 30](https://user-images.githubusercontent.com/289994/54674672-0b910b80-4b51-11e9-9b3e-e06b9cb4320d.png)

**Comment by yonaskolb** [comment]
Hi @johndpope. Support for these options doesn't exist in the Scheme spec yet.
As more and more of these small options come up I'm beginning to think that maybe supporting them all is untenable. Schemes have a lot of options around them and are quite fast moving in terms of changes within Xcode. We might even have to start thinking about dropping off support for complex schemes, and letting people just create them in Xcode and checking them in. If XcodeGen didn't remove all shared schemes on generation, would this solve your use case, or do you need them to be totally dynamic definable in the project spec?
Adding support for user schemes that aren't deleted has been discussed here as well https://github.com/yonaskolb/XcodeGen/issues/515

**Comment by johndpope** [comment]
Hi Yonas, going to close this as I'm spring cleaning my github issues. 
I'm in Sydney these days in Mosman if you are ever around for a beer.
