### ISSUE TITLE
Related frameworks for Carthage doesn't work correctly

### ISSUE THREAD

**Issue by gunterhager** [yonaskolb/XcodeGen#539]
I've been testing the fairly new `includeRelated`  feature from PR #506. However i found that it doesn't work in a lot of cases because it seems that the .version files that Carthage creates don't include the correct dependencies. E.g. the Cartfile for ReactiveCocoa looks like this:

`github "ReactiveCocoa/ReactiveSwift" ~> 4.0`

While the .ReactiveCocoa.version file looks like this:

```
{
  "commitish" : "8.0.2",
  "iOS" : [
    {
      "name" : "ReactiveMapKit",
      "hash" : "76076624c54f5581b1ea27cd6a09aaeb2782e6264c07e931d74a6d956609f6e7"
    },
    {
      "name" : "ReactiveMapKit",
      "hash" : "76076624c54f5581b1ea27cd6a09aaeb2782e6264c07e931d74a6d956609f6e7"
    },
    {
      "name" : "ReactiveCocoa",
      "hash" : "a8aba842f99b4abc012afa17d7fd4f709322ce9ad75d9fb8746fd630f9fcf87a"
    },
    {
      "name" : "ReactiveCocoa",
      "hash" : "a8aba842f99b4abc012afa17d7fd4f709322ce9ad75d9fb8746fd630f9fcf87a"
    }
  ]
}
```

It seems to me, that the .version file approach isn't correct since it won't give you the framework's dependencies.

**Comment by yonaskolb** [comment]
Hi @gunterhager

It looks like perhaps you're looking at the incorrect Carthage dependency?
The version file you posted is from `github "ReactiveCocoa/ReactiveCocoa"` not `ReactiveCocoa/ReactiveSwift`.

When I have a Cartfile with `github "ReactiveCocoa/ReactiveSwift" ~> 5.0` I get the following `.ReactiveSwift.version` file 
```
{
  "Mac" : [
    {
      "name" : "ReactiveSwift",
      "hash" : "85dd96f4881602bf8160455385ca89da1dd569796da2f6663d2f2956bcab623d",
      "swiftToolchainVersion" : "4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)"
    }
  ],
  "watchOS" : [
    {
      "name" : "ReactiveSwift",
      "hash" : "af64c8ca915236568ad57f701fa122a4d8a95c23d255304e9d80a5dc65099efd",
      "swiftToolchainVersion" : "4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)"
    }
  ],
  "tvOS" : [
    {
      "name" : "ReactiveSwift",
      "hash" : "55ab9f4f9e8cd18b07d5edba3f3269790279ad848ebf641f42fc2f1d92ccad07",
      "swiftToolchainVersion" : "4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)"
    }
  ],
  "commitish" : "5.0.0",
  "iOS" : [
    {
      "name" : "ReactiveSwift",
      "hash" : "f7d2ad2119c43afb097e27a891807a4ec46935e3591a4dc19e2c442c7281fed0",
      "swiftToolchainVersion" : "4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)"
    }
  ]
}
```
Do you have any other issues with it?

One thing that might be an issue is that Carthage can generate version files that have duplicate entries in them, like you one you posted. When we parse these we should filter out these duplicates.

@mdiep do you know why Carthage generates these duplicates?

**Comment by yonaskolb** [comment]
@mdiep do you know why Carthage generates these duplicate version entries?

**Comment by gunterhager** [comment]
@yonaskolb i think i didn't make myself clear enough. What i meant was: when i use Carthage to include `ReactiveCocoa/ReactiveCocoa` (in my project's Cartfile it would look like this: `github "ReactiveCocoa/ReactiveCocoa" ~> 8.0`) i would expect XcodeGen to add ReactiveCocoa's dependencies when i use `includeRelated`. In my tests it didn't. Looking for the reason, i found that the `.ReactiveCocoa.version` file doesn't contain any reference to ReactiveSwift, so i think the information XcodeGen needs to include the dependencies just isn't there although in the Cartfile inside the ReactiveCocoa project the dependency is clearly mentioned as`github "ReactiveCocoa/ReactiveSwift" ~> 4.0`. I hope this makes the problem i have clearer.

**Comment by yonaskolb** [comment]
Ah, got it. Yeah XcodeGen can’t automatically track dependencies across different Carthage dependencies. Carthage doesn’t surface that information. You will need to reference both ReactiveSwift and ReactiveCocoa

**Comment by yonaskolb** [comment]
I’ll close this for now. Let me know if you have any more issues. Not that this PR renames the property to `findFrameworks` https://github.com/yonaskolb/XcodeGen/pull/543
