### ISSUE TITLE
correct usage of DEVELOPMENT_TEAM

### ISSUE THREAD

**Issue by DanielReyesDev** [yonaskolb/XcodeGen#551]
Hi

first off, thanks for all your hard work to make this awesome tool possible. I was trying to set the DEVELOPMENT_TEAM of my App but I couldn't make it work. I'm not sure what is the correct format of the development team. I've been trying with the following formats:

DEVELOPMENT_TEAM: ABCABCACBB
DEVELOPMENT_TEAM: 'ABCABCACBB'
DEVELOPMENT_TEAM: 'The Company LLC'

could you please orient me to set it correctly? I'm not sure if I need to set the TeamID, the full name of the profile or anything else.

Thanks in advance!

**Comment by AndrewBennet** [comment]
In my usage of this setting, it works when I set it to the Team ID, with a colon and no quotes. E.g.:

    DEVELOPMENT_TEAM: ABCDE12345

**Comment by yonaskolb** [comment]
@DanielReyesDev any of those variants should work. Perhaps the place you're applying this setting is incorrect? See https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md#configuring-build-settings for details.

```
settings:
  DEVELOPMENT_TEAM: The Company LLC
```

**Comment by yonaskolb** [comment]
Closing this for now. @DanielReyesDev feel free to reopen if you encounter any more issues
