### ISSUE TITLE
I want to install old version’s XcodeGen with Homebrew.

### ISSUE THREAD

**Issue by tony1224** [yonaskolb/XcodeGen#556]
I use Xcode10.1 now, so I’m not able to use XcodeGen’s latest version.
Also I’m not able to update Xcode for some reasons.
So can you provide old version for Homebrew?
By the way, I hope to use ver 2.0.0 now.

**Comment by yonaskolb** [comment]
Homebrew isn’t good at installing old versions. I suggest you use another installation method like download the release zip, building from source, or using Mint

**Comment by tony1224** [comment]
Thank you for your reply.
I don't understand how to use Mint well, so If I try to install XcodeGen in the same way on CI, such as Bitrise, can I solve it using Mint?

**Comment by tony1224** [comment]
```
$ brew reinstall "mint"
mint: A full installation of Xcode.app 10.2 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode 10.2 cannot be installed on macOS 10.13.
You must upgrade your version of macOS.
Error: An unsatisfied requirement failed this build.
Can't install formulas:  exit status 1
```
I’m not able to update Xcode for some reasons...

**Comment by yonaskolb** [comment]
This is the mint install script we run on a Bitrise setup step

```sh
#!/bin/bash

MINT_VERSION="0.11.3"

curl -#L "https://github.com/yonaskolb/Mint/releases/download/$MINT_VERSION/mint.zip" > mint.zip
unzip mint.zip
cp ./mint /usr/local/bin/mint
rm mint.zip
rm mint
```
This lets you install a specific version of Mint that will work for you (again, homebrew can't install older versions)

Then you can just run `mint bootstrap` to get all your packages

If you're on Bitrise another helpful thing to do is to add the following path to your CachePush step `/usr/local/lib/mint`. This will cache all the packages Mint builds

**Comment by tony1224** [comment]
I was able to solve this problem with your correct advice!
Thank you so much!
