### ISSUE TITLE
Use Regular Expression for Excludes Syntax

### ISSUE THREAD

**Issue by keehun** [yonaskolb/XcodeGen#563]
I would like to make a feature-request for using regular expression (or any other standard syntax) that would allow the wildcard (`*`) to cross a `/` or a `\`. Currently, it's impossible to add files only matching a certain rule (like an inverse `excludes` or an `includes`) throughout the entire codebase (e.g. only add file names starting with `Mock` to the test target).

This can be done currently with a glob rule like: `*/*/[!M][!o][!c][!k]*` but that would only match files not starting with "Mock" 3 directories deep. Once I add other rules to cover other directory levels, none of the files get added because no file can possibly "survive" through all the exclude rules due to the directory levels being built into the rules.

I would like to start making a transition where all of my `Mock*` classes reside right next to their respective classes (instead of in a separate `TestSource` directory), and this is the only blocker to achieving that today.

**Comment by yonaskolb** [comment]
Recursive globs we added in 2.7.0
You can now do things like `**/*.swift`
