### ISSUE TITLE
Ability to generate project.yml that describes existing .xcodeproj

### ISSUE THREAD

**Issue by wacumov** [yonaskolb/XcodeGen#565]
This feature will help to start using XcodeGen in existing projects with multiple targets and schemes.
Something like `xcodegen init` in the existing project directory. It would create project.yml file that contains the same targets, schemes and non-default settings values as the .xcodeproj file.
Then .xcodeproj can be ignored because it can be regenerated from the newly created project.yml file.

As of now, it requires a lot of efforts to create a project.yml file that duplicates an already existing [relatively big] project. It would be great to automate this job.

**Comment by yonaskolb** [comment]
Thanks for the suggestion @wacumov. That issue is tracked in #9, so I'll close this one
