### ISSUE TITLE
Target template duplications

### ISSUE THREAD

**Issue by haritowa** [yonaskolb/XcodeGen#574]
I have an issue when target template properties are duplicated each time `yml` file is included. 
Here is my sample setup:

```.
├── A
│   ├── Sources
│   │   └── AClass.swift
│   └── project.yml
├── B
│   ├── Sources
│   │   └── BClass.swift
│   └── project.yml
└── baseProject.yml

4 directories, 5 files
```

`baseProject.yml` contains target template `Core`:
```name: BaseProject
targetTemplates:
  Core:
    platform: iOS
    type: framework
    preBuildScripts:
      - name: Swifty Mocky
        script: echo "123"
```

Both `A/project.yml` and `B/project.yml` has an `- ../baseProject.yml` include. `xcodegen` invocation against `B/project.yml` leads to duplicated properties(build scripts, for example) for any target, that have the `Core` template.

![Duplicated Build Scripts](https://cl.ly/55fa3f4a7d5b/Image%2525202019-04-25%252520at%2525208.21.46%252520PM.png)

[Sample Project](https://github.com/yonaskolb/XcodeGen/files/3118139/project.zip)

**Comment by haritowa** [comment]
Hello everyone, I have made some progress:

- This issue relates to any spec element, not only target templates
- Any array value is multiplied

As far as I understand, the problem is that we have duplicated `subSpecs`, which forces this method https://github.com/yonaskolb/XcodeGen/blob/b490851c737809ee3cb545ee8ea41742cfb5a84d/Sources/ProjectSpec/SpecFile.swift#L85-L95 to merge spec onto itself.

I propose to merge each spec *file* only once. I already have the fix, which solves this issue and doesn't break any existing tests. 

Before any PR fuss, I want to be sure that this issue is actually a bug. So, after @yonaskolb provides details, I'll produce tests cases and open PR.

**Comment by haritowa** [comment]
Meanwhile, @nivanchikov, could you share your setup, which encounters the same problem? I want to test my fix against your case.

As far as I understand, you may bypass this issue adding `:REPLACE` suffix to any property you don't want to be merged. (Try to replace `preBuildScripts` with `preBuildScripts:REPLACE` in your target template.)

**Comment by yonaskolb** [comment]
@haritowa your setup indeed includes the base spec twice. If you want to handle a scenario like this instead of changing your includes, then a fix would be required to only include a path a single time. If you'd like to create a PR that would be great

**Comment by nivanchikov** [comment]
@haritowa @yonaskolb just checked #599 results with my setup, seems like the duplication issues have been resolved - at least from what I see from build phases and linked frameworks sections
