### ISSUE TITLE
how to update to a specific version?

### ISSUE THREAD

**Issue by kevin00223** [yonaskolb/XcodeGen#579]

**Comment by pvinis** [comment]
update what?

**Comment by kevin00223** [comment]
> update what?

update my current version of xcodegen. like from 1.10.3 to the latest

**Comment by pvinis** [comment]
how did you install it?

**Comment by kevin00223** [comment]
> how did you install it?

brew install xcodegen

**Comment by pvinis** [comment]
https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

**Comment by kevin00223** [comment]
> https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

thx! that's what i need!

**Comment by pvinis** [comment]
Remember to close the issue ;)

**Comment by yonaskolb** [comment]
Thanks @pvinis
