### ISSUE TITLE
Support Includes in Sources

### ISSUE THREAD

**Issue by dpfannenstiel** [yonaskolb/XcodeGen#584]
This feature request is to add an `includes` property on the *Sources* for a project.

In a project with a file hierarchy similar to:
```
+ root
  + common
    - shared_resource
    + test-resources
  + OtherProject
  + XcodeProject
    - project.yml
    + Source
    + SourceTests
      + resources
        - test-resource
```

I want to be able to import the contents of test-resources to both OtherProject and XcodeProject.  Within XcodeProject it should be stored within the SourceTests/resources group.

**Comment by yonaskolb** [comment]
Hi @dpfannenstiel. I'm not sure if I understand fully.

Currently you can use sources outside of the root
```
targets:
  XcodeProject:
    sources:
      - ../common/test-resources
```
I believe what you're trying to do is add this group within `SourceTests/resources` correct? For that I think you would need this issue to be completed https://github.com/yonaskolb/XcodeGen/issues/478

**Comment by dpfannenstiel** [comment]
Yes.

By adding `../common/test-resources` directly to the project as a source it becomes another group along with `Source` and `SourceTests`.  That's makes it's use unclear.

The goal would be to add it as a group under `SourceTests/resources`.  I had attempted to use the `name` property to that effect.  But `group` makes a lot more sense.  I'd be happy closing this as a dup of #478.

**Comment by yonaskolb** [comment]
Tracking this in #478 👍
