### ISSUE TITLE
How to dependent a cocoapods target

### ISSUE THREAD

**Issue by smalllixin** [yonaskolb/XcodeGen#586]
My app depends on some cocoapods project.
And the framework target generated by xcodegen need import module from cocoapods.

SomeApp:
  - MyLibA

Podfile:
LibB

// in MyLibA source code
import LibB //No such module 'LibB'

I just do not find any elegant solution for this. Any practice solve this  plz?

**Comment by cs-filipe-jordao** [comment]
I believe you should add the LibB library to the MyLibA target dependencies on your Podfile.
Xcodegen has nothing to do with it since cocoa pods will create a workspace from your .xcodeproject.

**Comment by FilipeJrd** [comment]
I believe you should add the LibB library to the MyLibA target dependencies on your Podfile.
Xcodegen has nothing to do with it since cocoa pods will create a workspace from your .xcodeproject.

**Comment by smalllixin** [comment]
> I believe you should add the LibB library to the MyLibA target dependencies on your Podfile.
> Xcodegen has nothing to do with it since cocoa pods will create a workspace from your .xcodeproject.

I cannot use this way because there's may many xcodegen targets depend on many cocoapods target. It is hard to maintain.

My final solution is create a target template. Which specify the xcconfig file cocoapods generated.

configFiles:
      Debug: "Pods/Target Support Files/Pods-XXXXX/Pods-XXXXX.debug.xcconfig"
      Release: "Pods/Target Support Files/Pods-XXXXX/Pods-XXXXX.release.xcconfig"
