### ISSUE TITLE
Childs targets

### ISSUE THREAD

**Issue by AlexisQapa** [yonaskolb/XcodeGen#591]
Splitting my app into smaller frameworks, I found great help from templates. There is still something bothering me, we can't associate a child target/template to another. 

How awesome it would be to define: 
A Unit test template
A UI test template
A "Data" framework template (having an associated Unit test template)
A "UI" framework template (having an associated UI test template)
Some "Data" and "UI" frameworks

and then XcodeGen could generate all targets and their associated tests targets.

Additionally as "UI" framework could inherit from "Data" framework it could gain Units tests target for free if associated target/template is an array

**Comment by AlexisQapa** [comment]
Maybe this could be only some kind of helper generating tests targets (not going generic associated targets)

**Comment by yonaskolb** [comment]
Do you have an example of what this would look like in a spec? 

What if `include` files had access to attributes like target templates do? That would allow you to set up related targets in a single file and then include it multiple times. 

A note that this PR would break that, and would need to be updated to allow multiple files with different attributes https://github.com/yonaskolb/XcodeGen/pull/599
