### ISSUE TITLE
`.pch` files are bundled as resources

### ISSUE THREAD

**Issue by thii** [yonaskolb/XcodeGen#593]
`.pch` files are prefix headers but they are bundled as resources.

**Comment by yonaskolb** [comment]
Thanks for opening @thii. Would you like to create a PR for this? It should be a one line change here https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/SourceGenerator.swift#L222

**Comment by thii** [comment]
Will do.
