### ISSUE TITLE
How To Disable Main Thread Checker

### ISSUE THREAD

**Issue by muehlemann** [yonaskolb/XcodeGen#596]
Im trying to toggle the `disableMainThreadChecker` flag on my test scheme but when setting the option and generating the project the change is not reflected.

I would like to know if I am either approaching this incorrectly or if XcodeGen even supports this functionality.

### Schemes
    "schemes" => {
      "Base" => {
        "build" => {
          "targets" => {
            "Base" => "all",
            "BaseTests" => ["test"],
            "BaseUITests" => ["test"]
          },
          "parallelizeBuildables" => true, 
          "buildImplicitDependencies" => true
        },
        "run" => {
          "config" => "Debug",
          "environmentVariables" => {
            "OS_ACTIVITY_MODE" => "disable"
          }
        },
        "test" => {
          "config" => "Debug",
          "disableMainThreadChecker" => true,
          "gatherCoverageData" => true,
          "targets" => [
            "BaseTests",
            "BaseUITests"
          ],
          "environmentVariables" => {
            "OS_ACTIVITY_MODE" => "disable"
          },
        },
        "profile" => {
          "config" => "Debug"
        },
        "analyze" => {
          "config" => "Debug"
        },
        "archive" => {
          "config" => "Debug",
          "revealArchiveInOrganizer:" => true
        }
      }
    }

Any help would be greatly appreciated!
Cheers

**Comment by yonaskolb** [comment]
Added in https://github.com/yonaskolb/XcodeGen/pull/601
