### ISSUE TITLE
SPM packages and Test Plans

### ISSUE THREAD

**Issue by ethanjdiamond** [yonaskolb/XcodeGen#606]
Hi! I was wondering if XcodeGen was going to support two new features I'd like to try out with Xcode 11.
- [SPM packages](https://developer.apple.com/videos/play/wwdc2019/408/)
- [Test Plans](https://developer.apple.com/videos/play/wwdc2019/413/). 

I think I saw that xcodeproj support packages now.

**Comment by yonaskolb** [comment]
Yeah I've been working a bit on SPM packages in my spare time. Here's a preview

<img width="458" alt="Screen Shot 2019-06-30 at 1 54 28 pm" src="https://user-images.githubusercontent.com/2393781/60392395-193d3080-9b45-11e9-910c-c8c88d09b734.png"> 
<img width="983" alt="Screen Shot 2019-06-30 at 1 55 09 pm" src="https://user-images.githubusercontent.com/2393781/60392394-193d3080-9b45-11e9-8abc-2c57c4760976.png">

Test Plans first needs XcodeProj support

**Comment by kdubb** [comment]
@yonaskolb Any thoughts on a alpha/beta release with SPM support. This solves _a lot_ of issues for us.

On a general note... kudos to you for creating and maintaining this project. Once discovered we've found it completely indispensable. Thank you!

**Comment by AlexisQapa** [comment]
Started using Xcode 11 with SPM thinking this is great but it will be hard to forget XcodeGen and then I saw this issue.

**Comment by bonkey** [comment]
Wonderful! :)

**Comment by rvanmelle** [comment]
Yeah ... thanks.  Funny, also was playing around and had a working prototype locally, very similar syntax, but I think I like yours better: 
```packages:
  Yams:
    package: https://github.com/jpsim/yaml
    version: 2.0.0 < NextMajor
  Yams:
    package: https://github.com/jpsim2/yaml
    version: 2.0.0 < NextMinor
  Yams:
    package: https://github.com/jpsim2/yaml
    version: 2.0.0 < 3.0.0
  Yams:
    package: https://github.com/jpsim2/yaml
    version: 2.0.0
  Yams:
    package: https://github.com/jpsim2/yaml
    branch: feature/cool
  Yams:
    package: https://github.com/jpsim2/yaml
    commit: afqwerqwefasdf
```

**Comment by zdnk** [comment]
What about the issue with resolving packages since `Package.resolved` file is inside the generated `xcodeproj`?

**Comment by rvanmelle** [comment]
One part that I haven't figured out properly yet either is support for local packages --- they kind of appear automagically if the source directory is listed (i.e. xcode recognizes them as a package etc.), but I don't have the the associated framework being linked properly against the targets.  I was kind of working with a methodology of *not* needing to explicitly declare local packages in the toplevel `package` section...

**Comment by ethanjdiamond** [comment]
Could we do any folder with a Package.swift file in it? That's roughly what's going on with Xcode.

**Comment by yonaskolb** [comment]
Swift Package support has been added here https://github.com/yonaskolb/XcodeGen/pull/624

Please test it out on your projects.

**Comment by yonaskolb** [comment]
@zdnk:
>What about the issue with resolving packages since Package.resolved file is inside the generated xcodeproj?

the `Package.resolved` file gets created by Xcode here. `Project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`
If you want to check that file in selectively you can do so, without checking in the actual `.pbxproj`.

@rvanmelle:
> One part that I haven't figured out properly yet either is support for local packages --- they kind of appear automagically if the source directory is listed (i.e. xcode recognizes them as a package etc.), but I don't have the the associated framework being linked properly against the targets. I was kind of working with a methodology of not needing to explicitly declare local packages in the toplevel package section...

@ethanjdiamond
> Could we do any folder with a Package.swift file in it? That's roughly what's going on with Xcode.

What you are seeing is opening a `Package.swift` or it's directory directly in Xcode, which is another form of SPM integration that Xcode provides. What we are aiming to do with XcodeGen though is to generate an Xcode project that can utilise Swift packages, which is the other form of integration. This is required because iOS projects for example can't be defined with just a simple `Package.swift` as SPM doesn't yet have support for bundles and resources and all the complexities that come with iOS app.

**Comment by smeshko** [comment]
@yonaskolb, awesome work with SPM! Have there been any updates about test plans support?

**Comment by yonaskolb** [comment]
Closing this in favour of https://github.com/yonaskolb/XcodeGen/issues/684
