### ISSUE TITLE
Copy frameworks only when installing

### ISSUE THREAD

**Issue by Elland** [yonaskolb/XcodeGen#608]
Is there a way to set this flag for a Copy Files phase?

**Comment by yonaskolb** [comment]
Hi @Elland. What do you mean exactly by `Copy frameworks`?
At the time there isn't a way to control that on any of the build phases. This happens through a `buildActionMask` property on the build phase.
What is your use case?

**Comment by Elland** [comment]
Hey @yonaskolb, I wanted the generated project configuration to only copy frameworks when installing, for faster build+launch times.

**Comment by jsorge** [comment]
I'm running into this now, where I need this checkmark checked in my Embed Frameworks build phase:
<img width="1079" alt="Screen Shot 2020-03-29 at 9 58 04 PM" src="https://user-images.githubusercontent.com/2585841/77876637-694a4000-7208-11ea-8981-f536f6a3f298.png">

Here's what my project file looks like without the checkmark:
```
/* Begin PBXCopyFilesBuildPhase section */
		FC21B861D79C5E0F1CFC6599 /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 12;
			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				637EF3B657CC45F576440008 /* GooglePlaces.framework in Embed Frameworks */,
				9CB073B21DCB818D51414013 /* GoogleMaps.framework in Embed Frameworks */,
				84A3FAC8FC437CBCF002801A /* GoogleMapsCore.framework in Embed Frameworks */,
				238BC22DAEFDEA871E9C4988 /* GoogleMapsBase.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXCopyFilesBuildPhase section */
```

And here's with the checkmark:
```
/* Begin PBXCopyFilesBuildPhase section */
		FC21B861D79C5E0F1CFC6599 /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 8;
			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				637EF3B657CC45F576440008 /* GooglePlaces.framework in Embed Frameworks */,
				9CB073B21DCB818D51414013 /* GoogleMaps.framework in Embed Frameworks */,
				84A3FAC8FC437CBCF002801A /* GoogleMapsCore.framework in Embed Frameworks */,
				238BC22DAEFDEA871E9C4988 /* GoogleMapsBase.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 1;
		};
/* End PBXCopyFilesBuildPhase section */
```

This setting should go on the `target` I think since it applies to all the frameworks being embedded. @yonaskolb if you have guidance on how this might be done (and the level of difficulty to do) I might be able to pull it off. Thanks!

**Comment by yonaskolb** [comment]
Just talked to @jsorge offline about a way forward and landed on a property on Target called `onlyCopyFilesOnInstall` which will affect all `PBXCopyFilesBuildPhase` in that target, and also the Carthage script that copies the frameworks

**Comment by Elland** [comment]
Thanks @yonaskolb that's great to hear! 💪

**Comment by jsorge** [comment]
Sorry this PR took so long to open!

**Comment by Noegon** [comment]
> Just talked to @jsorge offline about a way forward and landed on a property on Target called `onlyCopyFilesOnInstall` which will affect all `PBXCopyFilesBuildPhase` in that target, and also the Carthage script that copies the frameworks

Sorry, that asking here. But I strongly need to set “onlyCopyFilesOnInstall=true“ flag to one build phase, an “onlyCopyFilesOnInstall=false“ on another. Is it possible?

**Comment by jsorge** [comment]
@Noegon So you've got multiple embed framework build phases and one needs this turned on and another doesn't? The way I built the PR that's not possible, and I'm not sure offhand what it would take to make that possible.

I'm very curious about your use-case though. Can you share any more specifics about what you're doing?

**Comment by Timidercrayon55** [comment]
/* Begin PBXCopyFilesBuildPhase section */
		FC21B861D79C5E0F1CFC6599 /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 8;
			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				637EF3B657CC45F576440008 /* GooglePlaces.framework in Embed Frameworks */,
				9CB073B21DCB818D51414013 /* GoogleMaps.framework in Embed Frameworks */,
				84A3FAC8FC437CBCF002801A /* GoogleMapsCore.framework in Embed Frameworks */,
				238BC22DAEFDEA871E9C4988 /* GoogleMapsBase.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 1;
		};
/* End PBXCopyFilesBuildPhase section */

**Comment by Timidercrayon55** [comment]
/* Begin PBXCopyFilesBuildPhase section */
		FC21B861D79C5E0F1CFC6599 /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 8;
			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				637EF3B657CC45F576440008 /* GooglePlaces.framework in Embed Frameworks */,
				9CB073B21DCB818D51414013 /* GoogleMaps.framework in Embed Frameworks */,
				84A3FAC8FC437CBCF002801A /* GoogleMapsCore.framework in Embed Frameworks */,
				238BC22DAEFDEA871E9C4988 /* GoogleMapsBase.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 1;
		};
/* End PBXCopyFilesBuildPhase section */
