### ISSUE TITLE
localised .intentdefinition to sources does not work

### ISSUE THREAD

**Issue by cremnet** [yonaskolb/XcodeGen#614]
While adding localised .intentdefinition file it does not generates source files, because it imports as resource.

directory structure:
```
    |_ App/Sources/Base.lproj/Intents.intentdefinition
    |_ App/Sources/en.lproj/Intents.intentdefinition
    |_ App/Sources/ru.lproj/Intents.intentdefinition
```

project.yml:
```
sources:
   - path: App/Sources
      buildPhase: sources
```

**Comment by bartl1985** [comment]
same issue ... did you find a workaround?

**Comment by giginet** [comment]
I'm working to fix this issue.
I'll submit PR after few days. Please moment.
https://github.com/yonaskolb/XcodeGen/compare/master...giginet:intent-definitions?expand=1

**Comment by bartl1985** [comment]
Cool

**Comment by kikettas** [comment]
Do you know any workaround until this gets fixed?

**Comment by giginet** [comment]
Hi, I've just submitted #720. This PR help you to solve this issue.
Could you try with this patch?

**Comment by kaannesinn** [comment]
thanks @giginet :+1: waiting for the release version
