### ISSUE TITLE
Select Copy only when installing in Build Phase > Embed Frameworks

### ISSUE THREAD

**Issue by PeqNP** [yonaskolb/XcodeGen#615]
One of my frameworks requires the "Copy only when installing" option to be _checked_ in Build Phase > Embed Frameworks. I haven't found a way to perform this operation automatically. Right now I have to check the option every time I rebuild the project file.

Is there a way to do this?

**Comment by d-date** [comment]
+1
App Extension is also needed

**Comment by farshadtx** [comment]
You can use `onlyCopyFilesOnInstall` at target level.

**Comment by PeqNP** [comment]
Nice! I'll try that. Thank you!

**Comment by Noegon** [comment]
> You can use `onlyCopyFilesOnInstall` at target level.

And what if I need this checkbox checked only for one single extension? Is it possible to set checkbox not on target level, but on BuildPhase level?
