### ISSUE TITLE
Persist `Deployment Info - Devices`

### ISSUE THREAD

**Issue by TheInkedEngineer** [yonaskolb/XcodeGen#618]
Is there a way currently to set from the `project.yml` the supported devices (i.e.: iPhone)? Every time the `xcodegen` command is run, devices turns back to `universal` value.

If not currently supported, is there a way around it? 
Is it in the pipeline for the near future?

**Comment by GabrielMassana** [comment]
I'm also having the same problem.
Any Solution on this?

**Comment by yonaskolb** [comment]
Given that this is a pretty core setting that many apps might set, we could potentially even add this as a built in option on `target`:
```yml
targets:
  MyApp:
    # other target properties
    devices: [iPhone]
```
This could then also accept `iPad`, and potentially also `Mac` which would set the required settings for Catalyst

**Comment by TheInkedEngineer** [comment]
@GabrielMassana thank you for the answer.
@yonaskolb thank you too, and for that tip. Didn't think about it that way. Cheers
