### ISSUE TITLE
Multiple test targets created when using template

### ISSUE THREAD

**Issue by PeqNP** [yonaskolb/XcodeGen#629]
I'm having an issue where defining the `testTargets` value in a template is causing the respective test target to be added twice in the "Test Scheme". When declared outside of the test target no issues are seen.

Here is what I'm seeing in Xcode:
<img width="893" alt="duplicate-test-target" src="https://user-images.githubusercontent.com/1482394/63304109-c5261100-c296-11e9-8922-505c7537a05d.png">

Here is the module's configuration file:
<img width="429" alt="Foundation-config" src="https://user-images.githubusercontent.com/1482394/63304241-32d23d00-c297-11e9-8a7e-f564891e497f.png">

Here is the `Templates.yml` file which I use to generate the "test application" which is used to run the module's tests.
<img width="1056" alt="Templates-config-file" src="https://user-images.githubusercontent.com/1482394/63304130-dbcc6800-c296-11e9-8dc9-2a5f0b0fffd5.png">

I would expect that the `NBFoundationTests` would only be added once as a test target in the scheme.

**Comment by PeqNP** [comment]
I figured it out. This is fascinating. I was including the `Foundation.yml` file in two config files, `Api.yml` and the main `project.yml` file. That's what caused the problem.

**Comment by yonaskolb** [comment]
Interesting you bring this up @PeqNP, as a PR was JUST merged that fixes this edge case, and makes sure included files only merge their content in once, even if they are referenced multiple times https://github.com/yonaskolb/XcodeGen/pull/599

**Comment by PeqNP** [comment]
Thank you so much!
