### ISSUE TITLE
Set language and region of action in scheme

### ISSUE THREAD

**Issue by benrudhart** [yonaskolb/XcodeGen#630]
I'm trying to set the `language` and `region` of a scheme: The one you can setup in Xcode via  Edit Scheme > Options > "Application Language" and "Application Region"

When setting this in Xcode the scheme simply get's this new lines in test specified Action:
```
      language = "value"
      region = "value"
```

I know it's possible to set something like this in `schemes.target.action`
```
environmentVariables:
        -AppleLocale: <myLocale>
```

But: Is there a way to configure the language and region in a way you can do through Xcode as described above?

**Comment by PycKamil** [comment]
[Check documentation](https://github.com/yonaskolb/XcodeGen/blob/bdc9928a91dd7da67f908fce0133f566304f34ab/Docs/ProjectSpec.md#common-build-action-options) of _language_ and _region_

**Comment by benrudhart** [comment]
thank you. missed that one
