### ISSUE TITLE
setting requiresObjCLinking: true on target didn't add '-ObjC' anywhere in the build settings

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#639]
setting requiresObjCLinking: true on target didn't add '-ObjC' anywhere in the build settings

**Comment by yonaskolb** [comment]
Setting this actually adds `-ObC` to anything that uses that target as a dependency, as mentioned in the docs https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target. Is this not happening. 
If you want to add this to a specific target you can do so via the `OTHER_LDFLAGS`
```yaml
settings:
  OTHER_LDFLAGS: -ObjC
```

**Comment by brandtdaniels** [comment]
Maybe add that to the docs

> If you want to add this to a specific target you can do so via the OTHER_LDFLAGS
