### ISSUE TITLE
Support Scheme Templates

### ISSUE THREAD

**Issue by nevillco** [yonaskolb/XcodeGen#643]
As mentioned in the project spec, `targetScheme` is a convenience API that has a subset of the functionality of declaring top-level `scheme`s. I'm a user who requires the extra API surface of the top level `scheme`, but now, because they are no longer part of the target, I have no way of reusing common code between schemes like I had with `targetTemplates`. It would be nice to be able to define reusable schemes in that way.

**Comment by yonaskolb** [comment]
Yeah, this is a great idea @nevillco! Happy to accept a PR for this. I can help you out along the way

**Comment by bclymer** [comment]
PR that has this working. Needs review / docs / cleanup yet.

**Comment by bclymer** [comment]
Closing as this implemented here - https://github.com/yonaskolb/XcodeGen/pull/672
