### ISSUE TITLE
`settings` and `settingsGroup`: difference from xcconfig ?

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/XcodeGen#65]
Is there any difference from using xcconfig?
What are pros/cons ?

Related: https://github.com/yonaskolb/XcodeGen/pull/64#issuecomment-331669653

**Comment by yonaskolb** [comment]
`settings` are used to provide settings on a target or project. `settingsGroup` can be referenced from `settings` or other `settingGroups`. They are similar to `xcconfig` files but have a bit more power.

**Setting group advantages**
- can specify build settings or other setting groups by config
- written in the same spec using the same language so easier to use

**Xcconfig advantages**
- can reuse files already in use in a project

So I would say use `settingGroups` unless you want to use any custom `xcconfig` files you've already created.

**Comment by toshi0383** [comment]
Thank you for the clarification!
