### ISSUE TITLE
How do I enable code coverage only for specific targets?

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#660]
How do I enable code coverage only for specific targets?
How do I generate a scheme with these properties?

      codeCoverageEnabled = "YES"
      onlyGenerateCoverageForSpecifiedTargets = "YES">
      <CodeCoverageTargets>
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "D742B60F5C181EB748CF94C3"
            BuildableName = "MyApp.app"
            BlueprintName = "MyApp"
            ReferencedContainer = "container:MyApp.xcodeproj">
         </BuildableReference>
      </CodeCoverageTargets>

**Comment by bclymer** [comment]
Since `gatherCoverageData` is a `Bool` I don't think that's possible at the moment. Seems like a reasonable addition though.

**Comment by brandtdaniels** [comment]
Yes, the issue is that code coverage currently reports on all the dependencies as well.

**Comment by brandtdaniels** [comment]
The PR for this recently go merged into master. Do we know when they will release it via brew?

**Comment by yonaskolb** [comment]
It has already been released 👍

**Comment by brandtdaniels** [comment]
Is coverageTargets supposed to work under a TargetScheme or only under a TestAction?
