### ISSUE TITLE
Xcode 11 Support?

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#662]
My team is not able to build on device using our release configuration with Xcode 11. Has Xcodegen been tested with Xcode 11?

**Comment by yonaskolb** [comment]
Hi @brandtdaniels, yep should be working. Do you have some more information, what error are you running into?

**Comment by brandtdaniels** [comment]
Currently all I can tell is that Xcode freezes up while attempting to build a dependency or two in release mode on a device. It may not be related to XcodeGen but I wanted to run it you by to make sure.

**Comment by kylebrowning** [comment]
That sounds directly related to a Swift compiler bug. Some other dependency you have is hanging.
Try disabling the optimization level and I bet it works.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless target.name == 'DEPENDENCY'
    target.build_configurations.each do |config|
      next unless config.name.start_with?('Distribution')
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    end
  end
end
```

**Comment by brandtdaniels** [comment]
This was caused by one of our dependencies:

https://github.com/scinfu/SwiftSoup/issues/125
