### ISSUE TITLE
Enable Base localization

### ISSUE THREAD

**Issue by haemi** [yonaskolb/XcodeGen#680]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/183958/66385531-eebf0700-e9c0-11e9-9f47-450098d36755.png">

how can I fix this warning? Tried to set a

```
knownRegions: ["en", "de", "Base"]
```

element on top level, but didn't help...

**Comment by bclymer** [comment]
I'm seeing this after updating to Xcode 11.1 yesterday. It appears in all of the projects generated by XcodeGen.

**Comment by yonaskolb** [comment]
I think this PR should fix it https://github.com/yonaskolb/XcodeGen/pull/685
Can you please test this on your projects.

You can do so easily with mint if you have it installed
```
mint run yonaskolb/xcodegen@add_base_localisation
```

**Comment by lukewakeford** [comment]
Hey I'm looking for the documentation for adding localisations to a project using xcodegen, can anyone point me in the right direction? 🙏🏻
