### ISSUE TITLE
Support for TestPlan

### ISSUE THREAD

**Issue by keremgund** [yonaskolb/XcodeGen#684]
As starting with Xcode11 Apple introduces TestPlans, XcodeGen still doesn't have support to generate project using Test Plans.

**Comment by bartzet** [comment]
Hi @yonaskolb 

Do you have any ETA when the support for the TestPlans will be introduced?

**Comment by yonaskolb** [comment]
Test plans support has been added to XcodeProj in 7.2, so this can be started. I personally don't have time right now, but if someone wants to pick it up that would be great

**Comment by ramharshvardhan** [comment]
Hello @yonaskolb! Any updates on supporting Test Plans for XcodeGen? Would love to take advantage of it.

**Comment by yonaskolb** [comment]
Released in 2.29.0
