### ISSUE TITLE
No Test Host set on macOS

### ISSUE THREAD

**Issue by mtancock** [yonaskolb/XcodeGen#695]
I opened #678 a while ago and happy to report that the last release fixed that regression 👍 

The next problem I've run in to, is that while my test target is generated, the Host Application for the test target is blank.

Example project yaml:

```name: Project
settings:
  DEVELOPMENT_TEAM: 
options:
    bundleIdPrefix:  
targets:
    DirectTests:
      platform: macOS
      type: bundle.unit-test
      sources:
        - Tests/
      dependencies:
        - target: Direct
      gatherCoverageData: true
      settings:
        configs:
          debug:
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: MACOSTESTING_DIRECT
    Direct:
      type: application
      platform: macOS
      deploymentTarget: "10.14"
      sources:
        - /Common
        - /macOS
      settings:
        PRODUCT_BUNDLE_IDENTIFIER: 
      scheme:
        testTargets:
          - DirectTests
```
I've looked through some previous issues and can see tangentially related things, but nothing that seems obvious (to me). What am I doing wrong?

If I do the same thing with an iOS target it works fine.

**Comment by mjarvis** [comment]
Not sure of the solution yet but just doing some investigation, by generating a project and checking it into GIT, and then setting the test host and looking at the GIT diff, it looks like XcodeGen is failing to set the following items in the `.pbxproj`:

1. Additional `TargetAttributes` object in the `PBXProject` Project object section
2. `BUNDLE_LOADER` in the test target's build settings
3. `TEST_HOST` in the test target's build settings.

Next step is to look for these objects and settings in the xcodegen source to see how the iOS test generation differs from macOS.

It is also likely there is some way you could manually generate these settings though it might be awkward.

**Comment by mjarvis** [comment]
Looks like #452 Was the change that introduced the desired functionality, but was not tested for a macOS target.
Something in the checks in there must be failing for a macOS target vs iOS.

Next step is to add a test spec for a macOS testing target (if its not already in master), validate failure, and then figure out which check is failing.

**Comment by mjarvis** [comment]
First pass of testing, looks like it might be setting `TEST_HOST`, but setting it incorrectly.
Changing the test host to the correct value in xcodegen after generating fixtures results in:
```
-	TEST_HOST = "$(BUILT_PRODUCTS_DIR)/App_macOS.app/App_macOS";
+	TEST_HOST = "$(BUILT_PRODUCTS_DIR)/App_macOS.app/Contents/MacOS/App_macOS";
```
