### ISSUE TITLE
Localized .intentdefinition file cant be added to compile sources 

### ISSUE THREAD

**Issue by kaannesinn** [yonaskolb/XcodeGen#702]
Hi,

After adding localization support to .intentdefinition file, Xcodegen includes the .intentdefinition file and its localization strings files as a resource not as a source file.

I have founded the issue #439 , .intentdefinition file's compile source support was given with this fix. but its localized case isnt working still. (using Xcodegen 2.10 and Xcode 11.1 ) 

I have tried 3 cases on my .yml file below but it doesnt solve the problem;

```
- path:  Sources/SharedIntents/TranslateIntent.intentdefinition
  buildPhase: sources
```

or 

```
- path:  Sources/SharedIntents
  buildPhase: sources
```

or 

```
- path:  Sources/SharedIntents/Base.lproj/TranslateIntent.intentdefinition
  buildPhase: sources
```

BTW .intentdefinition file doesnt have an attributed string for target membership type like "public-project-private" with Xcodegen.

**Comment by giginet** [comment]
Same as #614

**Comment by kaannesinn** [comment]
Is there any PR or fix for this (and #614 )?

**Comment by giginet** [comment]
@kaannesinn Sorry for waiting for you. I'll fix them as soon as possible and we should ship on next release 🙏

**Comment by giginet** [comment]
I close this issue because it is the same as #614. I'll notify you of the progress on #614.

**Comment by kaannesinn** [comment]
@giginet no problem ;) want to know whether there is a progress on PR. 
OK, waiting for you :)

**Comment by kaannesinn** [comment]
@giginet is there a way to pull these last changes on xcodegen master with "brew upgrade xcodegen" etc? I think it is not tagged still as like "2.10.2" .

**Comment by yonaskolb** [comment]
@kaannesinn this is now released with 2.11.0

**Comment by kaannesinn** [comment]
thanks @yonaskolb 👍 but `brew upgrade xcodegen` doesnt give 2.11.0 for now.

`*** ~ % brew upgrade xcodegen`
`Warning: xcodegen 2.10.1 already installed`

`***~ % brew info xcodegen `
`xcodegen: stable 2.10.1 (bottled), HEAD`
`Generate your Xcode project from a spec file and your folder structure`
`https://github.com/yonaskolb/XcodeGen`
`/usr/local/Cellar/xcodegen/2.10.1 (27 files, 5.8MB)`
 ` Poured from bottle on 2019-12-03 at 15:57:28`
`From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/xcodegen.rb`
`==> Requirements`
`Build: xcode ✔`
`==> Options`
`--HEAD`
	`Install HEAD version`
`==> Analytics`
`install: 4,513 (30 days), 14,624 (90 days), 28,738 (365 days)`
`install-on-request: 4,512 (30 days), 14,620 (90 days), 28,732 (365 days)`
`build-error: 0 (30 days) `

**Comment by yonaskolb** [comment]
It has to be merged into brew first https://github.com/Homebrew/homebrew-core/pull/47426

**Comment by kaannesinn** [comment]
hmm ok I thought it is done also
