### ISSUE TITLE
Location simulation

### ISSUE THREAD

**Issue by raptorxcz** [yonaskolb/XcodeGen#722]
Hi,

Is it possible to set location simulation in scheme?

Thanks

<img width="497" alt="Screenshot 2019-11-20 at 08 10 46" src="https://user-images.githubusercontent.com/3967087/69216786-52feea00-0b6d-11ea-9195-3480c40a7b5c.png">

**Comment by yonaskolb** [comment]
This isn't currently possible, but happy to accept a PR

**Comment by brentleyjones** [comment]
Resolved with #756.
