### ISSUE TITLE
projectReferences path is not resolved correctly

### ISSUE THREAD

**Issue by PycKamil** [yonaskolb/XcodeGen#729]
Looks like there is some kind of issue in resolution of path in `projectReferences`. When I would like to reference a project is upper directory like `path: ../../Test/Test.xcodeproj` it will cause error message for project not found. Changing it to incorrect path `path: Test/Test.xcodeproj` will work but that create a wrong reference. Quick workaround for this issue is to create symbolic link to actual project in current folder but it would be nice to fix it properly.

**Comment by yonaskolb** [comment]
Are you running XcodeGen with any arguments, like --spec or --project, and are you using any includes?

**Comment by PycKamil** [comment]
Yes I am using `--spec` argument

**Comment by yonaskolb** [comment]
Yeah, though so. I don’t think the project reference paths are being set relative to the spec base path.
As a workaround for now you should be able to run XcodeGen in the same directory as your spec

**Comment by yonaskolb** [comment]
@kateinoigakukun

**Comment by kateinoigakukun** [comment]
@PycKamil Sorry for late reply, could you try this branch https://github.com/yonaskolb/XcodeGen/pull/740?
