### ISSUE TITLE
Best way to set Always Embed Swift Standard Libraries on the project level

### ISSUE THREAD

**Issue by brandtdaniels** [yonaskolb/XcodeGen#730]
Trying to run tests on the Firebase device farm and I am getting errors such as:

`Library not loaded: @rpath/libswiftUIKit.dylib`

Is there an easy way to set Always Embed Swift Standard Libraries on the project level?

From reading the docs, the only way I can see doing it looks like this:

```
  settingPresents:
    all:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: Yes
```

I think though that this isn't the correct usage of settingPresets because it doesn't work.

**Comment by yonaskolb** [comment]
```
settings:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
```

**Comment by brandtdaniels** [comment]
ok I see it now...it wasn't listed in the Index section of the project spec document that's why I missed it.

**Comment by yonaskolb** [comment]
Configuring build settings is covered here https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Usage.md
