### ISSUE TITLE
The best way to assign different command line arguments to different schemes

### ISSUE THREAD

**Issue by kliukin** [yonaskolb/XcodeGen#732]
Hey guys!

What would be the best way to give different command line arguments to different schemes?

The following setup gives the same argument to all listed schemes:

<img width="259" alt="Screenshot 2019-11-27 at 17 37 11" src="https://user-images.githubusercontent.com/24508036/69732373-9395cf00-113c-11ea-8f49-6c79435c9c28.png">

**Comment by yonaskolb** [comment]
Hi @kliukin. If you want different command line arguments per config variant, you will have to create the schemes separately using the extended `schemes` definitions which are documented here https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#scheme

(I also noticed you had a typo in `-FIRDubugEnable` if that helps in the future) :)

**Comment by kliukin** [comment]
Hi @yonaskolb! 
Yes, I had to define all schemes separately which is a bit verbose as we have many of them. 

Thanks for your help)

**Comment by yonaskolb** [comment]
@kliukin cool, glad you got it sorted. If your scheme definitions are quite large you can also leverage `scheme templates` to reduce duplication https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#scheme-template
