### ISSUE TITLE
Unable to install watchOS app

### ISSUE THREAD

**Issue by nickromano** [yonaskolb/XcodeGen#736]
Using the current [TestProject](https://github.com/yonaskolb/XcodeGen/tree/master/Tests/Fixtures/TestProject) I am unable to install and run the watchOS app scheme.

The error message is: "Could not install at this time. No WatchKit 1.0 app bundle found for app com.project.app.watch.extension".

XCode - Version 11.2.1 (11B500)
Latest version of XcodeGen

**Comment by yonaskolb** [comment]
Hmm, at first glance I'm not sure why this is either

**Comment by yonaskolb** [comment]
I think this might have something to do with the generated scheme for watch apps and `BuildableProductRunnable` vs `RemoteRunnable` within the `LaunchAction`. Will have to dig deeper another time

**Comment by daltonclaybrook** [comment]
I am seeing this issue as well. When I replace the generated scheme with one that includes both a `BuildActionEntry` for my host iOS app and a `RemoteRunnable` entry, the Watch app builds and runs correctly in the simulator (have not tested on device).
