### ISSUE TITLE
Add Organization Name in spec file

### ISSUE THREAD

**Issue by Christian-Seiler** [yonaskolb/XcodeGen#746]
I would like to have the organization name added in my projects. (as for copyright notice)

**Comment by yonaskolb** [comment]
@Christian-Seiler I left a comment in your PR. This is possible by using project attributes

```yml
attributes:
  ORGANIZATIONNAME: My Org
```

**Comment by yonaskolb** [comment]
Closing this for now. Let me know if you have any issues
