### ISSUE TITLE
Setting On-Demand-Resource Tags

### ISSUE THREAD

**Issue by sipao** [yonaskolb/XcodeGen#750]
Is there way to setting on-demand-resource tags?

<img width="251" alt="2020-01-06 18 59 24" src="https://user-images.githubusercontent.com/40229310/71810923-d4c3bc00-30b6-11ea-95e1-2567bda3becc.png">

**Comment by yonaskolb** [comment]
Hi @sipao. This isn't currently possible. But looking at the diffs of a project when you add one of these tags, it seems pretty easy to add.
- The project gets a new attribute `KnownAssetTags`
- The relevant PBXBuildFile gets an `ASSET_TAGS` setting

To surface this `SourceFile` could get an optional `resourceTags` array
```
sources:
  - path: Path/To/File.asset
    resourceTags: [tag1, tag2]
```

If you'd like to create a PR for this I could help you out
