### ISSUE TITLE
How to have several XcodeGen versions?

### ISSUE THREAD

**Issue by kornerr** [yonaskolb/XcodeGen#757]
If XcodeGen were a gem, I would simply use Bundler. However, XcodeGen is different.

Is there a way to have several versions of XcodeGen just like several versions of CocoaPods / Fastlane with Bundler?

**Comment by brentleyjones** [comment]
You can use [Mint](https://github.com/yonaskolb/Mint) with a [Mintfile](https://github.com/yonaskolb/Mint#mintfile) to pin to and use specific versions.

**Comment by kornerr** [comment]
Thanks!
