### ISSUE TITLE
Move "Link Binary With Libraries" before "Copy Bundle Resources"

### ISSUE THREAD

**Issue by mrtsamma** [yonaskolb/XcodeGen#761]
I use external frameworks that need to be linked and signed.
At distribution(uploading app) time I faced signing issues with these frameworks.
Then found the solution: 
had to move "Link Binary With Libraries" before "Copy Bundle Resources" in "Build Phases".
![LinkBinaryWithLibraries_before_CopyBundleResources](https://user-images.githubusercontent.com/11760624/73072831-a7507e00-3ebe-11ea-954a-83c656b6b48c.png)

Currently did it manually in Xcode. But didn't find the way to do it in the project spec - YML file.
Could anyone help?

**Comment by yonaskolb** [comment]
Thanks for the report @mrtsamma. Fixed in #768 👍

**Comment by yonaskolb** [comment]
Released in 2.13.0
