### ISSUE TITLE
"Enable Base Internationalization" warning is disabled

### ISSUE THREAD

**Issue by myihsan** [yonaskolb/XcodeGen#789]
This issue is caused by #694.

I totally agree that we should enable Base Internationalization. 
However, I think this PR disable the warning unintentionally. 

> no `Base.lproj` folder but one for the development language

In this case, the warning should be shown, and the user can solve it from Xcode.
After that, there is no such warning even after running `xcodegen` again since `Base.lproj` folder will be created by Xcode.

**Comment by yonaskolb** [comment]
Hmm, yes this was my intuition as well. @bryansum thoughts?

**Comment by bryansum** [comment]
I'm reading this thread to help regain context https://github.com/yonaskolb/XcodeGen/pull/685

I tried to reproduce the original warning by recreating the same scenario (only `knownRegions:  en`, with no `Base.lproj` folder, just using Xcode), but it seems like that warning is no longer reproducing in Xcode 11.3.1. Perhaps this warning was removed by Apple? Would be good for someone else to verify. If that's the case then we should probably remove it.

I guess there's a philosophical element to this as well: when Xcodegen creates a project, is the desire to set similar defaults as an Xcode new project? By default projects have Base internationalization enabled, but I could also see an argument that we shouldn't turn that on for people that don't want it -- especially when it's not always needed, like when the base matches matches the development language.

**Comment by myihsan** [comment]
> but it seems like that warning is no longer reproducing in Xcode 11.3.1.

And it returns in Xcode 11.4 beta. I have no idea why.

> when Xcodegen creates a project, is the desire to set similar defaults as an Xcode new project?

I can see the point, however, I think setting `Base` to `knownRegions` only disable the warning and have no effect to promoting the user to use Base Internationalization since there is no `Base.lproj` folder.
Therefore, I guess it may be better to keep the warning and let the user decide.

**Comment by bryansum** [comment]
I still can't reproduce the original warning, but it definitely did exist at one point (see the related Cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/9187). Not quite sure how to proceed -- I have a revert ready here if desired: https://github.com/yonaskolb/XcodeGen/pull/791

@myihsan if you can, would you mind sharing an example Xcode project that surfaces the warning? Would be helpful to reproduce the original issue.

**Comment by myihsan** [comment]
@bryansum 
As my tests, it seems like the warning certainly appears in the version newer than the version you unchecked **Use Base Internationalization**.
But somehow, it also appears in the current version sometimes and hard to tell why since the warning may not be updated until relaunched Xcode or done a clean.

If you need, I can create an example project by Xcode 11.1.

**Comment by bryansum** [comment]
@myihsan thanks, got it working by following your instructions (create a new project in Xcode 11.0, remove base internationalization, then open in any of 11.1, 11.3.1, 11.4 beta 2). In this case I can see that the Xcode fix it actually *does* offer to move files from `en.lproj` to a new `Base.lproj` folder. 

Given that behavior, I agree we should revert. @yonaskolb to review #791?

**Comment by yonaskolb** [comment]
Cool, will merge
