### ISSUE TITLE
Duplicate filenames in different paths confuse Xcode 11.3.1

### ISSUE THREAD

**Issue by sleepygarden** [yonaskolb/XcodeGen#794]
I'm using XCodeGen to generate a fairly large project for a build server out of many smaller components - many of the files included have the same name (ex: `LabelViewModel.swift`) but different paths ex:`Alpha/LabelViewModel.swift vs Beta/LabelViewModel.swift`. When using the New Build System for the xcodegen generated projects, I get compiler failures for each of these sets of files: 
```
filename "LabelViewModel.swift" used twice: 'Alpha/LabelViewModel.swift' and 'Beta/LabelViewModel.swift`
note: filenames are used to distinguish private declarations with the same name
```
Cleaning / clearing derived data / etc doesn't doesn't fix it, however visiting both of the `LabelViewModel`s, removing each from the build target, and readding them will cause just those files to settle. The diff on the generated proj file after removing + readding the files looks straightforward so i'm not sure what to make of it

```
-               2901F66CA0AD2B6C87F30E6A /* LabelViewModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7E9330481E62D35CE93FA361 /* LabelViewModel.swift */; };
+               7E19F7B42409B9E700846CAC /* LabelViewModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7E9330481E62D35CE93FA361 /* LabelViewModel.swift */; };
+               7E19F7B62409B9F500846CAC /* LabelViewModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = A80EF6E9F9FC23881314933F /* LabelViewModel.swift */; };
-               877FFACDC67ECFDDD74EFCBF /* LabelViewModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = A80EF6E9F9FC23881314933F /* LabelViewModel.swift */; };
//...
-                               877FFACDC67ECFDDD74EFCBF /* LabelViewModel.swift in Sources */,
-                               2901F66CA0AD2B6C87F30E6A /* LabelViewModel.swift in Sources */,
//...
+                               7E19F7B42409B9E700846CAC /* LabelViewModel.swift in Sources */,
+                               7E19F7B62409B9F500846CAC /* LabelViewModel.swift in Sources */,
```

I'm going to also attempt to build this on the legacy build system, but that is giving me `Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.` which could be for a dozen reasons - this is my first pass at making a macro project out over 1000 source files, I'm sure it wouldn't work on the first try.

Any advice why XCode is giving me this usually unrelated bug would be greatly appriciated.

**Comment by myihsan** [comment]
This issue seems not related to XcodeGen since I can produce this error without XcodeGen, and the Xcode pointed out the reason—filenames are used to distinguish private declarations with the same name.

> removing each from the build target, and readding them will cause just those files to settle.

I don't know if we should discuss it here.
But I couldn't get rid of that error by re-adding them. Could you try again in a brand new Xcode project without XcodeGen?
