### ISSUE TITLE
coverageTargets cannot work in 2.13.0

### ISSUE THREAD

**Issue by angelmic** [yonaskolb/XcodeGen#795]
I still cannot make `coverageTargets` to work with version 2.13.0.

```
targets:
  MyApplication:
    type: application
    platform: iOS
    settings:
      configs:
        Debug: debug
        Release: release
    scheme:
      gatherCoverageData: true
      coverageTargets:
        - MyApplication
```

Am I missing something obvious here?

**Comment by yonaskolb** [comment]
I think the `TargetScheme` isn't forwarding `coverageTargets` to `Scheme` here https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/SchemeGenerator.swift#L310. It should be a one line change if you'd like to open a PR for it? 
```swift
coverageTargets: [.local(target.name)],
```
