### ISSUE TITLE
Is it possible to omit schemes only for specific targets?

### ISSUE THREAD

**Issue by soffes** [yonaskolb/XcodeGen#811]
The schemes created by default are great. For just a few targets, I'd like to omit them. I tried `scheme: null` and a few other things, but that wasn't working. Is this possible and I'm missing something or is this not supported?

Thanks!

**Comment by yonaskolb** [comment]
Hi Sam. If you don’t specify a scheme for a target it won’t be generated. However, when you open an Xcode project it will auto create any missing schemes for you, which is what I believe you’re experiencing. I think there’s a way to suppress that, but I can’t remember how, I’m just on my phone at the moment.

**Comment by soffes** [comment]
@yonaskolb ya I'm not creating any schemes with XcodeGen. I guess that's what's happening. If you find out how to supress this, that would be awesome!

**Comment by keith** [comment]
To disable Xcode's behavior you can set IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded to false in the workspace settings. If you uncheck this box in the scheme editor you can also see Xcode serialize this setting.

**Comment by soffes** [comment]
The scheme was left over from my old workspace and not created my XcodeGen 🤦‍♂
