### ISSUE TITLE
Homebrew release for 2.15.0?

### ISSUE THREAD

**Issue by evandcoleman** [yonaskolb/XcodeGen#816]
Is there going to be a Home-brew release for 2.15.0? Homebrew is saying 2.14.0 is the latest version.

**Comment by yonaskolb** [comment]
PR open here https://github.com/Homebrew/homebrew-core/pull/52306
Thanks for the heads up, and sorry for the oversight!

**Comment by evandcoleman** [comment]
Thanks!!

**Comment by yonaskolb** [comment]
@evandcoleman its been merged on homebrew now 👍
