### ISSUE TITLE
Multiple entitlement files per target?

### ISSUE THREAD

**Issue by ileitch** [yonaskolb/XcodeGen#841]
There doesn't seem to be a way for a target to generate more than one entitlement file, is that correct? If so, how are people handling entitlements that have configuration dependent values, such as `aps-environment`?

**Comment by yonaskolb** [comment]
Hi @ileitch, if you need more flexibility you can create you own entitlement files, and reference them with the `CODE_SIGN_ENTITLEMENTS` build settings as per normal. Being able to generate them is just a helper for very simple projects 👍

**Comment by ileitch** [comment]
We do that currently, I was just looking to generate them instead using XcodeGen. I'll just stick with managing them manually, thanks.

**Comment by yonaskolb** [comment]
@ileitch if you wanted to you could submit a PR that would let you generate them per config
