### ISSUE TITLE
Question: Why don't we generate specs with the cli? 

### ISSUE THREAD

**Issue by 2075** [yonaskolb/XcodeGen#859]
hey there,

dropping out of anything xcode and swift related for a while and taking some detours with rust and yarn, etc, I was coming back to xcode to port some library and astonished about so many fragments of package and project management tools. i was wondering, though, why we cannot use xcodegen to generate a project/package spec?

this would make life much easier. e.g. 'xcodegen init' creates an empty workspace spec based on the folder name. or 'xcodegen add carthage <repo>' adds a carthage package everywhere needed and 'xcodegen add project <name> ios' another project into your workspace.

wouldnt this ease the overall developer experience? or are there reasons i dont get now from a naive perspective. as most packages seem selfcontained, it shouldnt be necessary to resolve complex dependency trees yet. right?

**Comment by yonaskolb** [comment]
Yeah would definitely be useful. There's a very old issue here to track that https://github.com/yonaskolb/XcodeGen/issues/18

Perhaps https://github.com/tuist/tuist would be good for your needs?

**Comment by 2075** [comment]
Hey there, yes, already using it. Why don't you guys join forces? Keep up the good stuff.
