### ISSUE TITLE
Xcodegen is now known as struct!

### ISSUE THREAD

**Issue by helbertgs** [yonaskolb/XcodeGen#867]
```
You can migrate to the new gem by running 'gem install struct'.
The struct 1.0 release contains a huge number of bug fixes, and the
groundwork for spec 1.2.0. Stay tuned for more updates!
```

Really?

**Comment by yonaskolb** [comment]
Hi @helbertgs. XcodeGen hasn't changed its name. There is a similar older project written in Ruby called struct https://github.com/lyptt/struct. Funnily enough it seems back in the early days of that project its author @lyptt had also called it XcodeGen, and had then renamed it, before this project was ever born.
@lyptt is there any chance putting a notice there, or even removing the deprecated gem if most people are using the newer struct? https://rubygems.org/gems/xcodegen

**Comment by lyptt** [comment]
@yonaskolb 'fraid not. The gem's still in use by past companies I've worked for.

**Comment by yonaskolb** [comment]
@lyptt no worries
