### ISSUE TITLE
Project with nested xcconfigs included in sources breaks

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#87]
Currently if I generate a project that has a xcconfig set for the configuration, and also includes the directory the xcconfig file lives in in the `sources` of a target, the project ends up in a broken state:

![image](https://user-images.githubusercontent.com/283886/31579659-9b5f39ba-b0ef-11e7-81e4-88dd5fe84928.png)

This is the configuration for this case:

```yaml
name: Project
configs:
  Debug: debug
configFiles:
  Debug: xcconfigs/debug.xcconfig
targets:
  Project:
    type: application
    platform: iOS
    sources: xcconfigs
```

Sample project (with the generated project) as an example: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1385032/XcodeGenTest.zip)

**Comment by yonaskolb** [comment]
Interesting, thanks for opening the issue @keith. I'll have to debug this.
In the meantime, maybe adding the xcconfig folder as a plain file group instead of a target source will fix the issue?
```
name: Project
configs:
  Debug: debug
configFiles:
  Debug: xcconfigs/debug.xcconfig
fileGroups:
  - xcconfigs
targets:
  Project:
    type: application
    platform: iOS
```

**Comment by keith** [comment]
That does seem to fix this case! Thanks! You can close this if that should be the workaround for this?

**Comment by yonaskolb** [comment]
Let's leave this open, as your original spec should still be valid

**Comment by yonaskolb** [comment]
Fixed in  https://github.com/yonaskolb/XcodeGen/commit/b2a2a01da7e9a3d04d7adfa8ad5877f67b62dfbd
