### ISSUE TITLE
Implement Localization Debugging

### ISSUE THREAD

**Issue by rvi** [yonaskolb/XcodeGen#873]
Hi, 

I'd like to implement the Localization Debugging toggle and do a PR. Any guidelines/advices on how you would do it? Ideally I'd like to merge it in this project so everyone can benefit from this change.

<img width="642" alt="Screen Shot 2020-05-27 at 9 26 56 AM" src="https://user-images.githubusercontent.com/1455122/83046816-5ed7d700-9ffc-11ea-9f76-8cbdeaa47953.png">

**Comment by brentleyjones** [comment]
https://github.com/yonaskolb/XcodeGen/blob/master/Sources/ProjectSpec/Scheme.swift
and
https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/SchemeGenerator.swift

Are the main places to modify. 

And we use values from https://github.com/tuist/XcodeProj/tree/master/Sources/XcodeProj/Scheme

**Comment by rvi** [comment]
Thanks @brentleyjones will look at it when I have the time!
