### ISSUE TITLE
Running the shell script before project generation

### ISSUE THREAD

**Issue by mrtsamma** [yonaskolb/XcodeGen#901]
What is the best solution to run a shell script before the project generation starts if any?
I'm using SwiftGen to have type-safe assets and localization usage in my app.
I want to remove generated files from the repository and run generation script before project generation and then after every build(the last part is easy). Files are needed to be generated before project generation, so they're added to the project.

One solution is to create setup.sh where I run the 
Swiftgen and other needed scripts for the project and in the end xcodegen.
Is there any alternative way? 
Sth like 
```
preGenerationScripts:
  - swiftgen.sh
  - someAnotherCoolScript.sh
```

This works, but then I need to reconfigure all Jenkins jobs 😞  and force every teammate to use a new solution - which doable, but thought, maybe there is a better way to do it already or planned.

**Comment by muizidn** [comment]
That would be some extension for the main purpose of XcodeGen.
```
XcodeGen is a command line tool written in Swift that generates your Xcode project using your folder structure and a project spec.
```

**Comment by CraigSiemens** [comment]
There's a `preGenCommand` option in the project spec that does what you're asking for.

**Comment by mrtsamma** [comment]
> There's a `preGenCommand` option in the project spec that does what you're asking for.

Thank you very much! That's what I need!
