### ISSUE TITLE
Xcode 12 and Base Internationalization

### ISSUE THREAD

**Issue by liamnichols** [yonaskolb/XcodeGen#954]
👋 It's another year so time for a discussion about the handling of Base Internationalisation in Xcode 12. I'm trying to wrap my head around the history of this since it seems vast so to recap:

1. #680 - Original issue of _"Enable Base Internationalization"_ warning in Xcode 11
2. #685 - Fix for original issue that adds base localisation by default
3. #694 - Addendum to handle scenarios where there is no Base.lproj directory on disk
4. #791 - Reverts last amendment and instructs us to add a **.gitkeep** file instead.

Xcode 12 has now come along and I think we need to revisit things. My unlocalised framework project is now producing the dreaded warning:

<img width="264" alt="Screenshot 2020-09-22 at 13 52 17" src="https://user-images.githubusercontent.com/482871/93884451-d54ec200-fcda-11ea-9c36-ed23b78a4a43.png">

This warning now shows despite the fact that I have zero localisable content whatsoever.

I started a new framework project in Xcode 12 to check the default behaviour and discovered that both the development language and Base are included by default:

<img width="1281" alt="Screenshot 2020-09-22 at 13 53 17" src="https://user-images.githubusercontent.com/482871/93884563-f9120800-fcda-11ea-9ee8-e554ef91d8df.png">

I then unchecked the _"Enable Base Internationalization"_ box, removed `LastUpgradeCheck` and restarted Xcode to see the warning again so my gut feeling is that we should so back to an approach where we populate `knownRegions` with `Base`, `pbxProject.developmentRegion ?? "en"`, and `sourceGenerator.knownRegions`. 

Does that sound reasonable? Or am I missing something? I can go ahead and make these changes if so

**Comment by myihsan** [comment]
```swift
pbxProject.knownRegions = knownRegions.isEmpty ? pbxProject.developmentRegion! : knownRegions
```
This may be better since we can only use `Base.lproj` without `developmentRegion.lproj`.

About the force unwrapping:
https://github.com/yonaskolb/XcodeGen/blob/775e14c48f0f55be3faecf550e39da50932dfa74/Sources/XcodeGenKit/PBXProjGenerator.swift#L102

And we should only set `Base` by `knownRegions` when `Base.lproj` is existing since `knownRegions` reflects all nonempty `.lproj` folders.

https://github.com/yonaskolb/XcodeGen/blob/775e14c48f0f55be3faecf550e39da50932dfa74/Sources/XcodeGenKit/SourceGenerator.swift#L477

Indeed, if there is no `Base.lproj`, Xcode will show the "Enable Base Internationalization" warning. 
However, we should keep the warning and let the user decides. #789 is the reason in detail.

**Comment by liamnichols** [comment]
@myihsan:

> Indeed, if there is no `Base.lproj`, Xcode will show the "Enable Base Internationalization" warning.
> However, we should keep the warning and let the user decides. #789 is the reason in detail.

I’m not sure I follow as this doesn’t match up to my experience. 

In my project (that does not utilise localised storyboards or xibs), checking the _”Enable Base Internationalisation”_ does nothing other than add `Base` to the `knownRegions` array.  I have an `en.lproj` directory that contains English phrases but nothing prompts me to move them or creates `Base.lproj` and from what I can tell, that’s correct behaviour.

With that in mind, does it make sense for me to have to create empty `Base.lproj` directories to opt out? 

I’d rather have a project spec setting called `enableBaseInternationalization` that I can set in my base spec since I generate multiple projects and having to commit multiple .gitignore files to suppress the warning seems like a poor work around

**Comment by myihsan** [comment]
@liamnichols 
> In my project (that does not utilise localised storyboards or xibs), checking the ”Enable Base Internationalisation” does nothing other than add Base to the knownRegions array.

You are right. The prompts only show when there are localized storyboards or xibs. I didn't notice it.

> With that in mind, does it make sense for me to have to create empty Base.lproj directories to opt out of getting that prompt/warning each time I generate the project?
>
> I’d rather have a project spec setting called `enableBaseInternationalization`

I agree with you. The issue here is that XcodeGen does not add `Base` to `knownRegions` if there is no `Base.lproj`, but Xcode adds `Base` if ”Enable Base Internationalisation” is checked. So adding `enableBaseInternationalization` (with a default value `true`?) seems perfect to me.

**Comment by liamnichols** [comment]
One other thing is that it seems we want to be careful to preserve the warning when we need it. 

If I understand correctly, when base internationalisation is enabled, `.storyboard` and `.xib` files should be placed within the `Base.lproj` directory so we could potentially surface this warning when running the generator?

For example, if the generator concludes that `Base` is to be included in `KnownRegions`, we could then output a warning for each `.storyboard` or `.xib` resource that isn't located within `Base.lproj`...

Would that be a wise thing to do?

**Comment by liamnichols** [comment]
So #955 has merged which configures the project file in the same way that Xcode 12 does by default but we still need a little more work to address concerns previously raised in #789.

Essentially, if an Xcode project does not have base localisation enabled and if a user has interface builder resources located in a non-base localisation directory (i.e **en.lproj**) then Xcode will help you to move them to **Base.lproj** when enabling base localisation. 

We can't easily get Xcode do to this again since we don't want to force a **Base.lproj** directory on people who don't need it, but we still do want to help people ensure their interface builder resources are in the correct location. 

My suggestion (but might need a bit more discussion) is to print a warning if we find interface builder resources (.xib, .storyboard) in the wrong directory while generating that instructs you to move them into **Base.lproj**.

One other thing I'm not sure of, but is there a reason for us to ever not want Base localisation enabled? It's now the default in Xcode 12, but you can also still disable it but I can't work out if/why anybody would ever want to do that.

**Comment by myihsan** [comment]
> we could then output a warning for each .storyboard or .xib resource that isn't located within Base.lproj

Xcode does not warn in this situation, so I think it might not be necessary. 
We can reproduce this situation by enabling Base Internationalization, then uncheck the checkbox of Base from the file inspector. 

To reproduce the behavior of Xcode, `enableBaseInternationalization` is enough to me.

The reason I issued #789 is, the XcodeGen always reenable Base Internationalization when I tried to find out some behavior of Xcode about Base Internationalization. But as you thought, I have no reason not to enable Base Internationalization.

**Comment by liamnichols** [comment]
Thanks for the insight @myihsan 

> Xcode does not warn in this situation, so I think it might not be necessary.

Yeah I realised that, but Xcode's warning only seems to come when you finally do opt into using Base Internationalisation as a one-time thing. 

Since we don't have that explicit opt-in behaviour then I felt that a warning might be more appropriate.

But, saying that, the `enableBaseInternationalization` project spec setting with a default to `true` is probably the simpler solution that saves us having to match up Xcode's logic behind the warning.
