### ISSUE TITLE
Using outdated version of Yams

### ISSUE THREAD

**Issue by liambutler-lawrence** [yonaskolb/XcodeGen#969]
I'm using XcodeGen as a SPM dependency in my Swift CLI tool, but it requires Yams 2.x, when 4.x is the latest. Fortunately I was able to downgrade Yams in my project without any ill effects, but is there any reason not to upgrade? Happy to open the PR

Error reproducible with this Package.swift:
```
let package = Package(
    dependencies: [
        .package(url: "https://github.com/jpsim/Yams.git", from: "4.0.0"),
        .package(url: "https://github.com/yonaskolb/XcodeGen.git", from: "2.18.0"),
    ],
)
```

**Comment by brentleyjones** [comment]
Resolved with #984.
